### ISSUE TITLE
Feature Request - Refresh Custom Queries 

### ISSUE THREAD

**Issue by tophertimzen** [BloodHoundAD/BloodHound#100]
It would be nice if I did not have to reinitialize BloodHound when I am working on custom queries. The cypher blog posts mentions "On Windows, the file falls under AppData\Roaming\bloodhound. Anything in this file will be loaded into the BloodHound user interface whenever it initializes." and it would be appreciated if there was something along the lines of a "query refresh" so I can pull in json queries more quickly.

**Comment by rvazarkar** [comment]
Added in https://github.com/BloodHoundAD/BloodHound/commit/d902ec080d0712228b7173c8b2df1729fc229e13
