### ISSUE TITLE
Missing Language Support might lead to skipped Account / Systems

### ISSUE THREAD

**Issue by new-gen23** [BloodHoundAD/BloodHound#101]
Hi,
I just setup an english Domain Controller and 2 german clients. After all systems were hocked up to the domain and the bloodhound powershell script was running, I observed some exceptions during the execution. 
After digging a while into the script, I discovered that it matches against (for example) the group "Administrators", which in german would be "Administratoren". 
I tried to modify the script as all local user enumerations failed on the german client and tried to add a language identification with the "get-culture" function. Sadly, this fill only identify the "local" language, where the PS script is running. If the script discovers that the local langange is de_DE, it won't help to enumerate the accounts on a remote english client.
My second attempt was to enumerate both languages. If english fails with an exception, it should be possible to continue with a try/catch block. Sadly, my PS scripting is not good enough and it ignored all my "catch-blocks" completely.

Any idea how to approach this?

**Comment by rvazarkar** [comment]
I'm not entirely sure yet what the best way to do this is, but its a problem we'll have to tackle sooner or later. I don't have anything concrete for now, but we will be working on this at some point.

**Comment by new-gen23** [comment]
Actually, the only approach I see would be brute force. Enumerate all systems in english. If it throws an exception or returns nothing, switch to another language. Howoever, the results would have to be normalized to english. Otherwise, other tools like bloodhound cannot parse it properly or drop it silently.

**Comment by leechristensen** [comment]
@new-gen23 Does [PowerView's](https://github.com/PowerShellMafia/PowerSploit/blob/dev/Recon/PowerView.ps1) Get-NetLocalGroup return the locale-specific group names when it's run against the de_DE hosts from the English machine?

**Comment by rvazarkar** [comment]
This problem has been solved in the new Ingestor, and should work across all localizations
