### ISSUE TITLE
Process is terminated due to StackOverflowException.

### ISSUE THREAD

**Issue by ebrinkster** [BloodHoundAD/BloodHound#106]
When BloodHound is run on a large AD environment I receive the following error message (repeated twice):
`Process is terminated due to StackOverflowException.`

This occurs after the `group_memberships.csv` file hits approximately 100mb.

Is this due to limited resources?  It is running on a virtualized PC with slightly limited resources (computing power and memory).  I have had no previous problems with BloodHound when it has been run on a bare metal desktop or server.

**Comment by rvazarkar** [comment]
Try the new ingestor at https://github.com/BloodHoundAD/SharpHound/releases

There's lots and lots of fixes, and this shouldn't happen anymore.
