### ISSUE TITLE
older data store version

### ISSUE THREAD

**Issue by Cypher-D** [BloodHoundAD/BloodHound#108]
get this when trying to connect to the sample db with neo4j 3.2.2

"Failed to start neo4j with an older data store version To enable automatic upgrade, please set configuration parameter to "dbms.allow_format_migration=true"

Cannot find in your wiki what version of neo4j works with the sample database, nor can i find the correct config file to change the parameter for upgrading.

**Comment by itseco** [comment]
Same issue here, using net4j 3.2.3

**Comment by itseco** [comment]
You must uncomment the line dbms.allow_format_migration=true in the configuration file. To find the path for configuration path open the neo4j Community Edition and hit the Options button.

**Comment by rvazarkar** [comment]
I believe @andyrobbins has updated the ingestor, Otherwise, you can use the configuration parameter suggested by @itseco
