### ISSUE TITLE
user_sessions.csv ComputerName has a lot of IPs

### ISSUE THREAD

**Issue by markgamache** [BloodHoundAD/BloodHound#110]
"10.201.182.23","dude@contoso.com","1"
"10.49.45.218","dude@contoso.com","1"
"10.236.145.177","dude@contoso.com","1"
"10.208.120.9","dude@contoso.com","1"
"10.208.120.9","dude@contoso.com","1"
"[2001:506:28:4206:5eb9:1ff:fe9c:605c]","dude@contoso.com","1"
"[2001:506:28:4206:5eb9:1ff:fe9c:5e40]","dude@contoso.com","1"

**Comment by rvazarkar** [comment]
This happens when PTR records aren't set in DNS. Sessions come back as ip addresses, which we attempt to resolve to the proper DNS name. If it fails, the fallback is to the IP address. Not really all that much that can be done to solve this unfortunately

**Comment by markgamache** [comment]
The code my be too thick for me to read well, but presumably, you know the
name of the host because you found it in AD first.  I'd prefer the code
assume that this is actually the host it reached, than return the IP.  My
DNS is almost completely PTR free.  :-P

Maybe a flag for not doing the reverse lookup?


This email is copyrighted, any unauthorized reproduction will result in
prosecution.  Restrictions may apply.  Always read email in accordance with
approved safety guidelines.


NSA, I am a US Citizen.  If this email is "inadvertently" collected please
remove it from your "metadata".

**Comment by rvazarkar** [comment]
Unfortunately, no. The NetSessionEnum function returns data in the following format:

```
typedef struct _SESSION_INFO_10 {
  LPWSTR sesi10_cname;
  LPWSTR sesi10_username;
  DWORD  sesi10_time;
  DWORD  sesi10_idle_time;
} SESSION_INFO_10, *PSESSION_INFO_10, *LPSESSION_INFO_10;
```
sesi10_cname is just an IP address, and username is the non-domain prefixed username. 

So if we're enumeration mgamache.testlab.local, we'll get a bunch of session info with IPs coming in to that system. The only way to figure out where those sessions are originally from is a PTR lookup.

**Comment by rvazarkar** [comment]
The corresponding code in a more easily readable format is here:

https://github.com/BloodHoundAD/SharpHound/blob/master/Sharphound2/Enumeration/SessionHelpers.cs#L141

**Comment by rvazarkar** [comment]
I think we may have come up with a sort of solution to this, which is in SharpHound. If PTR lookups fail, we'll fall back to using NetWkstaGetInfo to get a NetBios/Domain Name, and then do a forward lookup for that host name. Hopefully it'll work better?

**Comment by markgamache** [comment]
Sounds awesome.  Is it in the code now?  If so, I will pull and recompile
and have a look.


This email is copyrighted, any unauthorized reproduction will result in
prosecution.  Restrictions may apply.  Always read email in accordance with
approved safety guidelines.


NSA, I am a US Citizen.  If this email is "inadvertently" collected please
remove it from your "metadata".

**Comment by rvazarkar** [comment]
Yes, it's committed to SharpHound.

https://github.com/BloodHoundAD/SharpHound/blob/master/Sharphound2/Utils.cs#L71-L100

**Comment by rvazarkar** [comment]
I'm tentatively closing this for now. Feel free to re-open it if theres more issues
