### ISSUE TITLE
Feature: Map hyper-V host if found

### ISSUE THREAD

**Issue by markgamache** [BloodHoundAD/BloodHound#111]
Any admin on they hyper-V host can take over a VM it it is not bitlockered.  
$hyperVHost = (get-item "HKLM:\SOFTWARE\Microsoft\Virtual Machine\Guest\Parameters" -ErrorAction SilentlyContinue).GetValue("HostName")

**Comment by rvazarkar** [comment]
I believe you require Remote Registry as well as admin rights to enumerate this on remote hosts?

**Comment by markgamache** [comment]
Wow!  I must have been drunk.  Yes, you are correct.


This email is copyrighted, any unauthorized reproduction will result in
prosecution.  Restrictions may apply.  Always read email in accordance with
approved safety guidelines.


NSA, I am a US Citizen.  If this email is "inadvertently" collected please
remove it from your "metadata".

**Comment by dp001** [comment]
Instead of the registry way, you can check the SPNs. The same way can be used to hunt for Terminal Server/Citrix hosts

**Comment by rvazarkar** [comment]
Going to close this for now
