### ISSUE TITLE
Credential parameter missing

### ISSUE THREAD

**Issue by ama21n** [BloodHoundAD/BloodHound#113]
Is it possible to run bloodhound from a workstation / non-domain associated host, using enumerated domain credentials?

It appears Invoke-Bloodhound may be missing the -Credential parameter, which is available on other powersploit functions that perform a very similar task.

Alternatively, using BloodHound within a PS shell after running "runas /netonly /user:<domain>\<username><powershell.exe_path>" doesn't work either. The following error is given:
"Current security context is not associated with an Active Directory domain or forest."

Powersploit's dev branch has a number of functions (eg Find-DomainUserLocation & Get-DomainComputer) that support comma separated values with the -Credential parameter, I would have thought this functionality would have ported over to BloodHound

Is there anything obvious I may not have tried or seen?

**Comment by rvazarkar** [comment]
https://github.com/BloodHoundAD/SharpHound/releases

RunAs should work with both the .ps1 and exe. Give it a try and let me know!

**Comment by raul5660** [comment]
@rvazarkar i'm having an issue when trying to do the run as. I do the following:
```
runas /netonly /user:DOMAIN\USER powershell.exe
cd C:\Users\user\Desktop\BloodHound-master\BloodHound-master\Ingestors
Import-Module .\SharpHound.ps1
```
I then get the following:
![bloodhoundissue](https://user-images.githubusercontent.com/6777371/31513820-17dc2d1e-af55-11e7-8d93-9f586b92e483.PNG)

Its a bit of a concern that bloodhound would be storing/looking for data in system32. If you have any recommendations let me know.

**Comment by rvazarkar** [comment]
@raul5660 this is just a weird byproduct of the way PowerShell works with directories. For some reason it maintains the current working directory where you start PowerShell, and not the directory you CD into. I'll see if I can come up with a fix. The file being written is the cache file for BloodHound, nothing dangerous.

**Comment by raul5660** [comment]
@rvazarkar alright well if there's anything i can do to help let me know.

**Comment by rvazarkar** [comment]
Should be fixed in https://github.com/BloodHoundAD/BloodHound/commit/fb1afd0fef07762a255707448f0152b1faa0c1cb
