### ISSUE TITLE
Fail to import ACLs CSV if the first chunk of the file only contains "COMPUTERS" ACLs

### ISSUE THREAD

**Issue by ClementNotin** [BloodHoundAD/BloodHound#116]
On a large domain, a CSV file for ACLs contains many ACLs targeting "COMPUTERS".
If all these are at the beginning of the file, the first chunk that is read by Papa Parse will only contain ACLs for computers. The import then fails and the following chunks, which contain ACLs for other kinds of objects, are ignored.

I have tried to fix it in the code without success.
In the DevTools console, I observe a DOMException in paparse.min.js:
> Failed to execute 'readAsText' on 'FileReader': The object is already busy reading Blobs.

In the stacktrace, I see that the caller is `parser.resume()`.
My understand of the [relevant code](https://github.com/BloodHoundAD/BloodHound/blob/master/src/components/Menu/MenuContainer.jsx#L224) is that `buildACLProps` returns no data, therefore `premises` is empty, so `parser.resume` is called very quickly (contrary to other cases where the Bolt transactions create a latency, before calling `resume`).

I didn't see anything relevant to this in the Papa Parse documentation. I also tried to use a newer version of this library: the problem remained.
The only workaround I have found is to create a 10s delay with setTimeout before calling `parser.resume()`. It works but I hope there is a better solution...

**Comment by ClementNotin** [comment]
Is it maybe because it is resumed before the following workaround has a chance to trigger (since it is delayed by 1sec)?
https://github.com/BloodHoundAD/BloodHound/blob/master/src/components/Menu/MenuContainer.jsx#L130
```javascript
//I have no idea why this workaround is needed. Apparently all my sessions freeze unless I make a random query
setTimeout(function(){
    var sess = driver.session()
    sess.run('MATCH (n) RETURN (n) LIMIT 1')
        .then(function(){
            sess.close()
        })
}, 1000)
```

**Comment by rvazarkar** [comment]
I'm going to rewrite the entire CSV ingestion logic to fix other issues and hopefully squeeze some more speed out of it. I'll keep this in mind if I can figure out whats causing it

**Comment by ClementNotin** [comment]
Awesome, thanks for the update!

**Comment by rvazarkar** [comment]
I think the updated code in the UI-Update branch should handle this a lot more gracefully. I'll be merging it into master after some more updates are made.

**Comment by rvazarkar** [comment]
This should be fixed, feel free to open it up again if its not though!

**Comment by ClementNotin** [comment]
Confirmed, thanks!
