### ISSUE TITLE
ACLs

### ISSUE THREAD

**Issue by gsamuelhays** [BloodHoundAD/BloodHound#117]
I have a domain with a large ACLs csv (about 70 MB). I noticed that the 'Transitive Object Control' seems to never finish loading (the three loading bubbles). 

Is this a known issue or is there a fast set of debug flags to monitor this specific progress?

**Comment by rvazarkar** [comment]
So first of all, those queries take forever just by the nature of how much data they query. Second, it's likely you're also running into a bug with neo4j 3.2+, which is fixed in an upcoming branch. Try downgrading Neo4j to 3.1 and running it there

**Comment by rvazarkar** [comment]
Try the 1.4 release of BloodHound, this should be fixed
