### ISSUE TITLE
TODO: Additional Ingestor (.vbs, .bat, ...)

### ISSUE THREAD

**Issue by vdun** [BloodHoundAD/BloodHound#119]
Many non powered Powershell machines (XP) are still available in real life.
Many info could be gathered without powershell (e.g. wmi, net, ...)

**Comment by rvazarkar** [comment]
The new ingestor is in c# and compiles to a .exe that targets .NET 3.5. You can find it here:

https://github.com/BloodHoundAD/SharpHound

There's no plans to add any other methods of ingestion. The amount of work necessary is just far more than time is available. I welcome you to write one yourself if you have the time :)
