### ISSUE TITLE
Export-BloodHoundData - UploadString error

### ISSUE THREAD

**Issue by lordofthefries** [BloodHoundAD/BloodHound#12]
I'm getting the following intermittent error.  The Neo4j server is running on a different host, but up and responding as expected (with no issues reported).

Exception calling "UploadString" with "2" argument(s): "The remote server returned an error: (500) Internal Server
Error."
At C:\path\to\BloodHound-master\PowerShell\BloodHound.ps1:14103 char:17
-                 $Null = $WebClient.UploadString($URI.AbsoluteUri + "db/data/batc ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : WebException

**Comment by rvazarkar** [comment]
How are you running the ingestor? Just to get some more information

**Comment by lordofthefries** [comment]
Get-BloodHoundData -CollectionMethod Stealth -verbose | Export-BloodHoundData -URI "http://remote.server:7474/" -UserPass "user:pass" -verbose

**Comment by HarmJ0y** [comment]
Neo4j only allows ingestion from the local host by default, as it can be a security issue if you open up the interface without locking it down with something like iptables/another firewall to control what hosts can access it. You can open up the ingestor interface to allow connections from other hosts as described in https://neo4j.com/docs/operations-manual/current/security/

Try changing the hosting bind address in your [neo4j.conf](https://neo4j.com/docs/operations-manual/current/deployment/#file-locations) file and see if that resolves the issue.

**Comment by lordofthefries** [comment]
I've taken that step. I put the neo4j database on a box that's got a lot of resources and uncommented the line for the listener. I've got some data that went in there (users, some computer objects, and some group objects). That said, the number of computer objects that went in there is way short of the number of computer objects total. Same holds true for groups.

**Comment by rvazarkar** [comment]
We're investigating this. It looks like this has to do with groups/users with special characters in the name and escaping properly.

**Comment by rvazarkar** [comment]
Closing this since there's been no updates on it. Hopefully the issue is fixed now
