### ISSUE TITLE
Group CollectionMethod doesn't retrieve group membership using primarygroupid attribute if user isn't member of other groups

### ISSUE THREAD

**Issue by GregLucand** [BloodHoundAD/BloodHound#120]
Hi,

There is an issue with this filter.
https://github.com/BloodHoundAD/BloodHound/blob/ebd379b71581f75fe27a32ce339074919ae23018/PowerShell/BloodHound.ps1#L5055

If user isn't a member of other groups than its primarygroupid, he won't be retrieve by this filter.

![image](https://user-images.githubusercontent.com/28956517/29962923-34c5e232-8f05-11e7-80e0-9d37b5f7db61.png)

In this example user-admin primarygroupid is 512 and he isn't member of other groups.
Same for intruder account but hidden with List Object Mode.

![image](https://user-images.githubusercontent.com/28956517/29962863-fe791e7e-8f04-11e7-88d9-f18634b72d22.png)

Regards,
Greg

**Comment by rvazarkar** [comment]
This is already fixed in the updated ingestor which should be released soon-ish

**Comment by rvazarkar** [comment]
Fixed in https://github.com/BloodHoundAD/SharpHound/releases
