### ISSUE TITLE
1-way trust:  Groups/Users from "Account" domain, not seen in "Resource" Domain

### ISSUE THREAD

**Issue by jlawhon** [BloodHoundAD/BloodHound#126]
Perhaps I'm missing something.  Is there a way to see accounts/groups/machines from the perspective of a resource domain, where users/groups from a trusted accounts domain might have rights?   (One-way trust)   For example, the paths to domain admin in the resource domain, from the accounts domain.

(Domain Local Administrator Group for the Resource domain)
![resource-domain_local_administrators](https://user-images.githubusercontent.com/892785/30780135-acf2ceb6-a0c9-11e7-9079-e6fdb1583b7c.png)

The icons depicted with the upward pointing red arrow are references to groups/users in the trusted Accounts domain.   When expanding this group in BloodHound, the groups/users from the accounts domain are not shown.

**Comment by rvazarkar** [comment]
I'm not entirely sure how to replicate this, so its hard to kind of debug this. I'll look into it and see if I can duplicate the setup you have there. As a stopgap, have you tried enumerating the resource domain using the -Domain flag?

**Comment by rvazarkar** [comment]
I think I identified the issue here (months later). It's fixed in the SharpHound repo, and will be pushed to master in BloodHound soon
