### ISSUE TITLE
Bloodhound Lockup

### ISSUE THREAD

**Issue by pand0rausa** [BloodHoundAD/BloodHound#128]
I have an account that has "First Degree Local Admin" on 3983 machines but bloodhound interface locks up when expanding the list. 

... animation continues just fine.
Bloodhound wireframe animation hangs. 
Unable to interact with the interface at all. Cannot click on anything nor move any of the objects.

Any suggestions on how to fix?

**Comment by rvazarkar** [comment]
Press ctrl + r or restart the interface. Loading queries that large isn't really something that we can fix, its just a limitation of the libraries we use for drawing things. Until we find a true webgl enabled library we can use, this isn't something we can fix.

**Comment by pand0rausa** [comment]
Dang. Thanks for the prompt response!
