### ISSUE TITLE
Feature request: Search for object in view

### ISSUE THREAD

**Issue by pand0rausa** [BloodHoundAD/BloodHound#130]
It would be handy to be able to do a search for a specific object in the current view.

**Comment by andyrobbins** [comment]
When you have the graph drawing area focused, hit spacebar to bring up the spotlight searcher. This will let you see the list of currently drawn nodes, and includes a search bar so you can find a node by name in the currently drawn graph

**Comment by rvazarkar** [comment]
Additionally, clicking on a node in the spotlight will highlight the node and zoom in on it 👍
