### ISSUE TITLE
"Unrecognized csv type" when trying to upload ACL csvs

### ISSUE THREAD

**Issue by passwordleak** [BloodHoundAD/BloodHound#131]
I ran BloodHound using the following command:

Invoke-BloodHound -CSVFolder 'C:\Windows\Temp'

I then downloaded the precompiled Windows BloodHound .exe and uploaded the csv files. It fails on container_gplinks.csv and container_structure.csv, but everything else works. 

I tried both the rolling binary, and 1.3

**Comment by rvazarkar** [comment]
Those files aren't really release ready, the fact that they're writing out is actually unintended at the moment. So no error on your end, the functionality just doesn't exist

**Comment by rvazarkar** [comment]
The new ingestor will not drop these files, so going to close this for now
