### ISSUE TITLE
Can't find path to ADS

### ISSUE THREAD

**Issue by gnomefish** [BloodHoundAD/BloodHound#133]
When i Import the csv's which are all populated with the systems in my network - when I try to find the path between 2 systems (from victim to ADS, or to any other system) - I get "no data returned from query). When I check the DB info there's all my users, computers and groups - but no sessions. Any idea what I'm missing?

**Comment by rvazarkar** [comment]
There might just not be a path

**Comment by gnomefish** [comment]
What would guarantee a path?

**Comment by rvazarkar** [comment]
You would need sessions on systems as well as admin rights allowing you to get to those sessions.

Try pathfinding between other nodes instead of just to the Domain Admins group
