### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by jackassplus** [BloodHoundAD/BloodHound#134]
Invoke-BloodHound -URI http://10.10.25.135:7474/ -UserPass neo4j:BloodHound
Invoke-BloodHound -URI http://10.10.25.135:7474/ -UserPass "neo4j:BloodHound"
Invoke-BloodHound -URI bolt://10.10.25.135:7687/ -UserPass neo4j:BloodHound

all return "unable to connect to the Neo4j REST endpoint"

I can, however connect in a browser on the same PC using the same parameters
both in Neo4j 3.0.4 and 3.2.5 (the only two versions I have atm)

**Comment by rvazarkar** [comment]
The format is just SERVER:PORT for the URI string.

-URI 10.10.25.135:7474

**Comment by rvazarkar** [comment]
I'll be changing this to http://server:port shortly
