### ISSUE TITLE
Unrecognized CSV Type

### ISSUE THREAD

**Issue by maikeloni** [BloodHoundAD/BloodHound#138]
Hi there,

after using SharpHound.ps1 (https://github.com/BloodHoundAD/BloodHound/blob/master/Ingestors/SharpHound.ps1) with the Collection Methods
Group,LocalGroup,Trusts,ACL,GPOLocalGroup,LoggedOn,ObjectProps
I got the following *.csv files:
acls.csv, group_membership.csv, local_admins.csv, computer_props.csv, user_props.csv, sessions.csv

I could successfully upload the first three files to bloodhound, but when trying to upload computer_props.csv, user_props.csv and sessions.csv I get the error message "Unrecognized CSV Type".

**Comment by rvazarkar** [comment]
For now, check to make sure the files have a proper header. I'll add a check to ensure that headers are in files

**Comment by maikeloni** [comment]
Thanks for your quick response! Would you mind to tell me how a proper header would look like for the files?

**Comment by rvazarkar** [comment]
I added a sanity check in the most recent version of SharpHound. Sorry for never responding, missed your response to the issue. This hopefully shouldn't happen again. 

You can find the csv headers here
https://github.com/BloodHoundAD/SharpHound/blob/master/Sharphound2/CsvContainer.cs
