### ISSUE TITLE
Feature request: enumerate sessions on servers if d

### ISSUE THREAD

**Issue by TheFlexican** [BloodHoundAD/BloodHound#139]

**Comment by TheFlexican** [comment]
If the DC denies the smb enumeration, try to do the sesson enumeration on servers found in the ad.
Maybe even based of a list of servers, provided on the command line.

**Comment by rvazarkar** [comment]
I'm not entirely sure what this request means. Can you elaborate?

**Comment by TheFlexican** [comment]
Sorry about that, looks a bit confusing. What i meant, if a target would have implemented session security hardening on their domain controllers, bloodhound can't enumerate user and admin sessions right? But let's say they didn't on their file servers, you would be able to enumerate the sessions on the file server to do some mapping between the users and their workstations/servers.

I guess it would require some knowledge of the server you want to target to do the enumeration, but let's say the server is called fileserver01, pretty good guess you will find some users sessions on it.

Also, if they would be running microsoft ata, you wouldn't trigger an smb enumeration event on the domain controllers right?

So, what would cool to have, is that you can tell sharphound to skip the smb enumeration against the domain controller, and have it scan server xyz instead.

**Comment by rvazarkar** [comment]
The --ExcludeDC flag does exactly this, removes Domain Controllers from session enumeration. 

If you want to target specific servers, you can just use the ComputerList option

**Comment by TheFlexican** [comment]
I feel really stupid now, I looked into this before I posted this comment. Guess I was looking with my eyes closed. Sorry to have bothered you :)

Keep up the good work!

**Comment by rvazarkar** [comment]
No worries
