### ISSUE TITLE
BloodHound can't edit some Custom queries.

### ISSUE THREAD

**Issue by CodingFree** [BloodHoundAD/BloodHound#140]
BloodHound can't edit some Custom queries if the User data path has blank spaces and the host is Windows.

I think it is because of electron. The function app.getPath('userData') can return a path that looks like "C:\Users\My User\" and because of the blank space, it is not possible to edit the Custom Queries.

Maybe it could be useful to scap the following line:
https://github.com/BloodHoundAD/BloodHound/blob/2cac6e32550eb426c4790b82d7f6dd4fa80ee687/src/components/SearchContainer/Tabs/PrebuiltQueriesDisplay.jsx#L35

As an additional information,  the Get_,Path function:
https://github.com/electron/electron/blob/b790ad6c1abdb3baa6b365dd96829046dbb5b39f/atom/browser/api/atom_api_app.cc#L378-L387
Is mapped into getPath through:
https://github.com/electron/electron/blob/b790ad6c1abdb3baa6b365dd96829046dbb5b39f/atom/browser/api/atom_api_app.cc#L378-L387

**Comment by CodingFree** [comment]
Hi, is there any workaround for this, @rvazarkar?

**Comment by rvazarkar** [comment]
Just to make sure, this is just to hit the "edit" button on the custom queries panel right? The custom queries are still being read properly

**Comment by CodingFree** [comment]
Yes, that's right. But did you mean that there is another way to load custom queries?

**Comment by rvazarkar** [comment]
Was fixed in https://github.com/BloodHoundAD/BloodHound/commit/7771af22c597bf31f52f75faf6e415522cfaa9ba
