### ISSUE TITLE
SharpHound CLR Exception

### ISSUE THREAD

**Issue by cottinghamd** [BloodHoundAD/BloodHound#142]
During scanning this week I encountered a SharpHound crash. It was running from a Windows 2008 R2 server. This caused SharpHound to terminate.

This behavior was able to be recreated by scanning one particular domain, possibly a result in the domain is causing the crash? 

ExceptionAddress: 00007ffeb30795fc (KERNELBASE!RaiseException+0x0000000000000068)
ExceptionCode: e0434f4d (CLR exception)
ExceptionFlags: 00000001
NumberParameters: 1
Parameter[0]: ffffffff80131500

Crashdump file has been provided to @rvazarkar in Slack (no idea if the dump contains sensitive content or not). Please let me know if you want any further information.

**Comment by rvazarkar** [comment]
I *think* this is fixed. I guess we'll find out if it comes back up again
