### ISSUE TITLE
electron-packager is not recognized as a cmdlet name (Windows)

### ISSUE THREAD

**Issue by CodingFree** [BloodHoundAD/BloodHound#143]
BloodHound is using the electron-packager:
https://github.com/BloodHoundAD/BloodHound/blob/master/package.json#L25

However it is not set as a dependency:
https://github.com/BloodHoundAD/BloodHound/blob/master/package.json#L36

As a workaround, it can be installed using:
npm install electron-packager

**Comment by rvazarkar** [comment]
https://github.com/BloodHoundAD/BloodHound/wiki/Building-BloodHound-from-source

This is already documented in the wiki
