### ISSUE TITLE
Unable to run PS (SharpHound.ps1) file on Windows 10 OS

### ISSUE THREAD

**Issue by infolookup** [BloodHoundAD/BloodHound#144]
When attempting to run the file on Windows 10 I am getting the following error

Steps taken:
Powershell -exec bypass
Import-module sharphound.ps1
At C:\temp\BloodHound\SharpHound.ps1:127 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At C:\temp\BloodHound\SharpHound.ps1:131 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At C:\temp\BloodHound\SharpHound.ps1:136 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At C:\temp\BloodHound\SharpHound.ps1:141 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At C:\temp\BloodHound\SharpHound.ps1:145 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At C:\temp\BloodHound\SharpHound.ps1:2408 char:227
+ ... g:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in
double quotation marks ("&") to pass it as part of a string.
At C:\temp\BloodHound\SharpHound.ps1:2411 char:10
+ </form>  </div>
+          ~
The '<' operator is reserved for future use.
At C:\temp\BloodHound\SharpHound.ps1:2426 char:24
+       <li class="mr-3">&copy; 2017 <span title="0.19245s from unicorn ...
+                        ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in
double quotation marks ("&") to pass it as part of a string.
At C:\temp\BloodHound\SharpHound.ps1:2426 char:36
+       <li class="mr-3">&copy; 2017 <span title="0.19245s from unicorn ...
+                                    ~
The '<' operator is reserved for future use.
At C:\temp\BloodHound\SharpHound.ps1:2426 char:42
+ ...  2017 <span title="0.19245s from unicorn-818317362-rbqpc">GitHub</spa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'title="0.19245s from unicorn-818317362-rbqpc">GitHub</span>' in expression or statement.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : RedirectionNotSupported

PS C:\temp>

**Comment by rvazarkar** [comment]
You downloaded the web page, not the script. Download the raw version.

**Comment by rvazarkar** [comment]
https://raw.githubusercontent.com/BloodHoundAD/BloodHound/master/Ingestors/SharpHound.ps1

**Comment by infolookup** [comment]
Dope!, my mistake. Thank you!
