### ISSUE TITLE
Which tool to display JSON exports from BloodHound ?

### ISSUE THREAD

**Issue by maaaaz** [BloodHoundAD/BloodHound#145]
Hello there,

Do you know any tool/script being able to process a `json` export from BloodHound in order to display graphs ? I'm thinking about something like D3JS.

I know that there is a closed-source code part in BloodHound and you cannot really provide such format but I really think that in a near future, a good HTML export with graphs will be necessary to auditors/pentesters (because asked by customers :)).

Anyway, thank you for that great tool.

Cheers !

**Comment by rvazarkar** [comment]
You can always just export a single graph as an image

**Comment by maaaaz** [comment]
Yes but having the ability to wander in the graph and not only have a static image would be awesome.

**Comment by rvazarkar** [comment]
We could potentially enable the Gephi output, which is a third party graphing tool. The JSON was generally intended to allow you to parse data out, not export it for display, although BloodHound does support loading JSON back in to display a graph
