### ISSUE TITLE
Strategy for query internationalization

### ISSUE THREAD

**Issue by maaaaz** [BloodHoundAD/BloodHound#146]
Hello there,

What is the plan for BloodHound to include builtin queries for **foreign Active Directories, as group names differ** (e.g in France, `domain admins` is `admins du domaine`)

The current release allows to add some custom queries in the `PrebuiltQueries.json` file: so in the end some people will provide that file with internationalized queries relative to their language.

It could be nice to have a menu `AD language setup` in BloodHound with defined queries, don't you think ?

Cheers !

**Comment by rvazarkar** [comment]
So in the near future, we'll probably be migrating a lot of the built in queries to SIDs instead of names, which should solve the issue. The domain admins sid is consistent across internationalization as far as I know.

**Comment by maaaaz** [comment]
Okay that's a good idea ! 
I guess SIDs are also consistent for other privileged groups (backup operator etc.).

**Comment by rvazarkar** [comment]
BloodHound 2.0 now uses SIDs instead of names for domain admin groups
