### ISSUE TITLE
Bloodhound confusion between local and domain accounts

### ISSUE THREAD

**Issue by variableresults** [BloodHoundAD/BloodHound#147]
Not sure if this has been reported or not, but I found an issue today where ingested data from Sharphound confused session logins performed by local accounts with a similarly named domain account. 

Example: local account named "Localaccount" that has a corresponding domain account named "Localaccount" will show up as the domain account when viewing sessions in Bloodhound. You will see "Localaccount@domain" even though the sessions being reported are all local (verified by looking at the security audit logs--Account Domain field is local, not domain).

**Comment by rvazarkar** [comment]
There's no way to solve this unfortunately. The NetSessionEnum API only
gives us a username. We deconflict as best as possible but if there's a
local and a domain user we can't differentiate them
