### ISSUE TITLE
'Export-BloodHoundData' is not recognized

### ISSUE THREAD

**Issue by davidmthomsen** [BloodHoundAD/BloodHound#152]
I keep getting the below error when trying to use the `Export-BloodHoundData` command in Powershell.

> PS C:\BloodHound-master\Ingestors> Get-BloodHoundData | Export-BloodHoundData -URI http://localhost:7474/
Export-BloodHoundData : The term 'Export-BloodHoundData' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:22
> + Get-BloodHoundData | Export-BloodHoundData -URI http://localhost:7474 ...
> +
>                 ~~~~~~~~~~~~~~~~~~~~~
> + CategoryInfo          : ObjectNotFound: (Export-BloodHoundData:String) [], 
> CommandNotFoundException
> + FullyQualifiedErrorId : CommandNotFoundException

**Comment by rvazarkar** [comment]
Export-BloodHoundData hasn't been used for quite a while. You can find the new commands here

https://blog.cptjesus.com/posts/newbloodhoundingestor
