### ISSUE TITLE
Exception calling "FindAll" with "0" argument(s): "The server is not operational.

### ISSUE THREAD

**Issue by davidmthomsen** [BloodHoundAD/BloodHound#153]
I get the below error when executing `Get-BloodHoundData -URI http://localhost:7474/` command

`Sending output to neo4j RESTful API interface at: http://localhost:7474/`
`Exception calling "FindAll" with "0" argument(s): "The server is not operational."`
`At C:\BloodHound-master\Ingestors\BloodHound_Old.ps1:4635 char:22`
`+     ForEach($User in $UserSearcher.FindAll()) {`
`+                      ~~~~~~~~~~~~~~~~~~~~~~~`
`+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException`
`+ FullyQualifiedErrorId : COMException`

**Comment by rvazarkar** [comment]
Why are you using the old bloodhound ingestor instead of the new C# version?

**Comment by davidmthomsen** [comment]
How? I read this article [https://blog.cptjesus.com/posts/newbloodhoundingestor](url) but still unsure which command I should run.

**Comment by rvazarkar** [comment]
You should be using SharpHound.exe or SharpHound.ps1 from here:

https://github.com/BloodHoundAD/BloodHound/tree/master/Ingestors
