### ISSUE TITLE
Database Not Found

### ISSUE THREAD

**Issue by ch40sth30ry** [BloodHoundAD/BloodHound#154]
Hello - 

Trying to install Bloodhound on a Windows box. Moved the sample database into the neo4j\data\databases directory and pointed neo4j.conf to the database. (I've tried neo4j 3.2.9 and 3.3.2)
I start neo4j via the neo4j.bat file, and it appears to start fine after upgrading the database. I then launch bloodhound.exe and point it to bolt://127.0.0.1:7687 and as soon as I tab down to enter a username, I'm told the database isn't found as shown in the image attached to this post. What am I doing wrong?

Thanks in advance, 
Paul

![image](https://user-images.githubusercontent.com/20890996/35250225-b89ed994-ff92-11e7-9f38-560631f2e6c1.png)

**Comment by rvazarkar** [comment]
Just fixed this in https://github.com/BloodHoundAD/BloodHound/commit/896f7b207b0b50536ccab5c0cf351d40842ba741

You can compile yourself or grab the rolling release when it compiles
