### ISSUE TITLE
"DS-Replication-Get-Changes" extended right is shown as an "All Extended Rights" path. 

### ISSUE THREAD

**Issue by bravo2day** [BloodHoundAD/BloodHound#158]
Alrighty – I found a few ACL paths who doesn’t seem to be right. 

From the csv file:
USER1@EXAMPLE.LOCAL,user,GROUP1@EXAMPLE.LOCAL,group,ExtendedRight,User-Force-Change-Password,AccessAllowed,True

Now this plots up like this in Bloodhound (GROUP1 has “Force Change Password” on USER1)

 https://i.imgur.com/uzuc645.png

However, in AD this is the actual permissions – Bloodhound does not seem to take into consideration the “Applies to” setting. (Which in this case is set to "Descendant Computer objects")

 https://i.imgur.com/TBdwfRp.png

Is this a bug or am I missing something?

**Comment by rvazarkar** [comment]
It's a bug I thought I fixed. I'll take another look

**Comment by bravo2day** [comment]
Sorry, but I'we used an older Sharphound.exe by accident, so this might be fixxed by https://github.com/BloodHoundAD/SharpHound/commit/8c0d6c1cfaf84ed0eb058c500ee072971a1bb52b . Will run the latest Sharphound.exe and post results to confirm

**Comment by bravo2day** [comment]
Okay,  so i ran the latest injestor
 (https://github.com/BloodHoundAD/BloodHound/blob/master/Ingestors/SharpHound.exe). Old acls.csv=900MB, new acls.csv: 550 MB (! :p)
The previous (false) ACL paths are gone, however I *think* i found a (different) ACL false relationship:

https://i.imgur.com/X1YKd2b.png

GROUP1 claims to have "All Extended Rights" relationshop to USER1.

CSV file: 
USER1@EXAMPLE.LOCAL,user,GROUP1@EXAMPLE.LOCAL,group,ExtendedRight,All,AccessAllowed,True

Permissions in AD: "Effective permission for this group on this user" - No "All extended Rights".

https://i.imgur.com/F3AbAsW.png

Permissions in AD: The actual permission is "DS-Replication-Get-Changes", which is an extended right, but not "All extended Rights".

https://i.imgur.com/CNiyC9L.png

So unless DS-Replication-Get-Changes is special somehow i think this is a bug.

**Comment by rvazarkar** [comment]
Should hopefully be fixed in https://github.com/BloodHoundAD/SharpHound/commit/1d26122de4568d483498e476e6fb3eb51b36f710

**Comment by rvazarkar** [comment]
Feel free to re-open if the issue pops up again
