### ISSUE TITLE
default password and username not working 

### ISSUE THREAD

**Issue by 007scorpio** [BloodHoundAD/BloodHound#159]

**Comment by rvazarkar** [comment]
Uhhh, could we get a bit more info?

**Comment by 007scorpio** [comment]
No Error message actually... if i put the password "BloodHound" it tells me "invalid username or password" and if i put neo4j and neo4j as the username and password, nothing happens and the login becomes grayed out. 

thanks

**Comment by rvazarkar** [comment]
Go to localhost:7474 and try logging in there. See if the password needs to be changed. Are you using the example graph database? Or a new folder?

**Comment by 007scorpio** [comment]
ya that works

**Comment by 007scorpio** [comment]
but accept neo4j as the password and not BloodHound


thanks

**Comment by 007scorpio** [comment]
ok Everything is working now... Thanks

**Comment by Hamza199888** [comment]
anyone know hows to find a vulnerable path and if you know somehow that user didnt change his default password and has never logon but default pass is not working or i might be targetting the wrong group, can you guys explain?
