### ISSUE TITLE
Feature Request: Variable Filenames/ Encrypted Contents

### ISSUE THREAD

**Issue by johnnyxmas** [BloodHoundAD/BloodHound#161]
Generating static / known filenames is making it easy for endpoint protection mechanisms to alert on the files being written to disk. Randomly-generated filenames + encrypted contents using a key that can be provided as an argument may be a good solution.

**Comment by rvazarkar** [comment]
Both of these are implemented in 2.0

--RandomFileNames
--EncryptZip
