### ISSUE TITLE
Login Failed "Invalid Username and Password" Workaround

### ISSUE THREAD

**Issue by pe3zx** [BloodHoundAD/BloodHound#162]
I've encountered "Invalid Username and Password" when trying to login with default credential `neo4j` and `BloodHound`. This problem can be solved by replacing `dbms/auth` which available on `neo4j/data/dbms` with `data/dbms/auth` on `BloodHoundExampleDB.graphdb` and then restart neo4j service.

This step may need to be mentioned on [Getting started](https://github.com/BloodHoundAD/BloodHound/wiki/Getting-started#windows). 

The guideline also need to correct on `dbms.active_database=BloodHoundDB.graphdb` because example DB is `BloodHoundExampleDB.graphdb` to prevent wrong DB access.

**Comment by rvazarkar** [comment]
I corrected the db name in the getting started page. However the default username and password for neo4j is neo4j:neo4j. The BloodHound password is only valid for the example database.

**Comment by Dnozz** [comment]
default passwords don't work..  pulling my hair out just trying to login..   crazy!!
