### ISSUE TITLE
Sample data for testing purpose

### ISSUE THREAD

**Issue by CaledoniaProject** [BloodHoundAD/BloodHound#167]
Hi there,

I don't have a big environment to test BloudHound and wondering if you guys can provide some sample data to use?

Perhaps some CSV files that can be imported directly to Neo4J

**Comment by rvazarkar** [comment]
Theres a sample database included with the project.

https://github.com/BloodHoundAD/BloodHound/tree/master/BloodHoundExampleDB.graphdb

**Comment by CaledoniaProject** [comment]
Looks good

**Comment by ivan-cpu68** [comment]
Hello! How can I use https://github.com/BloodHoundAD/BloodHound/tree/master/BloodHoundExampleDB.graphdb

**Comment by peterp007** [comment]
Guys, it's probably me, but I can't find the sample data file anywhere. Is it really gone?
