### ISSUE TITLE
Sharphound Unhandled Exception: System.DirectoryServices.

### ISSUE THREAD

**Issue by jackpit110** [BloodHoundAD/BloodHound#169]
I got below error Whats happened?
 

> Initializing BloodHound at 23:38 on 07.04.2018
> Starting Default enumeration for Examlpe.com
> 
> Unhandled Exception: System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException: Unknown error (0x80005000) ---> System.Runtime.InteropServices.COMException (0x80005000): Unknown error (0x80005000)
>    at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
>    at System.DirectoryServices.DirectoryEntry.Bind()
>    at System.DirectoryServices.DirectoryEntry.get_AdsObject()
>    at System.DirectoryServices.PropertyValueCollection.PopulateList()
>    at System.DirectoryServices.PropertyValueCollection..ctor(DirectoryEntry entry, String propertyName)
>    at System.DirectoryServices.PropertyCollection.get_Item(String propertyName)
>    at System.DirectoryServices.ActiveDirectory.PropertyManager.GetPropertyValue(DirectoryContext context, DirectoryEntry directoryEntry, String propertyName)
>    --- End of inner exception stack trace ---
>    at System.DirectoryServices.ActiveDirectory.PropertyManager.GetPropertyValue(DirectoryContext context, DirectoryEntry directoryEntry, String propertyName)
>    at System.DirectoryServices.ActiveDirectory.DirectoryEntryManager.ExpandWellKnownDN(DirectoryContext context, WellKnownDN dn)
>    at System.DirectoryServices.ActiveDirectory.Utils.GetReplicaList(DirectoryContext context, String partitionName, String siteName, Boolean isDefaultNC, Boolean isADAM, Boolean isGC)
>    at System.DirectoryServices.ActiveDirectory.DomainController.FindAllInternal(DirectoryContext context, String domainName, Boolean isDnsDomainName, String siteName)
>    at System.DirectoryServices.ActiveDirectory.Domain.get_DomainControllers()
>    at Sharphound2.Enumeration.GroupHelpers.<GetEnterpriseDCs>d__5.MoveNext()
>    at Sharphound2.Enumeration.EnumerationRunner.StartEnumeration()
>    at Sharphound2.Sharphound.Main(String[] args)
>

**Comment by rvazarkar** [comment]
Fixed in https://github.com/BloodHoundAD/BloodHound/commit/31a3c1fe31166b461b731df442e393597abf336f
