### ISSUE TITLE
Missing neo4j password reset step on setup instructions

### ISSUE THREAD

**Issue by NetworkLlama** [BloodHoundAD/BloodHound#171]
When performing a clean installation of BloodHound on Windows 7 or 10, the neo4j password must be reset before one can log in to BloodHound.

Components used:
 - Java 8b161
 - Neo4j Community Server 3.3.5
 - BloodHound 1.5.2
 - Instructions at https://github.com/BloodHoundAD/BloodHound/wiki/Getting-started

Steps to recreate:
1. Perform setup steps through Step 12 (logging in to BloodHound.exe using neo4j/BloodHound)
2. Receive authentication failure

Fix:
1. Perform setup steps through Step 10 (navigating to http://localhost:7474 to validate that Neo4J has started).
2. Before loading BloodHound (currently Step 11), log in to Neo4J with neo4j/neo4j. Database will respond with prompt to change password. Set to neo4j/BloodHound.
3. Proceed with Step 11 (launch BloodHound.exe) and Step 12 (log in with neo4j/BloodHound).

This should probably go in the wiki.

**Comment by TomHubGit** [comment]
Thanks for the hint! It seems like I have a similar issue:
[Importing BloodHoundExampleDB.graphdb is not working #229
](https://github.com/BloodHoundAD/BloodHound/issues/229)

Do you have an idea how to fix this, when you set the initial password different then BloodHound?

**Comment by rvazarkar** [comment]
We've completely redone our documentation so closing this

**Comment by ivan-cpu68** [comment]
Please!!!! Where can I see BloodHoundExampleDB.db documentation?

**Comment by noraj** [comment]
> Please!!!! Where can I see BloodHoundExampleDB.db documentation?

@ivan-cpu68 It was removed in 4.1.0 https://github.com/BloodHoundAD/BloodHound/compare/4.0.3...4.1.0
