### ISSUE TITLE
Sizing Question

### ISSUE THREAD

**Issue by cmatthewbrooks** [BloodHoundAD/BloodHound#175]
What are the largest CSV files that have been tested for successful upload? 

- My small - medium files (local_admins at 343KB, sessions.csv at 595KB, user_props.csv at 40MB) load with ease.
- My medium - large files (computer_props.csv at 46MB, group_membership.csv at 345MB and acls.csv at 445MB) cause the interface to blank out and seemingly hang. 

Have files this size been tested and if so, has this "blank hang" been observed? What was the load time? The longest I've allowed the hang has been about 2 hours with no resolution before just exiting the program.

I'm on Windows 10 x64 with 16GB RAM and a i5-4690 CPU at 3.50GHz.

**Comment by rvazarkar** [comment]
As far as I know, file size shouldn't affect uploads. We chunk files and upload them in pieces. Open up the console in the BloodHound interface and see if theres any errors in the console when it blanks out

**Comment by rvazarkar** [comment]
Press ctrl + shift + i to open the console

**Comment by cmatthewbrooks** [comment]
After watching the console, there are errors thrown while trying to load computer_props.csv and group_membership.csv. Acls.csv did actually load so I made the false assumption on size when I reported - my fault.

computer_props.csv loads to ~35% then throws:

![image](https://user-images.githubusercontent.com/3974104/39738266-ba80f918-52bc-11e8-8975-e86296e657ca.png)

group_membership.csv loads to ~5% then throws a similar error:

![image](https://user-images.githubusercontent.com/3974104/39738276-cd12b3e6-52bc-11e8-9157-89230246d178.png)

**Comment by jbfuzier** [comment]
There is likely a line not properly formated in your input file. I had the issue.

You can run this on your file to get the line with an issue : 

`with open("acls.csv") as f:
    for l in f:
        l=l.strip()
        if len(l.split(","))!=8:
            print l
`

Change the filename accordingly and the expected number of column (3 for group_membership, 8 for computer_props).

**Comment by rvazarkar** [comment]
@cmatthewbrooks can you give me an example of the bad OS field?

**Comment by cmatthewbrooks** [comment]
I'll try to re-run next week and post back here.

**Comment by cmatthewbrooks** [comment]
These are the distinct bad OS fields I observed:

"Data Domain OS Samba Version 3.0.35, Likewise Version 5.2.0-48874p"
"Hyper-V Server Service Pack 1, v.178"
"Windows 2000 Professional Service Pack 2, RC 2.124"
"Windows Server┬« 2008 Standard Service Pack 1, v.222"
"Windows VistaΓäó Enterprise Service Pack 0, v."
"Windows VistaΓäó Enterprise Service Pack 1, v.275"
"Windows VistaΓäó Enterprise Service Pack 1, v.668"
"Windows VistaΓäó Enterprise Service Pack 2, v.105"
"Windows VistaΓäó Enterprise Service Pack 2, v.286"
"Windows VistaΓäó Ultimate Service Pack 1, v.668"
"Windows XP Professional Service Pack 2, v.2055"
"Windows XP Professional Service Pack 2, v.2126"
"Windows XP Professional Service Pack 2, v.2138"
"Windows XP Professional Service Pack 2, v.2149"
"Windows┬« Server Code Name ""Longhorn"" Standard Service Pack 0, v."
"Windows┬« Server Code Name ""Longhorn"" Standard Service Pack 1, v.126"
Windows Server┬« 2008 Enterprise Service Pack 2

I'll close this out now...
