### ISSUE TITLE
Ingestors don't work via runas from non-domain system, or domain system in different forest

### ISSUE THREAD

**Issue by johnmccash** [BloodHoundAD/BloodHound#179]
I've just attempted to run the Bloodhound ingestors from a runas /netonly command shell, on a domain host in a different forest from the target. This fails similarly for both C# and Powershell, whether I specify a target domain/DC or not.

Here's the error I get:

PS C:\users\<username redacted>\desktop\ingestors> Invoke-Bloodhound -collectionmethod all
Initializing BloodHound at 7:38 AM on 5/22/2018
Unable to contact domain. Try from a domain context!
PS C:\users\<username redacted>\desktop\ingestors> Invoke-Bloodhound -collectionmethod all -domain <domain redacted>
Initializing BloodHound at 7:39 AM on 5/22/2018
LDAP connection test failed, probably can't contact domain
PS C:\users\<username redacted>\desktop\ingestors> Invoke-Bloodhound -collectionmethod all -domain <domain redacted> -domaincontroller <DC name redacted>
Initializing BloodHound at 7:53 AM on 5/22/2018
LDAP connection test failed, probably can't contact domain
PS C:\users\<username redacted>\desktop\ingestors> Invoke-Bloodhound -collectionmethod all -domaincontroller <DC name redacted>
Initializing BloodHound at 7:54 AM on 5/22/2018
Unable to contact domain. Try from a domain context!

Based on the feedback for issue #113, I was assuming this would work from a non-domain system, and that the problem was just the different forest issue, however I just tried that as well, and it doesn't work from a non domain system either. Same errors.

Thoughts?

**Comment by johnmccash** [comment]
Ahah! Figured it out. You have to specify the domain with the X.com syntax, rather than using just X.

**Comment by kawaxi** [comment]
Im very very sorry to re-open this..... but I'm having the exact same problem .... 

runas /netonly /user:user@domain powershell
powershell -ep BYPASS
Import-Module .\Sharphound.ps1
Invoke-BloodHound -domain evil.com -domaincontroller DC.evil.com

I get: 

`LDAP Connection Test Failed. Check if you're in a domain context!`

So I proceed to supply LDAP credentials 

Invoke-BloodHound -domain evil.com -domaincontroller DC.evil.com --ldapusername 'EVIL\HACKER' --ldappassword "PWNY"

then I get 

`Invoke-BloodHound : Cannot validate argument on parameter 'OutputDirectory'. The " Test-Path -Path $_ " validation script for the argument with value
"EVIL\HACKER" did not return a result of True. Determine why the validation script failed, and then try the command again.
At line:1 char:108
+ ... maincontroller DC.evil.com --ldapusername 'EVIL\HACKER' --ldapp ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-BloodHound], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-BloodHound`

please help.

**Comment by rvazarkar** [comment]
You're using the wrong argument style for PowerShell. Its -LdapUsername and -LdapPassword.

Also, set your dns on your box to point to the domain controller

**Comment by kawaxi** [comment]
Thanks for your prompt reply @rvazarkar .

I have proceeded to use -LdapUsername and -LdapPassword as suggested , plus I edited the host file.

it finally worked, thanks for the help.

**Comment by eslimasec** [comment]
had a different root cause for the ldap error in my case. Sharing in case it helps others. if your computer (lab computer in my case) has the network adapter with "public" profile set, the local firewall will be causing the ldap error. make sure you network profile is set to "private" prior to launching sharphound ingestor. cheers

**Comment by GeneralXpress** [comment]
I used the command Invoke-BloodHound -CollectionMethod All -Domain domain.local -ZipFilename file.zip

and i get the error "LDAP Connection Test Failed. Check if you're in a domain context!"
