### ISSUE TITLE
Additional query request

### ISSUE THREAD

**Issue by jackassplus** [BloodHoundAD/BloodHound#181]
Another useful query would be to find all local admins (logged in or not) who are NOT members of the Domain/Enterprise Admins group.

**Comment by andyrobbins** [comment]
Should be an easy enough query to write. My question would be what sort of output you're looking for. Are you looking for a visualization, a list (csv)? Can you tell me a little more about what kind of insight you're looking to gain with the query?

**Comment by jackassplus** [comment]
It's just to declutter the output. It's a given that the DA/EA group members have admin access in 99% of cases. For those cases, It would be nice to see the graph without default groups.

**Comment by RamblingCookieMonster** [comment]
You can likely take one of the pre-canned queries (e.g. top 10 users with most local admin rights) and add `WHERE` clauses to exclude anyone with memberships in admin groups (either built in ones like `Domain Admins`, or your own groups that happen to provide admin on certain tiers.

e.g.

```
WHERE NOT (u)-[:MemberOf*]->(:Group {ADSamAccountName:'Domain Admins'}) AND
    NOT (u)-[:MemberOf*]->(:Group {ADSamAccountName:'Tier 1 Admins'}) AND
    NOT (u)-[:MemberOf*]->(:Group {ADSamAccountName:'Tier 2 Admins'})
```

There might be a cleaner way to do that, and my (neo4j) schema is a bit different, but hopefully that points you in the right direction

Cheers!

**Comment by jackassplus** [comment]
Thanks, I'll use that at a starting point (still learning cypher)

**Comment by rvazarkar** [comment]
Closing this for now, hopefully 2.0 will give you the tools needed to implement this
