### ISSUE TITLE
Using a remote neo4j ubuntu box

### ISSUE THREAD

**Issue by liamcs98** [BloodHoundAD/BloodHound#182]
Hi All,

I was wondering if anyone had successfully run bloodhound locally, and the neo4j on another server.

I have several people that want to tap into the same data so I was thinking it would be great to have just the client on each machine but host the neo4j database on a different box.

I thought it would be as simple as running it and changing the IP to the remote database, however I can't seem to access the neo4j interface (port 7474). 

Best,

**Comment by andyrobbins** [comment]
Hi William,

Thanks for opening the issue and for the great question. You can definitely host neo4j and make it available to remote systems. There is a certain line you need to change in the neo4j.conf file, which is located in $Neo4jhome$/conf/neo4j.conf, where $Neo4jhome$ is the folder you have neo4j installed. 

Open that file and head to the section with this header:

`#*****************************************************************
# Network connector configuration
#*****************************************************************`

The first configuration should be for configuring the default listener address, and that line is commented (disabled) by default:

`#dbms.connectors.default_listen_address=0.0.0.0`

You can very simply delete the `#` at the beginning of that line to uncomment the line and bind neo4j to 0.0.0.0, which will allow neo4j to accept connections from remote systems:

`dbms.connectors.default_listen_address=0.0.0.0`

After you make that change, save the file, stop neo4j, start neo4j up again, and you should be able to connect to neo4j from other systems, assuming they have logical access to the system on ports 7474 and/or 7687.

**Comment by liamcs98** [comment]
Hi Andy!
Yep I was just not looking well enough. Works perfectly.
For anyone in the future who wants to do this, here is some down and dirty documentation:

Setting up a Database Server and Local Bloodhound
Bloodhound has two parts. The Bloodhound client, which is a visualizer and suite of AD information gathering tools, and neo4j which is the backend database. 

Neo4j is pretty bad. So best to run it on a external server so that'll work.

Steps for Server
ssh into the server machine. It must be Ubuntu (or a distro that has apt-get, not yum or others).

1. sudo nano /etc/apt/sources.list
2. Add at the bottom:
3. deb http://http.kali.org/kali kali-rolling main contrib non-free
4. sudo apt-get update -y && sudo apt-get dist-upgrade -y
5. sudo apt-get install bloodhound
6. Yes and yes to the prompts
7. sudo ufw allow 22
8. sudo ufw allow 7474
9. sudo ufw allow 7687
10. Edit the neo4j config
11. whereis neo4j 
12. sudo nano /etc/conf/neo4j.conf
13. In the "Network Connector Configuration"
14. Uncomment this line (remove #):
15. #dbms.connectors.default_listen_address=0.0.0.0
16. sudo reboot
17. In a web browser goto <ip>:7474
18. Username: neo4j Password: neo4j
19. Change the password to something good.
20. Steps for Client
21. 

Install the Bloodhound client:

Mac: brew install homebrew/cask/bloodhound
Database URL – bolt://<IP>:7687
Username – neo4j
Password – your newly changed password
Congrats! It is now installed!
