### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by RyanDeleurme** [BloodHoundAD/BloodHound#185]
I am trying to install BloodHound on Kali, and when I try to run ./BloodHound from /BloodHound-linux-x64, I keep receiving this error: 
`./BloodHound: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory`

any suggestions?

**Comment by WJDigby** [comment]
`(sudo) apt-get install libgconf-2-4`

**Comment by rvazarkar** [comment]
Hopefull @WJDigby fixed your issue, if not you can re-open this, although its not particularly a BloodHound issue.
