### ISSUE TITLE
CSV Import issues

### ISSUE THREAD

**Issue by david-bla** [BloodHoundAD/BloodHound#189]
Hey, first I would like to _THANK YOU_ for this work!
I was using my own scripts to resolve these relationships like ad contol paths but this kind of visualisation is just awesome ;)

Some users, including me, were facing those "stuck in uploading csv" issues.
I was uploading csv with about 100.000 lines and discoverd the common "special chars" issue.
Due to this AD was setup in german, with german admins - they used german special chars like Ü,Ö,Ä.
SharpHound will export tham as Ãœ <- and similar, so after chaning the 100.000+ lines cvs was uploaded less than 10 seconds.

Thank you in advance!!

EDIT: I just noticed that also these "default group" are idendnified by name istead of the well known sids.
So for AD in foreign language the "Domain-Admin" group will have a different name and the preinstalled querys will return nothing.. maybe you can fix this be importing the well known sid's or similar 👍 
Or maybe add the option to change default domain admin group name and other important groups

**Comment by david-bla** [comment]
May notice #191

**Comment by rvazarkar** [comment]
We already have a plan in place to convert to using well known SIDs for groups. Unfortunately, its going to require some significant re-structuring of the way we do collection + the UI. Can you give me a few lines from the CSV that have German characters so I can test them? You can strip out group names, I just need some real user names to play with. Likely a fix will cover all of the cases.

**Comment by david-bla** [comment]
Yes I'll do that :+1:  

- German AD default domaincomputer group: _(SID: S-1-5-21&lt;DOMAIN ID&gt;-515)_
`DOMÃ„NENCOMPUTER[...]` = `DOMÄNENCOMPUTER@CONTOSO.LOCAL,MY_PC.CONTOSO.LOCAL,computer`
- German AD default domainuser group:  _(SID: S-1-5-21&lt;DOMAIN ID&gt;-513)_
`DOMÃ„NEN-BENUTZER[...]` = `DOMÄNEN-BENUTZER@CONTOSO.LOCAL,MY_USER.CONTOSO.LOCAL,user`

I think in group terms the Ä (&auml;) should be the thig because domain = domäne (who ever was translating identifiers.... :rage:)

I added a user with the special chars : __Ä (&Auml;) Ü(&Uuml;) Ö(&Ouml;) ß(&szlig;)__
becomes: `DOMÃ„NEN-BENUTZER@OCONTOSO.LOCAL,Ã„ÃœÃ–ÃŸ@CONTOSO.LOCAL,user`

**Comment by rvazarkar** [comment]
I'm going to be updating the code to use UTF-8 as the file encoding, hopefully that should help with this issue.

**Comment by rvazarkar** [comment]
The fixes have been merged into 2.0
