### ISSUE TITLE
Getting User Schema/Properties 

### ISSUE THREAD

**Issue by liamcs98** [BloodHoundAD/BloodHound#192]
Howdy,

I'm trying to build a query that is conditional on the "Last Logon" property. I cant seem to find what it is. ie ".lastlogon" This is not documented on the wiki.

My goal is to get all domain admins that have not logged in before, (assume .lastlogon =~ "-1")

MATCH (n:Group), (m:User) WHERE n.name =~ "(?i).*DOMAIN ADMINS.*" AND m.lastlogon =~ "-1" WITH n MATCH p=(n)<-[r:MemberOf*1..]-(m) RETURN p

**Comment by rvazarkar** [comment]
Its .LastLogon. Case sensitive

**Comment by rvazarkar** [comment]
We'll work on updating documentation soonish, been busy around here :)
