### ISSUE TITLE
No results to neo4j from PSE Bloodhound module

### ISSUE THREAD

**Issue by ll3N1GmAll** [BloodHoundAD/BloodHound#196]
I am using 'Invoke-BloodHound  -SearchForest true -UserPass user:pass -URI "http://192.168.1.131:7474"'. My neo4j is bound to 0.0.0.0 and can be accessed from the target machine via the browser. When my command runs I do not get any results to neo4j or the bloodhound interface. Am I missing something? When I run this locally without specifying the URI/UserPass I get the CSVs as expected. Thanks for your help!

**Comment by rvazarkar** [comment]
REST API ingestion has been deprecated as of 1.5. Use CSV ingestion instead

**Comment by ll3N1GmAll** [comment]
Does this mean the only way to get data into BLoodhound is to run Invoke-BloodHound and then to manually exfiltrate the CSVs from the target to your attacker machine and then manually import them?

**Comment by rvazarkar** [comment]
Yes. The CompressData flag exists to make this process easier
