### ISSUE TITLE
"ObjectProps" collection method missing from doc

### ISSUE THREAD

**Issue by ClementNotin** [BloodHoundAD/BloodHound#199]
The "ObjectProps" collection method is missing from [wiki page](https://github.com/BloodHoundAD/BloodHound/wiki/Data-Collector) and from the [blog post about version 2](https://posts.specterops.io/bloodhound-2-0-bc5117c45a99) whereas it's present [in the code](https://github.com/BloodHoundAD/SharpHound/blob/master/Sharphound2/Sharphound.cs#L148).

**Comment by rvazarkar** [comment]
Fixed!
