### ISSUE TITLE
'Change Layout Type' button not working

### ISSUE THREAD

**Issue by AidanMcCarthy** [BloodHoundAD/BloodHound#202]
Unable to get this button working correctly as it was in the last version. Clicking gets me the notification up top in red however the graph layout doesn't change.

Seems that I have to change the layout type and then re-run the query to get it to display in that layout.

**Comment by rvazarkar** [comment]
I think I fixed this bug in rolling. For now you can right click on the
graph to change the layout

**Comment by AidanMcCarthy** [comment]
Perfect! Thanks :)

**Comment by rvazarkar** [comment]
Fixed in 2.0.1
