### ISSUE TITLE
Error when running SharpHound 2.0

### ISSUE THREAD

**Issue by markajbell** [BloodHoundAD/BloodHound#203]
I have had this error several times since the release of SH 2.0. It only seems to appear randomly as I've run SH 4 times this evening to recreate this error. 

https://files.slack.com/files-pri/T20LT7NJX-FC7AUUXND/image.png

**Comment by markajbell** [comment]
running on Windows 10 Pro (17134.191). DC is Win 2016.

**Comment by rvazarkar** [comment]
Should be fixed in 2.0.1

https://github.com/BloodHoundAD/BloodHound/releases/tag/2.0.1
