### ISSUE TITLE
Import completes, icon doesn't update

### ISSUE THREAD

**Issue by AidanMcCarthy** [BloodHoundAD/BloodHound#205]
![image](https://user-images.githubusercontent.com/25337485/44152059-5f47ac32-a072-11e8-982e-d931471d20f8.png)

Once import has completed, the icon stays at 100% with the scrolling bar. Attempting another import results in a dialog confirming whether you want to cancel the current import.

![image](https://user-images.githubusercontent.com/25337485/44152091-82754a34-a072-11e8-8a0b-5bdd1bf01da6.png)

Windows 10

**Comment by rvazarkar** [comment]
Fairly sure this is fixed in 2.0.1 (https://github.com/BloodHoundAD/BloodHound/releases/tag/2.0.1)

If not, feel free to re-open
