### ISSUE TITLE
Uploaded user pictures are not deleted from disk

### ISSUE THREAD

**Issue by cnotin** [BloodHoundAD/BloodHound#206]
When a user picture is uploaded, it is stored in "images" in the BloodHound folder.
But, when the image is deleted from the user it isn't deleted from disk. Same when the database is cleared.

I have a simple patch but the problem is that two users could have the same uploaded image (since the filename is the MD5 hash of the original file path), then deleting the file when removing the picture from the first user would create a file not found problem when viewing the second user...

A suggestion is to base the filename on the full username hash instead. Note that in this case duplicate files will be stored.
I can contribute that if you want!

**Comment by rvazarkar** [comment]
Closing this since we deprecated the image feature
