### ISSUE TITLE
How to use Collector Directions are vague when using Kali

### ISSUE THREAD

**Issue by NtHawk101** [BloodHoundAD/BloodHound#209]
I'm trying to install on Kali rolling version 2018.2 and there is no Powershell. I looked into installing it but it fails with an error related to libcurl3 not being installable. There directions on this site don't really go into any detail at all on how to use the collector from a Linux perspective. Can that be added? I can see the .ps1 file itself so I'll look to see if I can pull it out and run it outside of Kali but I'd like a better option.

Thanks!

**Comment by rvazarkar** [comment]
If you want to run the collector you'll need to do it from a windows host. It relies on built in Windows APIs. Alternatively, you can try the project [here](https://github.com/fox-it/BloodHound.py). The python collector will not collect all the data, but its runnable from a linux context.
