### ISSUE TITLE
Pre-Built Analytics - Missing Top 10 Queries

### ISSUE THREAD

**Issue by DeC1pher** [BloodHoundAD/BloodHound#211]
Beginning with BloodHound 2.0 I am missing following Predefined queries in Windows:

Find Top 10 Users with Most Sessions
Find Top 10 Computers with Most Sessions
Find Top 10 Users with Most Local Admin Rights
Find Top 10 Computers with Most Admins

I already updated to v2.0.3 but this didnt helped:

![query](https://user-images.githubusercontent.com/36438641/44509761-d9025b80-a6b2-11e8-982d-8089bd16fa23.PNG)

Thanks

**Comment by nickvangilder** [comment]
I am also experiencing this same issue with 2.0.

**Comment by rvazarkar** [comment]
We removed those queries in 2.0. If you need them, you can add them to your CustomQueries file. The original queries are found here:

https://github.com/BloodHoundAD/BloodHound/blob/e17462cf50422bfe9572e60390d32479fdbc32c4/src/components/SearchContainer/Tabs/PrebuiltQueries.json
