### ISSUE TITLE
Bloodhound not working on VMWare

### ISSUE THREAD

**Issue by RivaSilvercrown** [BloodHoundAD/BloodHound#212]
Hi,

I have installed it following the instructions at the wiki but when I launch it I get only a blank screen:

![image](https://user-images.githubusercontent.com/1859605/44628371-876e0100-a93e-11e8-986e-93f62f3b560f.png)

I am using openjdk 1.8 and neo4j 3.4.6 over parrot linux.

**Comment by rvazarkar** [comment]
Press ctrl + r to reload the interface
