### ISSUE TITLE
CSV upload to bloodhound app -> unrecognized file

### ISSUE THREAD

**Issue by x00-R0n1n** [BloodHoundAD/BloodHound#214]
OSX: 10.13.6
Neo4j : 3.2.5
Bloodhound App: 2.01

CSV's generated by CME or directly on the host using bloodhound_old.ps1 is unrecognized by the OSX Bloodhound app when attempting to upload csv data files.

**Comment by andyrobbins** [comment]
Hi @x00-R0n1n,

CSV ingestion was deprecated with BloodHound 2.0, per this blog post: https://posts.specterops.io/bloodhound-2-0-bc5117c45a99 

We'll need to discuss the CME issue with Marcello and see if he can update the plug-in used by CME for doing BloodHound data collection.

The output from BloodHound_old.ps1 is incompatible with BloodHound 2.0 - to avoid further issues in the future we're going to remove this PS1 from the repo.

You should download and run the latest data collector, SharpHound.exe or SharpHound.ps1 and re-do your data collection, then import the resulting zip or JSON files into the interface. Check out the blog post above for more information about that.

Andy

**Comment by x00-R0n1n** [comment]
Thanks, missed that post.  CME is running the bloodhound_old script so this is the reason for CSV output.
