### ISSUE TITLE
Sharp hound issue

### ISSUE THREAD

**Issue by Lee123Mitchell** [BloodHoundAD/BloodHound#215]
Hi All

First of all thank you for all your hard work on this project so far. From what i have seen this will be extremely useful.

Unfortunately i have not been able to run the enumeration scripts as they seem to fail. The errors look very similar to errors others have reported.

![image](https://user-images.githubusercontent.com/43544523/45961097-a3d08c80-c015-11e8-870b-6c98bccde98e.png)

The above is what i get if i use the powershell script

![image](https://user-images.githubusercontent.com/43544523/45960460-33753b80-c014-11e8-9624-be24f4d25d9c.png)

The above is what i get if i use the exe in the Debug folder

![image](https://user-images.githubusercontent.com/43544523/45960487-412ac100-c014-11e8-9e93-5d8639a0e28d.png)

The above is what i get if i run the main sharphound exe. It does manage to do some enumeration before it fails

![image](https://user-images.githubusercontent.com/43544523/45960545-615a8000-c014-11e8-898d-f7a6a2210dd4.png)

It looks like its failing on the trusts enumeration. I am running it on Windows 10 1709 but i have tried it on server 2012 R2 and it failed on that too

Any help is greatly appreciated.

Regards

**Comment by rvazarkar** [comment]
Fixed in https://github.com/BloodHoundAD/SharpHound/commit/3d3d65c4cf9b4ce28bc64bc9db60ea373513aa1c
