### ISSUE TITLE
[Feature Request] Import from LDIF file

### ISSUE THREAD

**Issue by aress31** [BloodHoundAD/BloodHound#219]
Hi,

I am wondering whether it could be possible to populate the neo4j database with a LDIF file generated using the ldapsearch utility. 

The following command could be used to create the LDIF file containing all the forest/domain objects:
```
ldapsearch -LLL -E pr=1000/noprompt -x \
    -h dc1.corp.foo.com \
    -b "DC=corp,DC=foo,DC=com" \
    -D "joe.bloggs@corp.foo.com" \
    -w "superP@55w0rd!" \
    > corp.foo.com.ldif
```
That could be a very useful feature for pentesters remotely connected to a Kali box for example. Because they could then just run the command mentioned above to query the DC for all the information required to feed BloodHound without the hassle of having to configure routing/VPN on their host machine to run a Powershell prompt with `runas` to use the ingestors.

Kind regards,
Alex

**Comment by variableresults** [comment]
I'll 2nd this. LDIF exports from AD are far faster than the ingestor scripts. I manage a huge forest and the ingestor is painful to use since it takes so long.

**Comment by gitsreerao** [comment]
+1 on the LDIF import feature

**Comment by AdrianVollmer** [comment]
This will not collect session information, RPD privs or local admin data, which are some of the most interesting pieces of information. I recommend using https://github.com/fox-it/BloodHound.py for your use case.

**Comment by rvazarkar** [comment]
We won't be implementing this, however, would be interested to see open source implementations pop up if anyone has the time.

**Comment by AdrianVollmer** [comment]
https://github.com/SySS-Research/ldif2bloodhound
