### ISSUE TITLE
Bloodhound misses group memberships

### ISSUE THREAD

**Issue by dmb2168** [BloodHoundAD/BloodHound#222]
Bloodhound collections seem to miss-represent user's group memberships. Several bloodhound collections I've run have incorrectly reported multiple user's group memberships. 

I've tested on the latest version of Bloodhound using both the "ACL" and explicit "group" collection options. Very anecdotal, but the failure seems to happen in large complex domain environments.

**Comment by andyrobbins** [comment]
Can you provide some more data that might help us troubleshoot this? Is it missing foreign group memberships, groups with special characters in their name, distribution groups, etc? Is there anything common across the affected users/groups? Is the group membership different between "ACL" and "group" collection types? Thanks!

**Comment by dmb2168** [comment]
As far as I can tell there isn't too much commonality - this is related to my work @Mandiant so all of the instances I've come across this issue have been at unique domain environments.

The group memberships are not foreign groups, they are within the same domain the user resides in. No special characters beyond "-" and "_" in some group names. In some cases a user will report as belonging to 0 groups when they belong to many, in other cases the user will have group memberships, but the list is incomplete when compared to the output from PowerView for example. The only commonality I have is that the environments were relatively large (100k+ users)

Without really knowing the guts of the BloodHound ingest process I wonder if there is some sort of timeout that is happening and causing null output?  My colleagues internally have experienced similar issues at other client environments

**Comment by rvazarkar** [comment]
This seems to actually be an issue with domain controllers, not with SharpHound. Other people have reported this same issue and solved it by manually targetting the primary domain controller during enumeration.

I think we're just going to default enumeration to the Primary Domain Controller for now, because I honestly have no clue whats causing this issue.

**Comment by rvazarkar** [comment]
Change made in https://github.com/BloodHoundAD/SharpHound/commit/77045baad4726f3759b64829c94c8e5353824153

**Comment by dmb2168** [comment]
Oh wow that's interesting and mysterious! Thanks for that.
