### ISSUE TITLE
Sharphound.ps1 exports failing to import

### ISSUE THREAD

**Issue by secureideas** [BloodHoundAD/BloodHound#224]
Hi,

While I hate posting issues I don't have any idea how to fix, we have run into an issue.  We ran Sharphound.ps1 and received a zip of the output.  When trying to import it inot Bloodhound we received a "Bad JSON" error.

**Comment by secureideas** [comment]
2.0.3.1 is the version we are using.

**Comment by secureideas** [comment]
Thanks I will check that out.  I swore that it finished correctly but am probably wrong.  :)

**Comment by abdullahkareem** [comment]
Hi guys, 

i am encountering the same issue while importing a zip file and it says bad json file.
the bloodhound's version is 3.0.5
any advice please?

**Comment by ssh30** [comment]
> Hi guys,
> 
> i am encountering the same issue while importing a zip file and it says bad json file.
> the bloodhound's version is 3.0.5
> any advice please?
just drag and drop the zip file into bloodhound

**Comment by lawson2305** [comment]
So I have battled this issue from time to time and what I have found is.  If I drag and drop I get the failure along with the import graph button.  If I use the button that says "Upload Data" right below the "import graph" button it works.

Hopefully this helps someone.
