### ISSUE TITLE
Edge filtering doesn't apply to Custom Queries

### ISSUE THREAD

**Issue by JonZeolla** [BloodHoundAD/BloodHound#225]
Currently, the edge filtering doesn't apply to custom queries.  Given the UI configuration, and the usefulness of checkbox edge filtering, I would suggest that is applied across all stored queries.

**Comment by rvazarkar** [comment]
As far as I can tell, all the prebuilt queries that use shortestPath should use edge filtering. Which queries in particular are not working with filtering? They might be hardcoded to use certain edges because of the functionality of the query itself

**Comment by JonZeolla** [comment]
Is it possible/reasonable to take the results of the custom query and remove any unselected edges?  I could take a stab at this if it isn't architecturally unreasonable

**Comment by rvazarkar** [comment]
Can you give me an example of which custom queries aren't working the way you expect?

**Comment by rvazarkar** [comment]
Closing this as theres a lack of response
