### ISSUE TITLE
No Database Found for prebuilt binary

### ISSUE THREAD

**Issue by hook-s3c** [BloodHoundAD/BloodHound#226]
Do I need to install Neo4j? Assumed it was all packaged within the Electron app.

Please advise.

**Comment by hook-s3c** [comment]
Might want to update the default creds listed to neo4j's defaults as it's not contextually aware of Bloodhound before running the binary.

**Comment by duncandw** [comment]
I've installed neo4j and BloodHound on a Ubuntu 19.10 system; neo4j seems working fine; I can look into the BloodHound example database and I see the nodes and relationships via the web interface http://127.0.0.1:7474/browser/.
But when I launch ./BloodHound it does start but in the logon screen it keeps telling me the red circle with the white cross' No database found'  when I use the url bolt://localhost:7687.
Anyone that has seen this before or know what I'm doing wrong?

**Comment by Ifonly-go2019** [comment]
> I've installed neo4j and BloodHound on a Ubuntu 19.10 system; neo4j seems working fine; I can look into the BloodHound example database and I see the nodes and relationships via the web interface http://127.0.0.1:7474/browser/.
> But when I launch ./BloodHound it does start but in the logon screen it keeps telling me the red circle with the white cross' No database found' when I use the url bolt://localhost:7687.
> Anyone that has seen this before or know what I'm doing wrong?

now working? i have the same problem:(
