### ISSUE TITLE
Importing BloodHoundExampleDB.graphdb is not working

### ISSUE THREAD

**Issue by HachimanSec** [BloodHoundAD/BloodHound#229]
Hi,
I have been searching and reading for quite some time but can't find a solution, so I hope I don't miss anything obvious.

I just installed bloodhound via `apt install bloodhound` (stable repository) on a latest Kali linux:
`Linux 4.18.0-kali2-amd64 #1 SMP Debian 4.18.10-2kali1 (2018-10-09) x86_64 GNU/Linux`

I can start neo4j console, login and do the necessary password change. 
Bloodhound also starts with the empty DB and is able to connect via bolt.

Then I downloaded the BloodHoundExampleDB.graphdb from Github and stored it in `/data/databases` as written in [Wiki Getting started](https://github.com/BloodHoundAD/BloodHound/wiki/Getting-started)

I modified the neo4j.conf according to this part from the wiki:

> Open neo4j.conf, and uncomment the line #dbms.active_database=graph.db. Change this line so it reads as dbms.active_database=BloodHoundExampleDB.graphdb. Also uncomment the line #dbms.allow_upgrade=true so that it reads as dbms.allow_upgrade=true, then save this file.

When I start neo4j I still have to login with the credentials I have chosen in the very beginning. 
I can see the example DB but it seems empty (see screenshot):
![image](https://user-images.githubusercontent.com/20123996/51207248-90ba3300-190a-11e9-903d-b14c713b80b1.png)

When I now start bloodhound, I also have to provide the password I chose and not the one described in 
[Wiki - Interface-Intro](https://github.com/BloodHoundAD/BloodHound/wiki/Interface-Intro
)
> "The password for the provided example database is BloodHound."

When I log in to bloodhound with my credentials, it says that no data could be retrieved and the DB is empty.
![image](https://user-images.githubusercontent.com/20123996/51207327-ca8b3980-190a-11e9-8560-bfc4157ee9fa.png)

I am not sure what I am missing but any help is highly appreciated. 

Thanks!

![image](https://user-images.githubusercontent.com/20123996/51207332-cced9380-190a-11e9-8c59-3fba7610282f.png)

**Comment by TomHubGit** [comment]
Some additional info.
It seems like I misinterpreted the documentation. 
Obviously the default path for data/databases is `/usr/share/neo4j/data/databases` and not just `/data/databases`

I moved the GitHub graphdb into the directory and restarted neo4j console as well as Bloodhound.

```
neo4j console
Active database: BloodHoundExampleDB.graphdb
Directories in use:
  home:         /usr/share/neo4j
  config:       /usr/share/neo4j/conf
  logs:         /usr/share/neo4j/logs
  plugins:      /usr/share/neo4j/plugins
  import:       /usr/share/neo4j/import
  data:         /usr/share/neo4j/data
  certificates: /usr/share/neo4j/certificates
  run:          /usr/share/neo4j/run
Starting Neo4j.
WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
2019-01-15 20:30:54.752+0000 INFO  ======== Neo4j 3.4.6 ========
2019-01-15 20:30:54.789+0000 INFO  Starting...
2019-01-15 20:30:56.078+0000 INFO  Starting upgrade of database
2019-01-15 20:30:56.389+0000 INFO  Migrating Explicit indexes (1/4):
2019-01-15 20:30:56.393+0000 INFO    10% completed
2019-01-15 20:30:56.393+0000 INFO    20% completed
2019-01-15 20:30:56.393+0000 INFO    30% completed
...
```
Again, when I log in to bloodhound and connect to neo4j via bolt I have to use the password I set during initial setup, not the one mentioned in the documentation. 

Executing a query in Bloodhound now leaves me with an ongoing "sandclock"... 
![image](https://user-images.githubusercontent.com/20123996/51208371-c7de1380-190d-11e9-80bc-9af5c974eabd.png)

**Comment by TomHubGit** [comment]
This is the output I seem from the terminal where `neo4j console` is running:
```
2019-01-15 20:31:15.097+0000 WARN  The client is unauthorized due to authentication failure.
2019-01-15 20:31:21.417+0000 WARN  The client is unauthorized due to authentication failure.
2019-01-15 20:39:04.377+0000 WARN  The client is unauthorized due to authentication failure.
2019-01-15 20:40:27.185+0000 WARN  The client is unauthorized due to authentication failure.
2019-01-15 20:40:43.067+0000 WARN  The client is unauthorized due to authentication failure.

```

Is it possible that there is somehow a miss match between the initial password I had to set and the password used for the example DB? 

Every time I use `BloodHound` as DB password, I get an access denied error:
![image](https://user-images.githubusercontent.com/20123996/51208659-9154c880-190e-11e9-945f-44c2aff961b7.png)

**Comment by TomHubGit** [comment]
It seems like I came one step closer. 

When Bloodhound start it shall display the members of the Domain Admin group.
However it seems like there are no Domain Admins in the example graph db.

This is just an assumption and is kinda confusing as one would assume that an example db would have Domain Admins. Or there is still something wrong with my setup...
![image](https://user-images.githubusercontent.com/20123996/51210741-d7f8f180-1913-11e9-9a9a-f40b105db07f.png)

**Comment by TomHubGit** [comment]
Even though the example DB seems to contain 391 users (when check under "Database Info"). However when I select the Domain trust, neither the internal nor the external one got any items (see screenshot)
![image](https://user-images.githubusercontent.com/20123996/51210967-6cfbea80-1914-11e9-83ac-e74f4bd47a32.png)
![image](https://user-images.githubusercontent.com/20123996/51210987-784f1600-1914-11e9-99e4-4f9f6019c98d.png)

**Comment by rvazarkar** [comment]
Hey Tom,

The example db is unfortunately quite outdated, which is why you're getting issues with the counts of items and stuff. We'll need to update the DB to a newer version soon to account for this. Sorry about the issues.

**Comment by rvazarkar** [comment]
We've updated the example DB included with BloodHound to be significantly better, which should resolve this issue. Sorry for the inconvenience!
