### ISSUE TITLE
[Question] Mitigation of BloodHound

### ISSUE THREAD

**Issue by CG-root** [BloodHoundAD/BloodHound#231]
What action items can be used in order to prevent the use of BloodHound to run successfully?

**Comment by 0xB455** [comment]
You may find this blog post helpfull:
https://www.stuffithoughtiknew.com/2019/02/detecting-bloodhound.html

TL;DR
Preventing is hard, but detection is possible by analyzing network traffic and AD logs

**Comment by rvazarkar** [comment]
For what its worth, we frequently tell people not to worry about trying to stop BloodHound, instead fix the issues that BloodHound shows you. 

That being said, there's several ways to limit the amount of data that BloodHound can grab. You can use [NetCease](https://gallery.technet.microsoft.com/Net-Cease-Blocking-Net-1e8dcb5b) to prevent unprivileged session enumeration, and [Samri10](https://gallery.technet.microsoft.com/SAMRi10-Hardening-Remote-48d94b5b) to prevent unprivileged local admin collection (this fix already exists in Windows 10 1607 and above).
