### ISSUE TITLE
Wiki: neo4j database

### ISSUE THREAD

**Issue by noraj** [BloodHoundAD/BloodHound#234]
https://github.com/BloodHoundAD/BloodHound/wiki/Getting-started

Default password are `neo4j` / `neo4j` and not `neo4j` / `BloudHound` for me on ArchLinux and before to be used the password must be change at http://localhost:7474/

**Comment by Ir0nvIP3r** [comment]
Same in Windows

**Comment by noraj** [comment]
New content is here after the wiki was deprecated: https://bloodhound.readthedocs.io/en/latest/installation/linux.html
