### ISSUE TITLE
Unable to pass the way of socks5

### ISSUE THREAD

**Issue by FuckAllWorld** [BloodHoundAD/BloodHound#240]
Unable to pass the way of socks5 collect domain information

`SharpHound.exe --DomainController 10.10.10.10 --LdapUser testlab\administrator --LdapPass xxxxx.
Initializing BloodHound at 12:08 on 2019/3/18
Unable to contact domain. Try from a domain context!`

parameter -d is same

**Comment by NoneNotNull** [comment]
SharpHound.exe --DomainController 10.10.10.10 --Domain testlab --LdapUser administrator --LdapPass xxxxx

**Comment by rvazarkar** [comment]
Is this still an issue?

**Comment by NoneNotNull** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，邮件已收到，我会尽快回复
