### ISSUE TITLE
Missing Information after Invoke

### ISSUE THREAD

**Issue by dracod3** [BloodHoundAD/BloodHound#244]
I didn't seem to have this issue with previous builds of Bloodhound (talking early 2018) but I have been on the most recent Bloodhound / Sharphound instances.  I am using a "standard account" with no permissions (Domain User only).  When I ran earlier builds of Bloodhound, I was able to extract RDP, sessions, trusts etc. 

However on running the newest versions I am not getting the same result.  I am simply getting the computer objects, users and groups but no correlation.  The only JSON that is generated when executing Sharphound is the computer, users and groups json files.

I am running Sharphound by using the following commands

* import-module .\Sharphound.ps1
* Invoke-Bloodhound -All

Any thoughts as to why I am no longer getting session information, RDP, Trusts etc.?  Do I need to change permissions on the newer version?  Do I just go back to an older version that only required low level Domain User access.

**Comment by syn-4gvn** [comment]
I am also having this issue. I ran it as @dracod3 ran it with `Invoke-Bloodhound -All`. This was for a test environment, running as a Domain User on a member server. I have an active session (DA to the member server I was running on) and the result was 0 sessions. I then ran the same on the DC as a DA, still no sessions being recorded. 

I also tried explicitly calling out the output I wanted (this was from the DC running as DA): `Invoke-Bloodhound -CollectionMethod Group,Trusts,LocalAdmin,RDP,ACL,Session`, still no session information (confirmed session was active still). Finally, I tried a session loop to no avail. This gave a session json file with no contents: `Invoke-BloodHound -CollectionMethod Group,Trusts,LocalAdmin,RDP,ACL,Session,SessionLoop`. Interested in the reasoning, if I have more time I'll dig into it.

**Comment by dracod3** [comment]
In the interim I am going to go back to the previous version for my purposes.  Is there a debug mode when executing to find out why this is actually failing?

**Comment by jopels** [comment]
The commands for invoking Sharphound changed recently.
I use the following command:
`& .\SharpHound.exe --CollectionMethod Group,LocalGroup,RDP,DCOM,GPOLocalGroup,Session,ObjectProps,Trusts,ACL,Container`

**Comment by rvazarkar** [comment]
It should be Invoke-BloodHound -CollectionMethod All

I dont know why -All would work or what it would resolve that command too.
