### ISSUE TITLE
White Screen at Startup. Ctrl-R Does Not Solve

### ISSUE THREAD

**Issue by r35pect** [BloodHoundAD/BloodHound#256]
![image](https://user-images.githubusercontent.com/40766624/59527969-ff47f080-8eaa-11e9-80ad-f769654ceb39.png)

OS: Server 2016
App: BloodHound-win32-x64 Precompiled v2.1.0

Bloodhound will not load. Simply starts a white screen and Ctrl-R does not solve the issue.

**Comment by rvazarkar** [comment]
Press ctrl + shift + i and see if there's errors in the console. Last time this happened, it was because Windows defender ate some files in the archive

**Comment by r35pect** [comment]
![image](https://user-images.githubusercontent.com/40766624/59532134-dda03680-8eb5-11e9-8e28-04c973f184a9.png)

**Comment by bokandbok** [comment]
Check that the %JAVA_HOME% environment variable is properly set to the Java Home Directory. For example C:\Program Files\Java\jdk-11.0.6
