### ISSUE TITLE
[Question] How can I get information from an entire forest?

### ISSUE THREAD

**Issue by CG-root** [BloodHoundAD/BloodHound#257]
I executed the ingestor but it seems that only information about the current domain is being obtained along with domains trusts.
Is there a way to instruct the ingestor to go all over the entire forest?
Thanks !

**Comment by andyrobbins** [comment]
Hi @CG-root,

Take a look at the documentation in the wiki under "Data collector" here: https://github.com/BloodHoundAD/BloodHound/wiki/Data-Collector 

There is a flag for SharpHound, -SearchForest, which will instruct SharpHound to enumerate each domain it can view from its current context, and collect data from each of those domains.

Andy
