### ISSUE TITLE
Can't set the computer as owned

### ISSUE THREAD

**Issue by junmoxiao** [BloodHoundAD/BloodHound#260]
Can't set the computer as owned.
Only user can be set as owned.

**Comment by sysophost** [comment]
Which version of Bloodhound are you using? The latest builds are located [here](https://github.com/BloodHoundAD/BloodHound/releases).

I've just tested using v2.2.0 and I can right click a computer node and "mark computer as owned". 

You could also do this manually via the Neo4j web interface using (http://localhost:7474):
`MATCH (c:Computer {name:"SOME_COMPUTER@MYDOMAIN.COM"})  SET c.owned=TRUE RETURN c.name, c.owned`

**Comment by littlepig1337** [comment]
Thank you! solved

**Comment by rvazarkar** [comment]
I cant replicate this, I can easily set a computer as owned. If you have more details, feel free to re-open this
