### ISSUE TITLE
"Failed to establish connection in 5000ms" console log error  

### ISSUE THREAD

**Issue by bravo2day** [BloodHoundAD/BloodHound#262]
After updating to the latest BH 2.2.0 i recieve errors in the console log while importing data aquired with the new Sharphound collector.
Everything is running on the same box -  neo4j-community-**3.5.2**
The import continiues but I am worried i might be missing data. 

Google/Neo4j tells me this is a neo4j standard error message:

> Failed to Establish Connection in (5000)ms.
> When a driver attempts to connect to the server, it has a default amount of time that it will wait for a response from the server before giving up. When you get this message, it generally means that you did make a connection to the server, but the server isn't responsive within that timeout window. It may not be 5000ms, this is a configurable driver setting, and will depend on which language driver you're using, and your local configuration.
> 
> A common reason why this error occurs is that your Neo4j instance is under heavy load. For example if you're running a query that is soon going to result in an Out of Memory error, it would be possible to run into this error. Another possibility is extremely high network latency between your machine and the Neo4j instance, for example if you're on a low quality wifi link.

Am I alone in recieving this error (50 errors total on a 32MB zip)

![image](https://user-images.githubusercontent.com/36545668/62617453-2ef70000-b912-11e9-9efe-b36bab9cb38b.png)

**Comment by bravo2day** [comment]
I just realized that the error's might not be connected to the import at all, as i get 1 of them as soon as i open BH and connect to the DB 
![image](https://user-images.githubusercontent.com/36545668/62621138-76ce5500-b91b-11e9-9e0d-9a1b33b138dd.png)

**Comment by bravo2day** [comment]
After realising i [might have been using a "too new" version of Neo4](https://github.com/neo4j/neo4j-java-driver/wiki)j I changed to neo4j-community-**3.3.4**

No errors on startup - No errors during import. 
Guess this can be closed? I'm not sure this was even a problem, but I feel more comfortable running 3.3.4 with no errors.

**Comment by Crypt0-M3lon** [comment]
Got the same issue, I fixed it by disabling timeout globally, it's probably not the best solution but Bloodhound is usable again on a big domain.

Replace [these line](https://github.com/BloodHoundAD/BloodHound/blob/master/src/components/Float/Login.jsx#L253) with
```
{
    connectionTimeout: 0,
    disableLosslessIntegers: true 
}
```

@rvazarkar Did you experience the same issue ?

**Comment by rvazarkar** [comment]
I get this error very occasionally, but it never has any impact on the actual running of the UI. I guess I can change the connectionTimeout if this is a recurring problem, but I'm kind of hesitant to do so, since the real issue seems to be more along the lines of the neo4j instance just not handling the load

**Comment by cnotin** [comment]
Same here!
Why not increase the value to something higher than 5s? ([default](https://neo4j.com/docs/api/javascript-driver/current/function/index.html))

**Comment by johnmccash** [comment]
Is there a way to extend or disable the timeout without recompiling Bloodhound?

**Comment by johnmccash** [comment]
And is the timeout actually resulting in data being skipped, or is it getting picked up by a retry of some sort?

**Comment by johnmccash** [comment]
I've been attempting to build Bloodhound from source, in order to incorporate the timeout disable suggested above, but am running into issues with npm failing to build it properly from behind our corporate firewall (It's getting a "connect ECONNREFUSED 140.82.113.3:443" error, and that IP is the address returned by DNS for github.com imediately before). I've set all of the proxy variables, as well as setting the proxy configuration within npm, but still am having problems. I doubt this is actually a problem with Bloodhound though. Can somebody do a build of the Windows exe for me with the timeout disabled? Pretty please :-)
Thanks

**Comment by johnmccash** [comment]
Oh, one more thing. Most of these timeouts are NOT being caught. I'm not sure whether that matters or not, but I'm attaching a partial dump from my console.

[-1570037501602.log](https://github.com/BloodHoundAD/BloodHound/files/3682488/-1570037501602.log)
of one of my Bloodhound console logs.

**Comment by johnmccash** [comment]
I was finally able to get Bloodhound rebuilt (had to essentially patch around the proxy). Now the graph does actually build, which suggests that the timeout setting really does need to be modified for large graphs.

**Comment by rvazarkar** [comment]
I'm going to up the timeout to 120 seconds. Is that a reasonable compromise? I don't want to set it to infinite, because it will almost certainly cause issues with memory leaks/hanging sockets

**Comment by cnotin** [comment]
@johnmccash sorry for the late answer but you could directly edit Login.jsx in your bloodhound release folder, e.g.:
"...\BloodHound-win32-x64\resources\app\src\components\Float\Login.jsx"
No need to rebuild then :)

@rvazarkar looks nice!

**Comment by rvazarkar** [comment]
Fixed in https://github.com/BloodHoundAD/BloodHound/commit/059c3c61409aee24743e0d43493b0c40bda56554
