### ISSUE TITLE
SessionLoop doesn't exit cleanly

### ISSUE THREAD

**Issue by PaperMtn** [BloodHoundAD/BloodHound#264]
When attempting to run Bloodhound with the `SessionLoop` option, when the time limit is reached, the script does not finish and cleanup the files. It just hangs on `Exiting session loop as LoopEndTime has passed.`

**Comment by bravo2day** [comment]
Same issue here. "CTRL+C" does (usually) trigger a clean exit tho.

**Comment by rvazarkar** [comment]
THis should be fixed in v3.
