### ISSUE TITLE
Updating scan information in existing database

### ISSUE THREAD

**Issue by c3101** [BloodHoundAD/BloodHound#266]
Running bloodhound for blue teaming, and I regularly scan the environment, one scan per domain per week say.

Do I need to clean the database and import the new scan data fresh?
Or can I import the new scan data "over" last weeks data?
Or do I clean just the session information and import over last weeks data?

Does bloodhound "break" links between nodes if membership or permissions changed between scans and not clearing the database before importing?

**Comment by bravo2day** [comment]
When you import the new data it will add to the database. So you will not get a correct picture.

User A has membership in Group 1 
You run Sharphound and import the data.
Now user A is removed from Group 1 and added to Group 2
You run Sharphound again and import the data.
User A now has membership in Group 1 and Group 2 in your database.

I personally do a "fresh db" every week to make sure i have the right memberships. In between i just clear sessions.
