### ISSUE TITLE
SharpHound requires several runs to get all groups

### ISSUE THREAD

**Issue by l0ss** [BloodHoundAD/BloodHound#269]
In a moderately large domain, 70,000ish users, 20,000ish groups, I run SharpHound with -CollectionMethod All, and it successfully gets all users, and only a couple hundred groups. 

I run it again with -CollectionMethod Groups, and I get the remaining groups.

I also seem to be getting far fewer sessions and almost no information about who's got LocalAdmin where, even after running those collection methods independently. That last part may be unrelated.

No error messages displayed.

**Comment by l0ss** [comment]
Oh, collection was performed with SharpHound v2.2, although i've seen similar behaviour from this domain before on older versions of the ingestor.

**Comment by rvazarkar** [comment]
Is this still happening on v3?

**Comment by l0ss** [comment]
I haven't had the chance to test in that domain since v3 came out. I'll be able to in the next couple of weeks i expect.

**Comment by l0ss** [comment]
confirmed, v3 resolved this issue. Cheers!
