### ISSUE TITLE
Empty database view after successfull import of SharpHound Collection

### ISSUE THREAD

**Issue by cyb3rwr3ck** [BloodHoundAD/BloodHound#271]
Hi there,

versions used: 

- Sharphound 2.2
- Bloodound 2.1 & 2.2.1

Problem:
The content of the zip file looks good, all files are containing valid JSON. After dropping the archive to bloodhound it imports it without any errors, but the database-counters are still 0. 
I've imported an older collection without any errors, additionally a collection of the same AD done with BloodHound.py was successfully imported.

**Comment by mattwalkr** [comment]
Hi cyb3rwr3ck,

Curious if you've identified a solution for this? I'm experiencing same issue. Sharphound collects data without error. Drop into Bloodhound and import seems to occur without error as well but all counters showing 0.

**Comment by cyb3rwr3ck** [comment]
Hi,
unfortunately not. I had one occurrence where a colleague queried the same AD with the powershell version of the ingestor and this import was actually browsable. Options of the collections were the same.

**Comment by rvazarkar** [comment]
I would try again with the 3.0 release, the logic has been completely rewritten both on the collection and ingestion side

**Comment by mattwalkr** [comment]
Thanks, rvazarkar. Read the release notes for bloodhound version 3 and realized my attempts were flawed. After using recent releases for bloodhound, neo4j and sharphound it’s working like a champ! :)

**Comment by sxplitfirex** [comment]
Hello there, i have this same exact issue.
How can I check if my versions are the latest?

Thank you.
