### ISSUE TITLE
Mac OS: No "customqueries.json" file created

### ISSUE THREAD

**Issue by jstigerwalt** [BloodHoundAD/BloodHound#272]
There seems to be an issue after a Bloodhound install on MacOS that no "customqueries.json" file is created. I had to manually create one to get the custom query functionality to work in the application.  

Location file was created that seemed to work:

~/Library/Application Support/bloodhound

**Comment by rvazarkar** [comment]
Fixed in https://github.com/BloodHoundAD/BloodHound/commit/059c3c61409aee24743e0d43493b0c40bda56554
