### ISSUE TITLE
Paused before potential out-of-memory crash

### ISSUE THREAD

**Issue by johnmccash** [BloodHoundAD/BloodHound#274]
So, I'm also seeing a lot of "Failed to establish connection in 5000ms" messages (#262), which may be contributing to this problem. Basically, I'm unable to get the "Find Shortest Paths to Domain Admins" query to load with all edge types selected. It runs for a long time, gets a bunch of the above timeouts, then hangs up with the "Paused before potential out-of-memory crash" error. I've tried raising the memory limits in the Neo4j config file, as well as raising the java memory limits in the java control panel (-Xms40960m). The host I'm running this on has plenty of memory (64GB).

**Comment by johnmccash** [comment]
I just updated "Failed to establish connection in 5000ms" messages (#262). I was finally able to get Bloodhound rebuilt (had to essentially patch around the proxy). Now the graph does actually build. This suggests that the timeout setting really does need to be modified for large graphs. I'm also no longer getting the above crash, so this problem appears to have been due to the timeout issue.

**Comment by rvazarkar** [comment]
I upped the default connection timeout to 120 seconds in https://github.com/BloodHoundAD/BloodHound/commit/059c3c61409aee24743e0d43493b0c40bda56554

Hopefully it fixes this issue
