### ISSUE TITLE
Feature Request: Allow Selection & Move of Edge and Connected Nodes

### ISSUE THREAD

**Issue by johnmccash** [BloodHoundAD/BloodHound#277]
In my large corporate environment graph, it's difficult to tease out the endpoints of an interesting edge, because often one end of the edge is buried in a large pile of nodes of various types. It would be really useful to be able to left-click-and-hold on the link, and move it (with both endpoints), so that I can then easily select and move the endpoint that's currently buried in the pile.

I do see that you can (sometimes?) blow up the link, and follow it back to a point where you can click the node, but that doesn't work nearly as well when trying to pull the right-hand node out of a pile (I will admit I do that less though)

**Comment by rvazarkar** [comment]
This is unfortunately not possible with the graph rendering library we use.

**Comment by johnmccash** [comment]
Is there ANYTHING that CAN be done to manually move a node when you have the node name from the edge data, but the node itself is buried in a huge pile of others with the exact same placement, despite being blown up to max size? The only way I've found is to blow the map up to mac size, and randomly pull out nodes from the pile till I actually get the one I'm looking for. Maybe you could do some kind of select left node and select right node from the edge right click menu?
