### ISSUE TITLE
Custom query showing ACLs on OUs from groups

### ISSUE THREAD

**Issue by jacmarpets** [BloodHoundAD/BloodHound#283]
Hello,

This simple query gives me all groups which have GenerilAll on all groups:

MATCH p=(m:Group)- [r:GenericAll]->(t:Group) RETURN m.name,TYPE(r),t.name

It works fine. But this one, which should do the same, just for OUs, gives me no results:

MATCH p=(m:Group)- [r:GenericAll]->(t:OU) RETURN m.name,TYPE(r),t.name

Anyone know why?

The query will be more complex of course. My thought is to exclude all groups which are privileged by default, so that only "normal" groups are checked for privileges on OUs in the AD environment.

Thanks in advance!

**Comment by rvazarkar** [comment]
ACLs aren't collected on OUs currently. We'll be fixing that in an upcoming
release

**Comment by rvazarkar** [comment]
Fixed in 3.0
