### ISSUE TITLE
ISSUE: Export JSON does not work

### ISSUE THREAD

**Issue by matandobr** [BloodHoundAD/BloodHound#284]
Hey guys,
I'm trying to export a graph to JSON, and it just does not work. 
(No errors...) 
How can I debug this?
Thanks!

**Comment by felixguerrero12** [comment]
The export to JSON is not working for me with the compiled binary. @matandobr Were you able to extract it via JSON Format? If so can you please give me some guidance on what you did.

**Comment by felixguerrero12** [comment]
This is the commit made for the JSON Export - https://github.com/BloodHoundAD/BloodHound/commit/c7dfe2a81637db7f38ac1443a2aa2eba88c09d79

**Comment by rvazarkar** [comment]
Can you try Rolling Release?

https://github.com/BloodHoundAD/BloodHound/releases/tag/BloodHound-Rolling

**Comment by felixguerrero12** [comment]
This worked. Thank you @rvazarkar.

**Comment by nikallass** [comment]
> Can you try Rolling Release?
> 
> https://github.com/BloodHoundAD/BloodHound/releases/tag/BloodHound-Rolling

But it is an old one. 

I also cannot export to JSON. Can smbdy help with it?

**Comment by rvazarkar** [comment]
Fixed in 3.0
