### ISSUE TITLE
DB not found with neo4j 4.0.0

### ISSUE THREAD

**Issue by Ir0nvIP3r** [BloodHoundAD/BloodHound#291]
OS Windows 10 PRO 1903
When setting up with neo4j 4.0.0 the BloodHound application is unable to find the database on the bolt://localhost:7687 address - even though I can find it and connect to it in the webbrowser. 

Also in 4.0.0 neo4j have upgraded some of their dbms syntaxt from what the Wiki Getting-Started suggest so not sure if there might be some other underlaying syntax that might have change as well. 

When downgrading to 3.5.14 it starts working directly.

/Ir0nvIP3r

**Comment by exploide** [comment]
might be due to https://github.com/neo4j/neo4j/issues/12361

**Comment by rvazarkar** [comment]
BloodHound 3.0 will be compatible with Neo4j 4.0. As of now, use 3.5.X

https://github.com/BloodHoundAD/BloodHound/wiki/Getting-started
