### ISSUE TITLE
Collector is flagged by Windows Defender

### ISSUE THREAD

**Issue by mathieuchateau** [BloodHoundAD/BloodHound#292]
Even using PowerShell script, it's detected by Windows Defender

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=HackTool%3aPowerShell%2fSharphound.A&threatid=2147745008&enterprise=0

Not sure something can be done easily about it. Means local admin right is needed to shut windows defender. Even on a computer without antivirus to kill first.

**Comment by TheLawsOfChaos** [comment]
I mean, this makes senses and is desired behavior. A Blue teamer running this should be able to get around this being blocked, and would absolutely want to know when an adversary/red team was using this very method.

**Comment by ionrover2** [comment]
I agree with @TheLawsOfChaos. This is 100% expected behavior and if it wasn't, it would be a very bad thing. HOWEVER, the powershell script does the exact same thing as the exe and is usually not flagged by AV. Give that a shot. I don't think there is much that can be done about this particular issue.

**Comment by mathieuchateau** [comment]
@ionrover2 : As stated in my original comment, even PowerShell version is flagged. Microsoft links is about it. I am fine with antivirus blocking it, but so why making a PowerShell script version ? I thought it was to escape antivirus.

**Comment by andyrobbins** [comment]
Actually one of the primary reasons for the PowerShell version of the data
collector was to maintain the ability to remain memory resident when
running through an agent like beacon. Now with execute-assembly, that need
isn’t felt as strongly, but the PS1 option is still there for folks who
aren’t using beacon.

**Comment by rvazarkar** [comment]
I'm going to close this as AV bypass isn't part of the project's scope. If you want to get around signatures, the easiest way is to change a few things around in the SharpHound source and recompile it yourself.
