### ISSUE TITLE
Upgrade on Kali Rolling to 3.0 instructions?

### ISSUE THREAD

**Issue by wizhardhacker1** [BloodHoundAD/BloodHound#296]
Is it possible to get instructions to upgrade to 3.0 on kali rolling linux ? I have Version: 2.2.1 installed from the repo

**Comment by corsch** [comment]
Is this still a problem? I'm on BloodHound 3 on Kali Rolling via automatic apt updates.

**Comment by rvazarkar** [comment]
You can always manually download a release here. 

https://github.com/BloodHoundAD/BloodHound/releases
