### ISSUE TITLE
Sample DB "objectid" <=> "objectsid"

### ISSUE THREAD

**Issue by FallenHero66** [BloodHoundAD/BloodHound#297]
Hello,
I noticed that my Bloodhound threw a "No data returned from query" error when trying to run the "Find all domain admins" sample query on the sample database.
While trying to figure out what the problem was, I stumbled upon the fact that I couldn't even show single notes.
The Query Debug mode revealed, that the attribute "objectid" is "undefined".

Comparing with the data in neo4j, I noticed that there is no attribute "objectid", but "objectsid".

Hope this helps with fixing.

Cheers

**Comment by rvazarkar** [comment]
Unfortunately, we haven't had a chance to update the sample DB. It's on our to-do list

**Comment by leitosama** [comment]
Hello, guys! I'm using neo4j-communtity 4.0.1 and i had a similar issue not only in sample DB. I had successfully fixed her by changing all of "objectid" entries in code to "objectsid".

**Comment by Brian-Hanrahan** [comment]
lines 227, 367 in DBCreator.py need to be tweaked to use “objectid” in place of objectsid … in case you are interested.

**Comment by d0pameen** [comment]
> 
> 
> Hello,
> I noticed that my Bloodhound threw a "No data returned from query" error when trying to run the "Find all domain admins" sample query on the sample database.
> While trying to figure out what the problem was, I stumbled upon the fact that I couldn't even show single notes.
> The Query Debug mode revealed, that the attribute "objectid" is "undefined".
> 
> Comparing with the data in neo4j, I noticed that there is no attribute "objectid", but "objectsid".
> 
> Hope this helps with fixing.
> 
> Cheers

Been struggling with this issue, glad to know you solved it. can you tell me which files to change and its location please.

**Comment by Brian-Hanrahan** [comment]
@d0pameen see my prior post above :-)

**Comment by d0pameen** [comment]
> @d0pameen see my prior post above :-)

Thank you Brian. I was not able to find BDCreator.py.

Sorry, i am new here, may be missing something which may be very basic.

Can you point me to the location i can find it and change.

Thanks in advace.

**Comment by Brian-Hanrahan** [comment]
@d0pameen Ahh - my mistake. I did not mention it is part of BloodHound-Tools (https://github.com/BloodHoundAD/BloodHound-Tools) in ~/BloodHound-Tools/DBCreator.py

**Comment by d0pameen** [comment]
Thank you so very much Brian.

I was doing HTB labs and extracted have some .json with extracted from
bloodhound-python..

in my process, i didnt have to use the DBCreator.py. what am i messing up
here?

**Comment by FallenHero66** [comment]
Hey d0pameen
Data extracted with the correct version of sharphound or other bloodhound tools which are compatible with this version will integrate fine into bloodhound
It's just the sample DB that is not yet updated

Cheers

**Comment by d0pameen** [comment]
> 
> 
> Hey d0pameen
> Data extracted with the correct version of sharphound or other bloodhound tools which are compatible with this version will integrate fine into bloodhound
> It's just the sample DB that is not yet updated
> 
> Cheers

Thank you for the reply FallenHero66!

1. Tried running directly from kali using bloodhound-python command..
2. Tried running from the git clone repo.. /bloodhound.py

both of the above give json.. both version of json has objectid, instead of objectsid.. 

i replaced manually to see if it help, NO.. still i get "No data returned from the query" and the map is shown without any connections.

Note: i also tried running 'bloodhound --no-sandbox' from kali default and from the git clone repo.. same results

**Comment by FallenHero66** [comment]
So if I understand correctly, you're scanning a network in HTB, and want to inspect the outcome in Bloodhound?

If so, I would suggest loading Sharphound3 onto a windows machine inside the HTB network, as this will definitely generate a compatible database
SharpHound is included in this repository btw

Kind of off-topic: (since I'm doing the Offshore pro lab with a few colleagues), which pro lab are you doing, if I may ask?

**Comment by d0pameen** [comment]
I am actually preparing for my OSCP.. im all over the places. Doing HTB
randomly with unique skill requirements and when i get bored, jump on to
TryHackMe, then Kioptrix.

On to the issue:

Im scanning a domain controller using bloodhound-python, this generates
.json for me.

I have to upload this on to bloodhound.

Typically this should give maps, for me shows none.. i click on an entry
and it goes blank and none of the queries work. This is specific to while
following the walkthrough for Pathfinder lab.

**Comment by cnotin** [comment]
According to https://github.com/BloodHoundAD/BloodHound/issues/322#issuecomment-613638482 the sample DB was updated to version 3 format. The issue can be closed?
