### ISSUE TITLE
Ingestor LDAP connection check fails when using alternate creds

### ISSUE THREAD

**Issue by blahdeblahde** [BloodHoundAD/BloodHound#299]
When I run 
 .\SharpHound.exe --outputdirectory "C:\Temp\" --ldapusername "username" --ldappassword "password" -v true --disablekerberossigning --CollectionMethod All --Domain our.domain

I get:
[+] Creating Schema map for domain OUR.DOMAIN using path CN=Schema,CN=Configuration,DC=OUR,DC=DOMAIN
LDAP Connection Test Failed. Check if you're in a domain context!

but when I run
.\SharpHound.exe --outputdirectory "C:\Temp" -v true --disablekerberossigning --CollectionMethod All --Domain our.domain

It successfully runs

**Comment by rvazarkar** [comment]
That generally means your ldap credentials aren't correct. If SharpHound is working without the credentials, then you should run it that way instead.

Your username should be prefixed with the domain. TESTLAB\username
