### ISSUE TITLE
Malware Found on the Repo

### ISSUE THREAD

**Issue by Wilgg** [BloodHoundAD/BloodHound#310]
**Did someone infect the Repo ?**

![bloodhound malware capture](https://user-images.githubusercontent.com/61794619/75896815-a12ab700-5e05-11ea-9087-3ac0eb7c12ff.PNG)

![Old Bloodhound malware](https://user-images.githubusercontent.com/61794619/75896816-a12ab700-5e05-11ea-9531-c50f887b22fc.PNG)

**Comment by rvazarkar** [comment]
AV has been detecting BloodHound as malware for a while, despite our efforts to the otherwise. There's nothing malicious, and you can always review the code yourself if you feel uncertain.
