### ISSUE TITLE
[Documentation request]: Wiki documentation for JSON-format not updated with SharpHound3

### ISSUE THREAD

**Issue by CasperGN** [BloodHoundAD/BloodHound#311]
Hi! 
The documentation of the JSON output at the [wiki](https://github.com/BloodHoundAD/BloodHound/wiki/BloodHound-JSON-Format) does not seem to be up to date with the newer format that SharpHound3 dumps / BloodHound requires.
I'm currently building a python dumping tool and up-to-date documentation would be very helpful when mapping the output into the JSON object BloodHound requires to draw relationships.

Fx. the Users object is documented as:
```json
{
    "users": [{
        "Name": "ADMINISTRATOR@TESTLAB.LOCAL",
        "PrimaryGroup": "DOMAIN USERS@TESTLAB.LOCAL",
        "Properties": {
            "domain": "TESTLAB.LOCAL",
...
```
However the output i receive with SharpHound is as following:
```json
{
    "users": [{
        "Properties": {
            "highValue": false,
            "name": "ADMINISTRATOR@TESTLAB.LOCAL",
...
```

Thanks for the awesome toolsuite!

/ Casper

**Comment by rvazarkar** [comment]
Just fixed this

https://github.com/BloodHoundAD/BloodHound/wiki/BloodHound-JSON-Format
