### ISSUE TITLE
JSON Data Upload failure

### ISSUE THREAD

**Issue by trashpanda21** [BloodHoundAD/BloodHound#312]
Team,

Not able to upload the JSON data files after running Sharphound. 

The files are not recognized on either our Windows or Linux deployment. The Linux deployment itself doesn't face the ingested file as unrecognized issue, however the data is not loading.

We're running Neo4, Bloodhound3, and Sharphound3.

Noticed others mentioning similar problems on a closed issue, [254](https://github.com/BloodHoundAD/BloodHound/issues/254). 

Please advise, great work. 

![Screen Shot 2020-03-11 at 6 11 26 PM](https://user-images.githubusercontent.com/53443534/76472647-2e50ab80-63c4-11ea-8625-0ec83dc4a2c8.png)

**Comment by rvazarkar** [comment]
Did data collection complete successfully? Was the collector terminated early? Were the files in a zip file, or were they just standalone when the run finished, assuming you used default options. If SharpHound didn't complete successfully, the data is incomplete, and it won't upload.

**Comment by trashpanda21** [comment]
Rohan, closing this. Looks like the operation was indeed getting terminated early, stable run properly yielded the intended results.

Thanks for the prompt response, awesome.
