### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by djwhite1177** [BloodHoundAD/BloodHound#313]
Upon launching bloodhound the following errors are throwing:

DeprecationWarning: buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

This is thrown for node:3415.

This seems to have an effect on the queries against a full database. Essentially nothing loads. Will there be a fix for this anytime soon?

**Comment by rvazarkar** [comment]
This issue has nothing to do with queries not loading. The error has been consistent for about a year with no negative effects. 

If queries aren't working there's a different underlying cause.

**Comment by djwhite1177** [comment]
I've updated to 3.0.3 and I'm still not getting any queries to run successfully. The pre-built queries also return back no data.

Is there something I can provide that can help in resolving this issue? Am I the only one experiencing this?

**Comment by rvazarkar** [comment]
Is your data collected using a 3.0 data collector?

**Comment by djwhite1177** [comment]
I'm using Sharphound.ps1...so...yes?

**Comment by zaoific** [comment]
I am having a similar issue. So far I have not ingested any data, only used the sample database and the database generator. But whenever I start up BloodHound, I get "No Data Returned from Query" and a blank screen. I can get nodes to appear by clicking on certain prebuilt queries, but when I click on any of the nodes none of the info about them ever populates. I have attached screenshots for reference. I have tried this on Linux and Windows with the same results.

![NodeInfo](https://user-images.githubusercontent.com/63107238/78365050-2085e480-7584-11ea-827b-69888ec7e903.png)
![NoData](https://user-images.githubusercontent.com/63107238/78365032-19f76d00-7584-11ea-9fe0-66c6fc6a9e91.png)

**Comment by chr0n1k** [comment]
I am also facing the same issues:

![image](https://user-images.githubusercontent.com/30057970/78778687-56700200-79a4-11ea-9e42-1b9d665355b3.png)

**Comment by zaoific** [comment]
If using data from the sample database or from the database generator, the data format is not compatible with the newest version of Bloodhound. I have since gotten everything working by using Badblood to create a sample domain and running Sharphound.

**Comment by rvazarkar** [comment]
The db creator and the example db have been updated. This should no longer be an issue
