### ISSUE TITLE
Parsing RemoteDesktopUsers from sharphound to Bloodhound

### ISSUE THREAD

**Issue by simo995d** [BloodHoundAD/BloodHound#315]
Below is a smaller snippet from the OUs file, where a RemoteDesktopUsers relation is present.
To my understanding it describes the relation that the group (RedactedGroupSID) can rdp to the computer (RedactedComputerSID).
When loading this OUs file into bloodhound, the relation does not exists. In comparison we see a similar structure for the LocalAdmin relation in the below snippet, which is correctly loaded into bloodhound.

```
[...]
"ChildOus": [],
"Computers": [
	"RedactedComputerSID"
],
"DcomUsers": [],
"Links": [
	{
		"Guid": "RedactedGuid",
		"IsEnforced": false
	}
],
"LocalAdmins": [
	{
		"MemberId": "RedactedGroudSID",
		"MemberType": "Group"
	}
],
"ObjectIdentifier": "RedactedObjectID",
"PSRemoteUsers": [],
"Properties": {
	"blocksinheritance": false,
	"description": null,
	"distinguishedname": "OU=XX,OU=XX,OU=XX,OU=XX,OU=XX,DC=XX,DC=XX,DC=XX",
	"domain": "RedactedDomainName",
	"highvalue": false,
	"name": "RedactedName",
	"objectid": "RedactedObjectID"
},
"RemoteDesktopUsers": [
	{
		"MemberId": "RedactedGroupSID",
		"MemberType": "Group"
	}
],
"Users": []
[…]
```

I am not sure if this is a mistake in the parser between Sharphound and Bloodhound, or if I misunderstand the data.

**Comment by rvazarkar** [comment]
This was definitely an issue. Fixed in https://github.com/BloodHoundAD/BloodHound/commit/2332c2ca89a8d018c296859f82fb56f569c457e8
