### ISSUE TITLE
Bloodhound in Web Browser?

### ISSUE THREAD

**Issue by basketas** [BloodHoundAD/BloodHound#317]
Hi, 
is there anyway to get the GUI in web browser, other than running it as an EXE as it is currently released?

**Comment by rvazarkar** [comment]
This isn't possible currently as we depend on some functions in Electron

**Comment by fastlorenzo** [comment]
I'd love to have that option as well, it would be nice to be able to integrate it in [RedELK](https://github.com/outflanknl/RedELK)!
Any hints on the Electron functions you rely on?
