### ISSUE TITLE
False positive in ACL-based attack paths

### ISSUE THREAD

**Issue by Qazeer** [BloodHoundAD/BloodHound#318]
Hello,

BloodHound (version 3.0.3) does not seem to take into account the `PropagationFlags` when determining ACL-based attack paths.  If the `PropagationFlags` of the ACL is set to `InheritOnly`, the ACE "is propagated only to child objects" and does not grant privileges on the object the ACL is applied to.

This may lead to false positives in some attack paths.

Best regards,
Qazeer.

**Comment by rvazarkar** [comment]
This has definitely been fixed since this issue was opened
