### ISSUE TITLE
`Custom query` feature request

### ISSUE THREAD

**Issue by Lz1y** [BloodHoundAD/BloodHound#320]
I want to write a custom query to find computers in specified OU, but many `OU` have a same named! Like `Desktop User` or what. But I notice that first query only could return a name String to second query via `$result`. So could you append a feature to make first query return other var like `ObjectId`? 

Example:
```
        {
            "name": "Find computers in specificed OU",
            "queryList": [
                {
                    "final": false,
                    "title": "Select a OU...",
                    "query": "MATCH (n:OU) RETURN n.name ORDER BY n.name DESC"
                },
                {
                    "final": true,
                    "query": "MATCH p=(o:OU {name: $result})-[r:Contains*1..]->(n:Computer) RETURN p",
                    "allowCollapse": true,
                    "endNode": "{}"
                }
            ]
        }
```

**Comment by rvazarkar** [comment]
This is already possible using the current prebuilt query mechanism. If you need help still, comment on or reopen this issue.
