### ISSUE TITLE
GPO processing doesn't interpret GpoStatus correctly.

### ISSUE THREAD

**Issue by s3c** [BloodHoundAD/BloodHound#321]
I'm currently getting a false positive because the property controlling whether a GPO is applied to a user/computer, isn't being interpreted correctly. This property is controlled by the Apply-Group-Policy extended right permission, and I believe it's called GpoStatus.

For example, I have a badly configured GPO listed as being applied to a number of users and hosts. The GpoStatus is marked as only being applied to users. Bloodhound thus lists viable chains to both users and computers, but in practice only the users link is valid.

The neo4j entry for the GPO below:

```
{
  "name": "GPO_NAME@DOMAIN.FOREST.COM",
  "highvalue": false,
  "distinguishedname": "CN={XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX},CN=Policies,CN=System, DC=domain,DC=forest,DC=com",
  "objectid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "domain": "domain.forest.com",
  "gpcpath": "\\domain.forest.com\sysvol\domain.forest.com\Policies\{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}"
}
```

Thus when viewing the GPO within the GUI, it shows a pivot for "Computer Objects", which are not valid.

**Comment by rvazarkar** [comment]
If you control the GPO object, you should be able to modify the GPOStatus to enable your attack path. 

If that's not correct, feel free to re-open this issue for more discussion
