### ISSUE TITLE
Interface refusing to render any queries (An error occurred in the graph query)

### ISSUE THREAD

**Issue by ZephrFish** [BloodHoundAD/BloodHound#322]
I ran sharphound against a domain today and it completed however when importing into bloodhound none of the queries work. When attempting to view any object within the GUI it just crashes and errors out with `Expected parameter(s): objectid`.

- Bloodhound Version: 3.0.3
- Sharphound version 3

Command run: `.\SharpHound.exe --ZipFileName  C:\Users\Zephr\Desktop\blood.zip --Jitter 2 --stealth --ldapusername USER--ldappassword PASS --skipportscan -v`

**Comment by rvazarkar** [comment]
Are you using a new database? Or is this a previous database you're adding data too

**Comment by ZephrFish** [comment]
New database, new install for this engagement

**Comment by chr0n1k** [comment]
Also facing the same problems and running with similar setup

**BH v 3.0.3
Sharphound.exe v3**

![image](https://user-images.githubusercontent.com/30057970/78781832-a2717580-79a9-11ea-8fbd-a7111d3303d3.png)

And this is using a fresh generation of sample data using **DBCreator.py** 

Also noted a warning when starting up BH:

![image](https://user-images.githubusercontent.com/30057970/78781982-e795a780-79a9-11ea-93be-4b188662a5f2.png)

**Comment by ccsplit** [comment]
I've resolved the issue locally by running: `grep -r objectid src -l | xargs perl -pi -e "s/objectid/objectsid/g"` and then rebuilding the application with `npm run {win,linux}build`. Not sure if there is a difference in the SharpIngestor's data and https://github.com/fox-it/BloodHound.py as that is where I retrieved my data from.

**Comment by rvazarkar** [comment]
The DBCreator is not compatible with 3.0 and neither is the sample database.

Changing to objectsid will 100 percent break your install when you have
good data as that parameter is no longer our index

**Comment by rvazarkar** [comment]
Both the dbcreator and the sample db have been updated to 3.0.
