### ISSUE TITLE
Sharphound blowing up virustotal

### ISSUE THREAD

**Issue by 45x2** [BloodHoundAD/BloodHound#323]
![Sharphound_virustotal](https://user-images.githubusercontent.com/64410835/80365049-a77e6200-888f-11ea-8c9e-a694b0e42ef2.jpg)

**Comment by andyrobbins** [comment]
This is expected. SharpHound has been flagged by AV for quite some time now. If you are on the red team side and want to bypass AV, there are many great AV bypass resources out there. In general, staying memory-resident and doing basic string replacement when building SharpHound from source will bypass most of these signatures. If you're on the blue side, get an AV exception put in place for SharpHound.

**Comment by 45x2** [comment]
No possible way I'd ever get an exemption for this, nor would I ever even consider asking for one.

**Comment by andyrobbins** [comment]
In that case I would recommend trying some AV evasion techniques to get SharpHound running without getting caught by AV.
