### ISSUE TITLE
No exception handling for trying to write in read-only dir

### ISSUE THREAD

**Issue by jmoosdijk** [BloodHoundAD/BloodHound#333]
The latest version of sharphound doesn't seem to correctly catch the exception of trying to write in a read-only directory, whereas older versions of sharphound did.

Example below:
![C1_win10-x64-1](https://user-images.githubusercontent.com/15887879/83154297-40f39a80-a100-11ea-9962-e15ce35fea6e.png)

**Comment by rvazarkar** [comment]
This shouldn't be an issue in SharpHound3
