### ISSUE TITLE
Requiring TLS on Bolt causes login to hang

### ISSUE THREAD

**Issue by 2XXE-SRA** [BloodHoundAD/BloodHound#335]
If you configure a certificate for the Bolt connector and enforce TLS by setting the "tls_level" property 
 to "REQUIRED" (https://neo4j.com/docs/operations-manual/current/configuration/connectors/#connectors-configuration-options), the UI will appear to hang on the login screen. BloodHound seems to be making an unencrypted request to check if the Bolt connection is available, which causes a SecurityException to be thrown by Neo4j:

> ERROR [o.n.b.t.p.ProtocolHandshaker] Fatal error occurred during protocol handshaking: [id: 0x54bf1233, L:/0:0:0:0:0:0:0:1:7687 - R:/0:0:0:0:0:0:0:1:58978] An unencrypted connection attempt was made where encryption is required.
java.lang.SecurityException: An unencrypted connection attempt was made where encryption is required.

However, the UI continues to display the spinning circle making it appear like its still loading.

**Comment by leonwear** [comment]
I am also seeing this issue.

`ERROR [o.n.b.t.p.ProtocolHandshaker] Fatal error occurred during protocol handshaking: [id: 0x0e4b1405, L:/[ipv6]:7687 - R:/[ipv6]:18184] An unencrypted connection attempt was made where encryption is required.`

Maybe this was fixed previously (https://github.com/BloodHoundAD/BloodHound/issues/72) and has reoccurred with a subsequent Neo4j release?

Thanks.

**Comment by The1WhoPrtNocks** [comment]
I am also having this issue

**Comment by kiranghanwat-ams** [comment]
Same here again.
Within cluster of 3 nodes, I am getting this on 1 node.
Is there any solution for this issue?

**Comment by rvazarkar** [comment]
If this is still an issue, feel free to reopen this
