### ISSUE TITLE
BloodHoundExample.db Documentation

### ISSUE THREAD

**Issue by Canuck317** [BloodHoundAD/BloodHound#336]
I may just be unable to find it, but it appears the documentation for getting neo4j to recognize the example BloodHound database was lost in the move from Wiki to ReadTheDocs.

I've been trying to get it up and running, having similar issues to this old closed issue from 2019. When I try following the links to startup instructions the poster mentions, I get redirected to ReadTheDocs, which does not appear to have steps to setting up the example database.

https://github.com/BloodHoundAD/BloodHound/issues/229

**Comment by Canuck317** [comment]
I did get it figured and and was embarrassed at how simple it was...but documentation would have save me a couple hours...

**Comment by Cyb3rWard0g** [comment]
Hey @Canuck317 would you mind sharing what the fix was on your end? Thank you in advance!

**Comment by Canuck317** [comment]
> Hey @Canuck317 would you mind sharing what the fix was on your end? Thank you in advance!

Copy the BloodHoundExample.db folder into your default data folder. You can see this in the text readout when you launch neo4j, or by pulling up the config file.  For me, the config file was in /usr/share/neo4j/conf, and I had to put the BloodHound.db folder under /usr/share/neo4j/data/databases. Note that although my default data folder was /usr/share/neo4j/data, the actual databases were in another subfolder called 'databases'. 

Next open up the neo4j.conf file. Right near the beginning is a line for dbms.active_database. Uncomment it, and set it to point to BloodhoundExample.db.  You should then be able to start up (or restart) neo4j and bloodhound and see the example database.

**Comment by curi0usJack** [comment]
For any that might come across this issue thinking, like I was, that you need to copy the BloodHoundExampleDB.db directory over to the neo4j data/databases directory in order for BH to work properly, I just learned from the BH team that that isn't the case and never has been. Install neo4j, change the default creds (neo4j:neo4j) at http://localhost:7474, then login to BH and the schema/constraint magic happens on its own.

If you really are trying to see the sample data from the example database, here are the steps I went through to make it happen (Ubuntu 20.04 / neo4j 4.0.7). 

1. Copy BloodHoundExampleDB.db to /var/lib/neo4j/data/databases
2. Set default_database & allow_upgrade in neo4j.conf
3. sudo neo4j console. It will create a new bloodhoundexampledb.db directory in /var/lib/neo4j/data/databases, even though you already copied BloodHoundExampleDB.db over. Not sure why this happens.
4. Stop neo4j
5. cp -r the files from BloodHoundExampleDB.db to bloodhoundexampledb.db
6. Delete /var/lib/neo4j/data/transactions/bloodhoundexampledb.db
7. Start neo4j
8. Browse to localhost:7474 and change password.
9. Login to BloodHound. You should see all the sample data. 

Another note, I'm probably doing this all wrong and not the proper "neo4j" way. The above steps did work for me though. Someone with more knowledge come along and correct this please. :-)

**Comment by rvazarkar** [comment]
We'll be removing the example DB in favor of a cloud hosted one going forward.

**Comment by noraj** [comment]
BloodHoundExample.db removed in 4.1.0 https://github.com/BloodHoundAD/BloodHound/compare/4.0.3...4.1.0
