### ISSUE TITLE
"Find Shortest Path to Domain Admins" query results in blank screen 

### ISSUE THREAD

**Issue by Obsene** [BloodHoundAD/BloodHound#337]
Hello.

When I run the "Find Shortest Path to Domain Admins" query, Bloodhound says "Querying Database" for a few minutes, and then hangs with a blank screen.

I'm able to run other lighter queries and can run "Find Shortest Path to Domain Admins" on small domains without issue.

The domain in question has:

495,000 users
1800 computers
500,000 groups
30,706,309 Relationships

Is this to large for neo4j and Bloodhound?

Thanks!

**Comment by madmantm** [comment]
Hello, if this helps i'm having the same issues, and i have tried the following troubleshooting steps without any luck.

However, i have the following stacktrace in the bloodhound client.

```
(node:23715) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:23715) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

<--- Last few GCs --->

[23715:0x24fe97b47000]   624136 ms: Scavenge 2045.1 (2052.6) -> 2043.3 (2052.6) MB, 771.8 / 0.0 ms  (average mu = 0.290, current mu = 0.060) allocation failure 
[23715:0x24fe97b47000]   624147 ms: Scavenge 2045.2 (2052.6) -> 2043.3 (2052.9) MB, 5.3 / 0.0 ms  (average mu = 0.290, current mu = 0.060) allocation failure 
[23715:0x24fe97b47000]   625074 ms: Mark-sweep 2045.2 (2052.9) -> 2043.4 (2052.9) MB, 921.4 / 0.3 ms  (average mu = 0.374, current mu = 0.469) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x55cbbb2ad7b9]
    1: StubFrame [pc: 0x55cbbb22d9cd]
Security context: 0x3714ef5d18d1 <String[#7]: file://>
    2: decode [0x1debfd2cf3e1] [file:///home/user1/Downloads/BloodHound-linux-x64/resources/app/dist/bundle.js:~96] [pc=0xd369b38d3fb](this=0x079a63febcf1 <l map = 0x1489b30a1fb9>,0x3ad2b98a5c19 <DataView map = 0x33958b4830b9>,0x0d32b9a004d1 <undefined>)
    3: decode [0x79a63fd7879] [file:///home/user1/...


```


The database entries are about the same of Obsene. 

1) ajusted my neo4j config with the following parameters
```
dbms.memory.heap.initial_size=23900m
dbms.memory.heap.max_size=23900m
dbms.memory.pagecache.size=19600m
dbms.tx_state.max_off_heap_memory=8g
```

2) warm-up the database in Bloodhound, did not yield result in better results.

Thanks again for the project and if you require more info, please do tell.

**Comment by rvazarkar** [comment]
The issue isn't on the neo4j side, it appears to be on the UI side. Looks like the query is just too large for the UI to handle. We added warnings in newer versions about this issue, but there's not much we can do to solve this unfortunately.
