### ISSUE TITLE
Version 2 data not compatible with bloodhound 3

### ISSUE THREAD

**Issue by weligama** [BloodHoundAD/BloodHound#339]
I first run this command in CMD: C:\> SharpHound.exe --CollectionMethod Session --Loop

Then I upload the collected data into the Bloodhound GUI in Linux. 

An error message occurred: (version 2 data not compatible with bloodhound 3)

I am using the following versions:

Latest sharphound 3.0 
Latest neo4j 3.5.3
Latest bloodhound GUI 3.0.4

How to solve this issue?

**Comment by xeen3d** [comment]
Hi
here same I use Mac OS X to run BloofHopund and try SharpHound from master repository 
and get same message and the imported Files are not usable the query don't work.
best

Andre

**Comment by cnotin** [comment]
The message is rather explicit, are you sure that you collected the data with SharpHound v3?
According to the code, there should be a "version" tag somewhere in the generated JSON file: you should ensure that the files you got have it!
https://github.com/BloodHoundAD/BloodHound/blob/f6b5306867db5c3edc8e5975f68e9bf6f9093618/src/components/Menu/MenuContainer.jsx#L272

**Comment by cnotin** [comment]
Seeing that you use the --Loop option, also make sure that the file you're uploading was properly written on disk and that the current loop iteration is finished

**Comment by weligama** [comment]
I am using the Ingestor downloaded from this link: https://github.com/BloodHoundAD/BloodHound/tree/master/Ingestors

Do you have another suggestion for running a loop session? 

When I run this  SharpHound by simply running the binary itself, i do not get the error message.

 I will run the loop session and control the version tag in the generated JSON file.

**Comment by cnotin** [comment]
Ok so you're certainly using Sharphound 3.
I'm not used to using loop... I don't know if it creates a new file at each iteration or if it appends in the same and in that case I suppose you need to stop it to have a properly formatted and complete file.
Check what's inside yours and tell us!

**Comment by cnotin** [comment]
By reading the doc, I think you need to have to wait until the whole loop collection is finished to have a usable file

**Comment by rvazarkar** [comment]
If you did loop collection, you need to unzip the zip file that has all the other zips in it first

**Comment by weligama** [comment]
**@cnotin,** yes it creates a new file after each loops, and then it waits for another 30 sec to continue the loop. When the default run time ends after 2 hours it collects all the zip files and put it in one large zip. When I upload this large zip it trigger the alert/error message: "version 2 data not compatible with bloodhound 3". I investigated the"version" tag in the generated JSON files - attached is the outcome:

_"meta":{"count":XXXX,"type":"computers","version":3}} in the JSON computer file 
"meta":{"count":3,"type":"groups","version":3}} in the JSON _groups file_ 

**@rvazarkar,** when unzipping the large zip file I get around 24 zip files. Each of them contains two JSON scripts files called(_computers & _groups). To put the record straight, should I upload each of those files into the BloodHound GUI?

**Comment by rvazarkar** [comment]
You can upload the smaller zip files that are inside the bigger one. You cant upload the single zip file that contains the other zips

**Comment by weligama** [comment]
**@rvazarkar,** When I upload the smaller zip files, some information are missing in the Database Info in the GUI - concerning Users and ACLs, can you explain why? 

Each of the smaller files only contains two JSON script files: (_computers & _groups). 

Whereas, by running only SharpHound.exe file the binary itself, no error message occurs and the zip file creates more JSON scripts(_groups, _computers, _domains,_gpos, _ous, _users) than the loop.

**Comment by rvazarkar** [comment]
-c Session --Loop

You're doing loop collection for sessions. Therefore, the only thing you're going to get from that loop is sessions, which is in the computer file. The group file is created to ensure some well known groups are added to the output, nothing more. When you run it without arguments, it collects everything and it doesn't loop. So you get the rest of the data.

**Comment by Dangotei** [comment]
I have installed the Bloodhound. I am trying to run the shar
![Snag_58f10d71](https://user-images.githubusercontent.com/92122987/136458450-75b37419-e51d-49e8-92fb-cfd05e5a338a.png)
phound.exe but keep getting an error message. Please what do I do?
![image](https://user-images.githubusercontent.com/92122987/136458368-ec54effa-8b86-48ab-8d89-89af71d7e5ca.png)
