### ISSUE TITLE
Potential syntax errors in 2 Pre-Built Analytics Queries

### ISSUE THREAD

**Issue by Bal0u** [BloodHoundAD/BloodHound#341]
Hi,

First of all, thanks for this amazing tool that changed our way to do internal pentest!

I've just downloaded the last version (v3.0.4) and I'm encountering the following errors when submitting some Pre-Built Analytics Queries:

**Find All Paths from Domain Users to High Value Targets**

```
Invalid input 'A': expected whitespace, comment, ',', USING, WHERE, FROM GRAPH, USE GRAPH, CONSTRUCT, LOAD CSV, START, MATCH, UNWIND, MERGE, CREATE UNIQUE, CREATE, SET, DELETE, REMOVE, FOREACH, WITH, CALL, RETURN, UNION, ';' or end of input (line 1, column 77 (offset: 76))
"MATCH p=shortestPath((g:Group {name:$result})-[*1..]->(n {highvalue:true})) AND g<>n return p"
```

**Find all other Rights Domain Users shouldn’t have**

```
The semantics of using colon in the separation of alternative relationship types in conjunction with
the use of variable binding, inlined property predicates, or variable length is no longer supported.
Please separate the relationships types using `:A|B|C` instead (line 1, column 18 (offset: 17))
"MATCH p=(m:Group)-[r:Owns|:WriteDacl|:GenericAll|:WriteOwner|:ExecuteDCOM|:GenericWrite|:AllowedToDelegate|:ForceChangePassword]->(n:Computer) WHERE m.objectid ENDS WITH '-513' RETURN p"
```

I'm using the last version of Neo4j (4.0.6). I tried to play a bit with the queries but I'm lacking of patience and couldn't find where is the error. I think it may be just some minor typos in the queries that you would be able to spot fairly quickly.

Cheers,
                  ^

**Comment by rvazarkar** [comment]
The first one is fixed in rolling release, and I just pushed a fix for the second one. It should be compiled into rolling shortly.

**Comment by Bal0u** [comment]
Awesome! thanks a lot!
