### ISSUE TITLE
Neo4j Version Clarification

### ISSUE THREAD

**Issue by mike-boya** [BloodHoundAD/BloodHound#344]
The documentation for macOS instructs the user to download neo4j Community Edition Server:

```
1. Download the macOS version of neo4j Community Edition Server from https://neo4j.com/download-center/#community
```

However, there are now multiple versions available. The newest version, Neo4j Community Edition 4.1.0 (released 23 June 2020), threw an error:

```
./neo4j console
Unable to find any JVMs matching version "11".
```

Version 3.5.19 (released 15 June 2020) worked as expected. It may be worth updating the documentation to account for multiple versions.

If this is a duplicate of #343 feel free to close. They appear related but considering it would not run I wanted to mention it.

**Comment by PehDeh** [comment]
Neo4j Community Edition 4.0.6 also works, i stuck with 4.1.0 too...

**Comment by rvazarkar** [comment]
We should have no problems running on any modern version now
