### ISSUE TITLE
Feature request: Back and forward buttons for queries and / or query list

### ISSUE THREAD

**Issue by TealAlex** [BloodHoundAD/BloodHound#346]
Hi,

currently there is no way to get the last query back in the raw query window. There is a back button which shows the **result** of the last query but **not the raw query**. Further, there is no forward button to get the very last query back, when you hit the back button before.  

It would be great if there was a back and forward button which would show the result as well as the raw query. On top of that it would be great if there was a history of queries to look at.

Best regards
Alex

**Comment by rvazarkar** [comment]
I've fixed it so the raw query is properly updated. I think for now, I'm going to leave out the forward button. Might Add it in when I get a bit more time
