### ISSUE TITLE
Session collection doesn't seem to work

### ISSUE THREAD

**Issue by vineethsai** [BloodHoundAD/BloodHound#349]
I downloaded the latest script but for some reason, Session collection did not work. I was having this issue with the previous version as well (about a month ago)

Here's what happened:
![image](https://user-images.githubusercontent.com/23186197/87749730-560ab280-c7ae-11ea-9a2a-0cd747ed3b94.png)

![image](https://user-images.githubusercontent.com/23186197/87749779-789ccb80-c7ae-11ea-8925-02183786306b.png)

These are the only files that were in the zip file.
![image](https://user-images.githubusercontent.com/23186197/87749863-b26dd200-c7ae-11ea-8085-2cc6c6d5ee5c.png)

Any help? suggestions?

**Comment by andyrobbins** [comment]
Sessions are part of the computers.json file: https://bloodhound.readthedocs.io/en/latest/further-reading/json.html#computers

When you import these json files, do you see the number session in your database info tab go up?

**Comment by vineethsai** [comment]
Hey Andy! I think it worked. I had to remove and reinstall Bloodhound. It was a weird error! Thanks a bunch!
