### ISSUE TITLE
Incompatible with Neo4j 4.X?

### ISSUE THREAD

**Issue by CaledoniaProject** [BloodHoundAD/BloodHound#350]
Multiple errors observed while running predefined queries

![screenshot 2020-07-18 at 9 41 16 AM](https://user-images.githubusercontent.com/1357701/87841836-ef36e780-c8da-11ea-8ab4-9c4de02dc43a.jpg)

![screenshot 2020-07-18 at 9 41 44 AM](https://user-images.githubusercontent.com/1357701/87841838-f2ca6e80-c8da-11ea-9994-78a509f1fecb.jpg)

**Comment by rvazarkar** [comment]
The next update will address this. The code has already been pushed to master, so if you want to use rolling release you can
