### ISSUE TITLE
[Question] A Question about the new type "Base"

### ISSUE THREAD

**Issue by DerAlexx** [BloodHoundAD/BloodHound#352]
What criterias do bloodhound take in consideration to make an instance a "Base"?

 So how do i know from the JSON-Output that something is a "Base"-Instance?

Thanks for your support

**Comment by rvazarkar** [comment]
Everything is a Base instance if its a node. We use this to deduplicate nodes by making sure we have a consistent label to match on. We append additional labels on top of the base label such as User or Group.
