### ISSUE TITLE
Sharphound Incompatible with Windows version

### ISSUE THREAD

**Issue by aehurls** [BloodHoundAD/BloodHound#358]
I have Bloodhound running on a Server 2019 node and when I try to run Sharphound, I'm getting the following error:

SharpHound.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

![image](https://user-images.githubusercontent.com/26417320/89419371-95834980-d731-11ea-85e5-e75f8bd2d847.png)

![image](https://user-images.githubusercontent.com/26417320/89467759-7b1f8f00-d776-11ea-89a2-0e697d4e3941.png)

![image](https://user-images.githubusercontent.com/26417320/89419509-b8156280-d731-11ea-9efd-adfef0b7d10b.png)

Did I just miss something, or just forgetting how to read?

I'm using this version posted: https://github.com/BloodHoundAD/BloodHound/tree/master/Ingestors

**Comment by FallenHero66** [comment]
Hi,

got the same problem with the new version of Sharphound, the old one works fine

**Comment by FallenHero66** [comment]
Hey,

did you check the integrity of the sharphound.exe? We accidentally downloaded the html page via wget, which resulted in a .exe which contained HTML-Code

**Comment by rvazarkar** [comment]
This generally indicates an incomplete or wrong download. Just try downloading again. Its also possible AV ate something
