### ISSUE TITLE
Mac BloodHound still loading

### ISSUE THREAD

**Issue by FuckAllWorld** [BloodHoundAD/BloodHound#359]
BloodHound-darwin-x64.zip

the Login UI continues to display the spinning circle making it appear like its still loading.

can't login 

windows is normal

**Comment by rvazarkar** [comment]
Check if theres errors in the console with ctrl + shift + i. Is this still an issue?

**Comment by yellow-starburst** [comment]
@FuckAllWorld This issue has been resolved and fixed since august 2020. Could you please close?
