### ISSUE TITLE
'Node properties' and 'Extra Properties' are not updated correctly

### ISSUE THREAD

**Issue by magnusstubman** [BloodHoundAD/BloodHound#360]
BH version: 3.0.5
### Description

Dataset has following example OUs:
```
OU=dogs,OU=europe,DC=blah,DC=com
OU=dogs,OU=asia,DC=blah,DC=com
OU=dogs,OU=africa,DC=blah,DC=com
```
When searching in BH for dogs@blah.com, the autocomplete list shows all three results:
```
dogs@blah.com
dogs@blah.com
dogs@blah.com
```
If I click the first result, and then click the node shown, the 'Extra Properties' shows the correct DN: OU=dogs,OU=**europe**,DC=blah,DC=com

But, if I then click the search bar (which still contains the string `dogs@blah.com`) and select the second result, and then click on the node shown, I was expecting to see the correct DN shown as OU=dogs,OU=**asia**,DC=blah,DC=com, but this doesn't happen. Instead, it still shows OU=dogs,OU=**europe**,DC=blah,DC=com.

Note, that this applies onlhy to 'Node Properties' and 'Extra Properties'. 'Affecting GPOs' and 'Descending Objects' are still updated correctly.

### Workaround

Between browsing each node, search for any user account, and click on it, then the second OU can be clicked in the auto-complete list and will show correct DN.

**Comment by jtothef** [comment]
I've created a pull request that should address this issue - https://github.com/BloodHoundAD/BloodHound/pull/365

**Comment by rvazarkar** [comment]
Accepted the PR. Closing this issue
