### ISSUE TITLE
Bloodhound loads to white screen

### ISSUE THREAD

**Issue by nerdyninny** [BloodHoundAD/BloodHound#362]
I am running the latest version of neo4j 4.1.1, bloodhound 3.0.5, and java jdk 11.0.8.  I followed the instructions, tried both the pre-compiled binaries and the alternative npm builds and I keep getting a white screen whenever I launched Bloodhound.

Ctrl-R doesn't do anything
Ctrl-Shift-I shows only this error:
![image](https://user-images.githubusercontent.com/59848054/91366143-c9451280-e7b7-11ea-96e1-9544877d9e30.png)

Any tips appreciated!

**Comment by nerdyninny** [comment]
Nevermind.  Figured it out.  Bloodhound doesn't like either being in a subdirectory, or the special character '#' in the path.

**Comment by rkovaci** [comment]
Hi nerdyninny - Could you please detail a bit more your resolution? I'm running bloodhound from kali repos (so doesn't really matter which directory it's ran from) and I'm still getting the below. Looks like a number of people are getting the same on different platforms - https://github.com/BloodHoundAD/BloodHound/issues/397
![2020-12-04_10-24](https://user-images.githubusercontent.com/24431437/101152378-e42aec80-361a-11eb-9910-8e82cf20bc83.png)

**Comment by corsch** [comment]
Did you got a more detailed answer? I'm facing the same issue on Kali Linux.

**Comment by corsch** [comment]
A workaround for me was not using the provided binaries but compiling it by myself.
(https://bloodhound.readthedocs.io/en/latest/installation/linux.html#alternative-build-the-bloodhound-gui)

Could our issue be related to this commit?
4a0cd81

**Comment by rvazarkar** [comment]
Should be fixed in rolling. Will tag a new release soon
