### ISSUE TITLE
Suggested Documentation Edit: MACOS

### ISSUE THREAD

**Issue by JustinJayL** [BloodHoundAD/BloodHound#364]
Referring to [the documention for MACOS](https://bloodhound.readthedocs.io/en/latest/installation/osx.html), the instructions say to install neo4j community edition. I and several others have mistakenly installed the version of neo4j off of brew, and went through much consternation before discovering the issue.

I recognize that this was my fault for not reading the instructions properly, however, I thought it may be beneficial to highlight step 1 of the installation instructions, or to add a warning about installing neo4j from brew at the top.

**Comment by rvazarkar** [comment]
Fixed in https://github.com/BloodHoundAD/BloodHound/commit/de6c27583c7f9a6233ce66ce6470e4509f93a591
