### ISSUE TITLE
Ingestor Failes on CollectionMethod SessionLoop

### ISSUE THREAD

**Issue by 1nkotb** [BloodHoundAD/BloodHound#368]
Hi there,
I am finally updating the ingestor and server at the latest version and have some issues trying to get data in.
Using powershell on Windows Server.
Below I posting the query and error message:

**Query**

 Invoke-BloodHound -CollectionMethod Default, Group, LocalAdmin, DCOM, RDP, ComputerOnly, Trusts, ACL, ObjectProps, Container, DCOnly, SessionLoop  -LoopDelay 120 -MaxLoopTime 0d0h0m59s -Stealth -NoZip -JsonFolder C:\Export\Upload\$date

**Error message:**
Initializing SharpHound at 1:22 PM on 9/8/2020
----------------------------------------------
Failed to parse Collection Method SessionLoop.

**Comment by andyrobbins** [comment]
Hi there,

Thanks for opening the issue. You'll actually want to change your syntax a little bit as the "SessionLoop" collection method no longer exists. Instead, you have the -Loop parameter which can be used in several different ways:

https://bloodhound.readthedocs.io/en/latest/data-collection/sharphound-all-flags.html#loop-options

Your command includes some redundancies as well - "ComputerOnly" captures "LocalAdmin,DCOM,RDP", while "Default" captures almost everything else.

You should be able to change your command to this:

`Invoke-BloodHound -CollectionMethod Default -Loop -LoopInterval 120 -LoopDuration 0:0:59 -Stealth -NoZip -JsonFolder C:\Export\Upload$date`

The BloodHound documentation also includes lots of other info about SharpHound: https://bloodhound.readthedocs.io/en/latest/data-collection/sharphound.html

Hope this helps

Andy

**Comment by 1nkotb** [comment]
The loop part is working and I will close this for now.
Thanks for your help!
