### ISSUE TITLE
NoZIP flag is ignored and Json files are zipped in powershell

### ISSUE THREAD

**Issue by 1nkotb** [BloodHoundAD/BloodHound#369]
I am using the following 

`Invoke-BloodHound -CollectionMethod Default -Loop -LoopInterval 120 -LoopDuration 0:0:59  -NoZip -OutputDirectory C:\Export\Upload\$date`

Based on this command, I am getting the following;
 

1. sharphound runs and creates the following json files 
                - computers
                - domains
                - gpos
                - groups
                - ous
                - users
What I had here in BH 2.2 was also the sessions file, which I find really good, as I am running BH on a 24h basis.

2. Even if the -NoZip flag is on, the script still creates the zip archive and throws all files in there.  

An extra note, the .PARAMETER CollectionMethod shows some of the deprecated values, as Session, SessionLoop and maybe others, but I was not able to identify yet.

**Comment by cnotin** [comment]
Hey @1nkotb there's now a PR you can try :)
I think it's better to report issues in SharpHound in its own repo https://github.com/BloodHoundAD/SharpHound3/issues

**Comment by rvazarkar** [comment]
PR merged so this should be fixed
