### ISSUE TITLE
failed to commit changes to dconf

### ISSUE THREAD

**Issue by JerboaGobi** [BloodHoundAD/BloodHound#371]
5.4.0-kali3-amd64

BloodHound Version: 3.0.5-0kali1
Neo4j Version: 4.0.6

(BloodHound:16832): dconf-WARNING **: 14:38:36.167: failed to commit changes to dconf: The connection is closed

Any assistance would be apprecaited.

**Comment by rvazarkar** [comment]
Is BloodHound not opening? What behavior are you seeing?

**Comment by Wadshah** [comment]
Same :(
