### ISSUE TITLE
Suggestion: add more fields similar to "userpassword"

### ISSUE THREAD

**Issue by cnotin** [BloodHoundAD/BloodHound#380]
BloodHound now collects and display the "userpassword" field which sometimes contain the user's password (or derivative).
See 39756c3abc386ad7443e37a4449f9af5d793840d by @andyrobbins 

I suggest adding those fields too:
* unixuserpassword
* unicodepwd
* msSFU30Password

Source: https://www.blackhillsinfosec.com/domain-goodness-learned-love-ad-explorer/

If you like it I can suggest PRs in BloodHound and SharpHound

**Comment by rvazarkar** [comment]
Do those fields actually contain usable data generally? I dont think I've ever seen them actually have set values

**Comment by cnotin** [comment]
Looks like it exists in some environments according to the article
![image](https://user-images.githubusercontent.com/550823/100001001-bc3dbc80-2dc2-11eb-9f78-cb8d25ed99c8.png)
(here it's hex and ascii encoded)
> On a surprising number of tests, we find one or more of these fields are populated with ACTUAL passwords.

I can't say I've seen them used that often (or actually never for some)
