### ISSUE TITLE
Suggestion: cache results for "transitive..." queries to allow faster switch from obtaining the number of results to showing the results

### ISSUE THREAD

**Issue by cnotin** [BloodHoundAD/BloodHound#387]
Here is my scenario:

1. I select an object, and I click on the little "play" button next to "Transitive object control"
2. The query runs for a while...
3. I finally get the number of results :)
4. Now I want to see the results on the display with the discovered paths so I click on the number that just appeared
5. The query runs again! And takes time again... :'(

My suggestion would be to cache the results from the first query in order to be able to show the number of results, and then immediately the paths themselves if the user clicks on the number

**Comment by rvazarkar** [comment]
This is going to be too expensive in a few different ways to implement for now
