### ISSUE TITLE
Bloodhound 4.0 - Not showing analysis queries

### ISSUE THREAD

**Issue by yellow-starburst** [BloodHoundAD/BloodHound#393]

**Comment by skorov** [comment]
Same here. Some more info on what's missing.

![image](https://user-images.githubusercontent.com/15148733/99862275-31579900-2bed-11eb-9585-f48d6bc62e29.png)

Thanks! <3

**Comment by Maleick** [comment]
I was in the middle of purging all of my Bloodhound files because I thought it was me.

Good to know.

**Comment by yellow-starburst** [comment]
Status update - Rohan has said that he will be pushing an updated release around Monday.

**Comment by ebfe90** [comment]
I have the same problem

**Comment by mubix** [comment]
Same issue here

**Comment by vysecurity** [comment]
Same issue on windows

**Comment by GanbaruTobi** [comment]
same =(

**Comment by johnjohnsp1** [comment]
confirm, same issue on osx with latest prebuilt releases for osx (bigsur)

**Comment by yellow-starburst** [comment]
Released in version 4.0.1
