### ISSUE TITLE
Azure Attack Path does not work

### ISSUE THREAD

**Issue by weligama** [BloodHoundAD/BloodHound#394]
Using the latest SharpHound.exe. 
https://github.com/BloodHoundAD/BloodHound/tree/master/Collectors 

Running the latest version of neo4j 

Running bloodhound 3.5

I am using Linux debian to run the Bloodhound and neo4j DB.

**Comment by cnotin** [comment]
Hello, please be more specific in how it "does not work", and explain what you used to collect what, and then what you did of the collected data :)

**Comment by weligama** [comment]
I am using the latest sharphound.exe, which I execute in CMD to collect data. When I upload the zipped file into the Bloodhound, which I have installed in Linux Debian I can open the file without any issues. I am not able to see the new nodes, e.g.  tenants, Azure users, Azure security groups, Apps, Service Principals, Subscriptions, Resource Groups, Virtual Machines, Devices and Key Vaults.

**Comment by jopels** [comment]
You need to run SharpHound.exe for all date related to AD on premise and AzureHound.ps1 for all data related to Azure. Then import both zip files.

**Comment by weligama** [comment]
Alright, Thanks. 

The latest release of BloodHound-darwin-x64.zip, how do I update it in Linux? 
https://github.com/BloodHoundAD/BloodHound/releases

**Comment by cnotin** [comment]
Darwin is for Mac, looks like the Linux version isn't there yet...

**Comment by weligama** [comment]
Well, I will wait patiently for that update though. Hope it is around the corner.

**Comment by weligama** [comment]
@cnotin , now that the release og BloodHound 4.0.1, is out  how do I update it in Linux directly from github or in linux terminal?

**Comment by cnotin** [comment]
Have you at least tried to Google this error message? It will certainly help you...
anyway,yyou fdon't need to download the source code, cf. https://github.com/BloodHoundAD/BloodHound#downloading-bloodhound-binaries

**Comment by weligama** [comment]
Without any luck to find the solution, Yes. 

I suppose when I update the collectors the bloodhound will be updated to 4.0?

**Comment by cnotin** [comment]
The message is explicit in itself. You tried a git clone which creates a repository and downloads the content in it. Except you already have a folder with this name 😉 you need a different command if you want to update an existing git repo (and you shouldn't need sudo)

The collectors (sharphound and azurehound) are downloaded separately from the GUI (bloodhound)
see the doc https://bloodhound.readthedocs.io/en/latest/index.html
https://github.com/BloodHoundAD/BloodHound/tree/master/Collectors

**Comment by weligama** [comment]
What is the command to update an existing git repo? 

I have seen those docs before. I am aware of that, however I am not sure how to make it work.  
I can download the sharphound.exe file but I am not able to download the azurehound.ps1, only in raw format is possible.

**Comment by weligama** [comment]
I am not able to find a proper command to update an existing git repo from linux terminal? 

I have seen those docs before, however I am not sure how to make it work.  
I can download the sharphound.exe file but I am not able to download the azurehound.ps1, only in raw format is possible.

**Comment by cnotin** [comment]
First Google result for "git repository update" is https://stackoverflow.com/questions/1443210/updating-a-local-repository-with-changes-from-a-github-repository and "git pull" is indeed the answer!

The raw version is indeed the way to go, then you can copy paste content or save as from your browser

**Comment by weligama** [comment]
Actually I already visited that link and tried out the examples. 
Thanks you for your patience and reply.
