### ISSUE TITLE
imports of larger json files getting stuck at 24%

### ISSUE THREAD

**Issue by DracoLlasa** [BloodHoundAD/BloodHound#395]
When trying to import my scan results for a rather large environment, the largest json that completed is about 2.8MB, the next largest file is 4.4MB and it, along with all others larger will start loading and then get to 24% and just sit there

![image](https://user-images.githubusercontent.com/5413944/99969588-b3200180-2d68-11eb-9746-2103c2b44e05.png)

i closed out the gui, and tried loading the files individually instead of through just the 1 zip file the collector creates and the results are the same. All the smaller files load fine, any larger ones get stuck. All of them that get stuck, do so at the same 24% point

**Comment by rvazarkar** [comment]
Are there any errors in the console? You can open it with Ctrl + Shift + I

**Comment by DracoLlasa** [comment]
yes, when it stops at 24%, it has this error in the console
```
TypeError: Cannot read property 'toUpperCase' of null
    at azkvpermissions (bundle.js:87)
    at bundle.js:87
    at u (bundle.js:69)
    at Generator._invoke (bundle.js:69)
    at Generator.forEach.e.<computed> [as next] (bundle.js:69)
    at YA (bundle.js:87)
    at a (bundle.js:87)
```

**Comment by ElGatoL0c0** [comment]
I had the same issue with the azrgpermissions.json file outputted from the Azurehound scan; I took a look at the code and the .json and found this error occurs when there are results with a null value for RoleName (null can't be converted to uppercase).

Ex:
"RoleName":  null,

There is probably a better way to handle this; but, as a workaround to get the file uploaded into the DB, I did a search and replace on the output file.

"RoleName":  null,

to

"RoleName":  "Unknown Name",

**Comment by DracoLlasa** [comment]
i checked this and none of the "RoleName" vales are null in my files (that i could see)
there are other values that are null, such as GroupOnPremID and ControllerOnPremID
but im not sure its connected with mine because, just as example, the file with ControllerOnPremID value as null processes fine

**Comment by rvazarkar** [comment]
Closing this in hopes that its fixed in some of the newer commits
