### ISSUE TITLE
Search results in blank screen, making Bloodhound unusable.

### ISSUE THREAD

**Issue by s3c** [BloodHoundAD/BloodHound#397]
When using the search bar in Bloodhound 4 on Windows x64, the screen goes white and no controls are visible. I've confirmed that Bloodhound 3.0.5 works as expected. Any way I could help debug this?

![image](https://user-images.githubusercontent.com/1725894/100072403-dddf8800-2e44-11eb-9666-7ffd94d71a00.png)

**Comment by jopels** [comment]
Maybe related to this issue? #362

**Comment by s3c** [comment]
Confirmed this with the new Linux version, as well as from a colleague.

**Comment by eaneatfruit** [comment]
Same problem on MacOS Big Sur.
![Screen Shot 2020-11-26 at 5 27 05 AM](https://user-images.githubusercontent.com/16026025/100339598-0f249900-2fa8-11eb-9c8b-80a7bb93277f.png)

**Comment by vonjk** [comment]
big sur
![image](https://user-images.githubusercontent.com/30076142/100424349-6e79ca80-30c8-11eb-8bc8-3598f0880892.png)

**Comment by J005** [comment]
Same problem with Linux Mint

**Comment by rkovaci** [comment]
same on Kali Linux (5.8.0-kali2-amd64)
![2020-12-04_10-24](https://user-images.githubusercontent.com/24431437/101152554-29e7b500-361b-11eb-893b-803d371f4bad.png)
There's a mention of it here too - https://github.com/BloodHoundAD/BloodHound/issues/362 but still didn't find a resolution yet.

**Comment by menewol** [comment]
The solution provided in #362 [0] actually worked for me. Copied the Bloodhound Folder to C:\ and removed the hypens (renamed to BloodHound). 

The search functionality does work again now (running Win10 obv., Build 2004 - with a remote Neo4j server, running BloodHound as Administrator)

[0]: https://github.com/BloodHoundAD/BloodHound/issues/362#issuecomment-681185377

**Comment by init5-msft** [comment]
> The solution provided in #362 <<0>> actually worked for me. Copied the Bloodhound Folder to C:\ and removed the hypens (renamed to BloodHound).
> 
> The search functionality does work again now (running Win10 obv., Build 2004 - with a remote Neo4j server, running BloodHound as Administrator)
> 
> <<0>> [#362 (comment)](https://github.com/BloodHoundAD/BloodHound/issues/362#issuecomment-681185377)

I tried that and it didn't work. The path I'm running from is C:\BloodHound and I still have the issue.

**Comment by menewol** [comment]
i recreated it once again and funnily enough i was only able to do one proper search. trying to go for a second search issued the ssame blank screen as mentioned initially in the issue.

**Comment by corsch** [comment]
I have the same issue on Kali Linux. First search is sometimes working, but on the second search the screen gets white for sure.

**Comment by robantonucci-bf** [comment]
is there any workaround for this yet?

**Comment by corsch** [comment]
A workaround for me was not using the provided binaries but compiling it by myself.
(https://bloodhound.readthedocs.io/en/latest/installation/linux.html#alternative-build-the-bloodhound-gui)

Could our issue be related to this commit?
https://github.com/BloodHoundAD/BloodHound/commit/4a0cd8196a9bad1380aedbd6c1cc65f56a5ffca9

**Comment by eaneatfruit** [comment]
Can confirm when compiling on MacOS Big Sur, that the error does not occur. https://bloodhound.readthedocs.io/en/latest/installation/osx.html

**Comment by rvazarkar** [comment]
This should be fixed in rolling release as of about a week ago. I'll be tagging a new release soon with some bugfixes and updates

**Comment by s3c** [comment]
Can we have precompiled binaries please?

**Comment by yellow-starburst** [comment]
@s3c I have verified that this issue has been remediated. Could you please close?

**Comment by s3c** [comment]
Confirmed working, thanks folks.

**Comment by jaysharma786** [comment]
Can anyone let me know what is remediation for Resolving this issue
