### ISSUE TITLE
AzureHound Powershell issue

### ISSUE THREAD

**Issue by Multipatch** [BloodHoundAD/BloodHound#398]
Running AzureHound.ps1 keeps hanging on for hours and hours without any progress...

$AuthAdminsRights | ForEach-Object {
        $Coll += $_
    }

**Comment by itpro-tips** [comment]
Hello,
Can you try the PR to see if it's better : https://github.com/BloodHoundAD/AzureHound/pull/1

**Comment by rvazarkar** [comment]
Closing this for now. Reopen if its still a problem, however we have updates to AzureHound coming in the future which will improve performance
