### ISSUE TITLE
Format of JSON files

### ISSUE THREAD

**Issue by timrwwatson** [BloodHoundAD/BloodHound#399]
Hi,
I'm currently trying to work out what the format of the JSON files needs to be for BloodHound but working through the documentation the examples when I put them into files and try to upload them either return invalid file or incompatible errors.

Is there a place I can get example JSON files or better yet pipe the sample data produced in the sample program to JSON. As I do not currently have access/to produce my own via SharpHound.

**Comment by icysun** [comment]
i think you use the version of bloodhound  is wrong.

the version of SharpHound must be right

**Comment by rvazarkar** [comment]
Formats will be updated on the wiki soon. The canonical formats will always be found here going forwards: https://github.com/BloodHoundAD/SharpHoundCommon/tree/master/src/CommonLib/OutputTypes
