### ISSUE TITLE
Linux release assets missing for BloodHound 4.0

### ISSUE THREAD

**Issue by djcater** [BloodHoundAD/BloodHound#400]
Thanks for the new release.

However I noticed that compared to the previous releases, the pre-built Linux assets are missing: https://github.com/BloodHoundAD/BloodHound/releases

**Comment by yellow-starburst** [comment]
Version 4.0.1 has been released and contains linux release assets. 
Could you close?

**Comment by weligama** [comment]
Ho do you update it from Linux terminal?

**Comment by djcater** [comment]
Version 4.0.1 looks like it has a Linux release. Closing this. Thanks.
