### ISSUE TITLE
Azure Import problems

### ISSUE THREAD

**Issue by yellow-starburst** [BloodHoundAD/BloodHound#401]
**Won’t work:**
1. Uploading the Zip fails 
2. Uploading all the files at once fails

**Works but the data is incomplete:** 
3. Uploading all files individually works 
I noticed that the overall database statistics are extremely low. Taking a deeper dive, I noticed that there may be a max group size of 100.
So each azure group only shows 100 users.

**Comment by yellow-starburst** [comment]
Looping in another data import issue #395

**Comment by hkelley** [comment]
I am also having Azure import issues.   I cannot import the file at all - no error in the UI.  I have tried starting with a cleared-out DB and with one that has our on-prem objects already loaded.

My 20201120040726-azurecollection.zip is 35,741,422 bytes.

**Comment by yellow-starburst** [comment]
Part of the problem has been remediated - https://github.com/BloodHoundAD/AzureHound/commit/0f627a252fc2a4104617846110becadc7325c3ee

**Comment by yellow-starburst** [comment]
Still a problem in 4.0.2

**Comment by rvazarkar** [comment]
If you open the console using Ctrl + Shift + I, there should be errors there. If you can grab those errors we can take a look at this

**Comment by yellow-starburst** [comment]
I'm just going to trust that you fixed it and close
