### ISSUE TITLE
Bloodhound 4.0 - doesn’t upload all data  

### ISSUE THREAD

**Issue by yellow-starburst** [BloodHoundAD/BloodHound#402]
Version - bloodhound 4.0 built from source
In the search bar, I look up 2 users:
```
User 1 
User 2
```
User 1 will show up and I can select the node.
User 2 does not load in the search bar or as a node.
**Troubleshooting steps:**
1. I spun up bloodhound 3 and could not locate the user2 node. 
2. Using the bloodhound 3 console, I uploaded the same bloodhound data I uploaded to bloodhound 4.0.
3. Within bloodhound 3 Search through the data again and located user2.

**Conclusion:** 
This may relate to bloodhound 4.0’s uploading function - #401 .
The data is not uploading to the neo4j database properly.

**Comment by rvazarkar** [comment]
Fixed in vnext

**Comment by yellow-starburst** [comment]
Thanks @rvazarkar !!! So glad you found some time despite your likely busy schedule!

**Comment by noraj** [comment]
In 4.0.3 nothing uploads (either by uploading all json or one at a time), it shows _Upload Complete_ but is at 0% and nothing was imported. This behavior was fixed in 4.1.0.
