### ISSUE TITLE
Bloodhound 4.0 principle.name colision

### ISSUE THREAD

**Issue by r3vcrowley** [BloodHoundAD/BloodHound#408]
Sharphound and Azurehound seem to create collisions in the user.name field in the neo4j database. 

Steps to reproduce:
1) Create a dump with sharphound and upload via the bloodhound. This sets the object.name field to the SAMACCOUNTNAME sharphound receives from ldap. Note that the email property sharphound ingests is case sensitive and not processed by sharphound, resulting in whatever AD kicks out uploaded to neo4j. For example "Firstname.Lastname@Domain.com". 
2) Create an Azurehound dump and upload it via the bloodhound GUI. Once uploaded, all objects that are found in azure will have their object.name field set to azure's email. This property seems to follow upper case format. for example "FIRATNAME.LASTNAME@DOMAIN.COM"

This behavior results in breaking functionality in the bloodhound GUI such as search complete.

**Comment by yellow-starburst** [comment]
Can verify that I have the same issue

**Comment by rvazarkar** [comment]
Should be fixed in https://github.com/BloodHoundAD/BloodHound
