### ISSUE TITLE
Cross platform AzureHound

### ISSUE THREAD

**Issue by rhysjtevans** [BloodHoundAD/BloodHound#409]
Hey guys,
Great work! I've not managed to try out the Azure Hound yet - mac user!
Is there any plans for a cross-platform collector? e.g. Dotnet core? PowerShell Core? Golang?

**Comment by rvazarkar** [comment]
No plans as of now, but that might change at some point in the future. We're pretty married to the windows world for data collection right now, largely because that's where our expertise lies
