### ISSUE TITLE
Addition/Update to Wiki Page for Getting Started > Sample Database

### ISSUE THREAD

**Issue by leesoh** [BloodHoundAD/BloodHound#41]
Sample Database
To configure the sample database on Linux:
1. Copy BloodHoundExampleDB.graphdb to <NEO4J DIRECTORY>/data/databases.
2. Edit <NEO4J DIRECTORY>/conf/neo4j.conf and change the "`#dbms.active_database=graph.db`" line to "`dbms.active_database=BloodHoundExampleDB.graphdb`".
3. Start neo4j (`<NEO4J DIRECTORY>/bin/neo4j start`).
4. Log on to https://127.0.0.1:7474 (or wherever your Neo4j instance lives) using the default credentials of `neo4j\neo4j`. Enter new credentials when prompted.
5. Run the BloodHound binary you downloaded earlier, and use the credentials you chose in step 4.

**Comment by thatrez** [comment]
The only binary is see is deploy.sh, when I run it I get prompted with "enter host password for user" I enter the neo4j password and then nothing happens, it just brings me back to the bash prompt.

**Comment by leesoh** [comment]
@thatrez You can find it over here: https://github.com/adaptivethreat/BloodHound/releases

**Comment by lsuto** [comment]
Im able to import the the database but when running the binary nothing happens. IE Step 5 above makes no sense.

**Comment by leesoh** [comment]
@lsuto So you get everything else done, you can log into the database fine using 127.0.0.1:7474, but when you run the BloodHound binary, you can't log in, or it just doesn't launch?

**Comment by leesoh** [comment]
@lsuto That's odd. No idea what you're running into. Perhaps @andyrobbins @HarmJ0y or @rvazarkar can offer some insight.

**Comment by n03lx** [comment]
Thanks for the extra configuration information, hopefully this gets updated on the Wiki!!

I've got everything setup but get a failed login using both the default neo4j\neo4j and the neo4j\BloodHound credentials. Anyone have an idea?

**Comment by leesoh** [comment]
I'm going to assume you're using Linux.

The very first time you log on to neo4j it's going to let you log in with neo4j/neo4j and make you choose a new password. That's your password for (I think) every database you open with it.

The BloodHound password isn't valid for Linux, not sure why. Were you able to log on to neo4j initially? Before you moved the BloodHound database?

**Comment by n03lx** [comment]
Yes I'm using Linux x64. I'm not able to login using the neo4j password the first time.

**Comment by leesoh** [comment]
Ahh, I see. I updated the procedure. Hopefully it's a bit clearer now.

**Comment by lsuto** [comment]
I am able to view the Bloodhound database via the browser. I was able to change password from the default and everything, but when I try to run ./Bloodhound from the command line nothing happens. I have everything running in a Ubuntu 16.04 vm and I am connecting to a remote ESXI server via ssh. Could that be it?

**Comment by leesoh** [comment]
The BloodHound binary requires a GUI. Perhaps try downloading the appropriate build for the OS you're using a web browser on and connecting that way?

**Comment by bbb31** [comment]
New user to Bloodhound here; I am also using Linux and found that setup was pretty rough:
- `neo4j` will not auth on initial install until after you've changed the default password; I had to login via http first and change the password.
- After I got in I seen nothing (the default `neo4j` database); so had to google to find this post on setting up the example data.

**Comment by MrBenChung** [comment]
Same issue but on Mac OSX.

- Can see that database is loaded from within the Bloodhound app but you don't "see anything" actually if you click on one of the relationships from the neo4j browser you can see the raw cypher query which you can paste into the Bloodhound query box at the bottom of the app.
- Also if you start attempting to search in the search bar top left that will show you results and from there you can navigate to more complex patterns and relationships.

**Comment by yellow-starburst** [comment]
@leesoh  can you close?

**Comment by leesoh** [comment]
Sure!
