### ISSUE TITLE
no sessions?

### ISSUE THREAD

**Issue by icysun** [BloodHoundAD/BloodHound#411]
hi, i have a problem that  i run the command:
" SharpHound.exe --CollectionMethod Group,LocalGroup,RDP,DCOM,GPOLocalGroup,Session,ObjectProps,Trusts,ACL,Container"
but,have no sessions?

**Comment by icysun** [comment]
i use  the latest build of SharpHound "https://github.com/BloodHoundAD/BloodHound/blob/master/Collectors/SharpHound.exe"

**Comment by yellow-starburst** [comment]
+1 
I had the same problem! Had to use an old version of sharphound and worked fine. Definitely a problem in the new sharphound

**Comment by rvazarkar** [comment]
I'll take a look, but basically nothing has changed in the 4.0 collector compared to 3.0

**Comment by yellow-starburst** [comment]
I had this issue for a few months. Around this commit - 
https://github.com/BloodHoundAD/SharpHound3/commit/83a2401c597cce4033ffa49406c8b1506a01d468

**Comment by icysun** [comment]
> I had this issue for a few months. Around this commit -
> [BloodHoundAD/SharpHound3@83a2401](https://github.com/BloodHoundAD/SharpHound3/commit/83a2401c597cce4033ffa49406c8b1506a01d468)

Have you solved the problem of having no sessions?

**Comment by yellow-starburst** [comment]
Yes I used an old version of sharphound. Still need to troubleshoot and verify which commit disrupted session collection.

**Comment by icysun** [comment]
> d

thanks,i uesd old version of sharphound too.
but the new version of bloodhound can't import the results type of json.

**Comment by rvazarkar** [comment]
I'm a bit confused here. What exactly do you mean by no sessions? No sessions file in the output? No sessions in the results? Are you using Session looping to gather info?

**Comment by yellow-starburst** [comment]
I tested with the newest sharphound and sessions were loaded. This issue has been verified to be fixed.  
@rvazarkar Could you please delete?
