### ISSUE TITLE
File Path Too Long within the Release ZIP for 4.0.1

### ISSUE THREAD

**Issue by tehpr0** [BloodHoundAD/BloodHound#416]
Is this an important file within the zip files of the release?

![image](https://user-images.githubusercontent.com/5042600/102390690-a3dd4e00-3fcc-11eb-889f-5f7e5f25d2ed.png)

**Comment by yellow-starburst** [comment]
Yeah I always wandered about that. I’ve skipped and haven’t noticed any negative outcomes.

**Comment by rvazarkar** [comment]
Provided everything is working, I wouldn't mess with it, but if you want, there's a registry setting you can use:

https://stackoverflow.com/questions/38023046/node-js-path-too-long-windows-10
