### ISSUE TITLE
collectionmethod all doesn't appear to work correctly

### ISSUE THREAD

**Issue by johnmccash** [BloodHoundAD/BloodHound#423]
When I run either sharphound.exe or sharphound.ps1 with the '-collectionmethod all' option, the resultant zip archive only contains computers.json, groups.json, and users.json. However, if I run it with '-collectionmethod container', it does collect an ous.json file. When I run it with '-collectionmethod all', it DOES output the line "Resolved Collection Methods: Group, Sessions, LoggedOn, Trusts, ACL, ObjectProps, LocalGroups, SPNTargets, Container". Any idea what could be going on here? I'm not entirely certain what, if any, other json files I should be expecting. I'm testing with the 4.01 sharphound.exe, and with the most recent sharphound.ps1.

**Comment by rvazarkar** [comment]
I cant replicate this behavior. 
![image](https://user-images.githubusercontent.com/5720446/107269937-4ee01600-6a18-11eb-81a0-73d292cdfe57.png)
![image](https://user-images.githubusercontent.com/5720446/107269964-59021480-6a18-11eb-9dac-c5d806335c6e.png)

Using -c all, I'm getting all the files I expect

**Comment by johnmccash** [comment]
I'm retrying now with your exact syntax. Will let it run overnight, and see what's in the zip file in the morning.
John

**Comment by johnmccash** [comment]
Retried, with same results. One other thing though. For some reason sharphound -c all (using the 4.01 binary) seems to be causing the account I'm running it under to get locked out for multiple bad password attempts. Any idea why? And could this account for the failure to produce the other json files? If that's it, why did the various other options appear to work? I ran sharphound successfully with each of the other individual options, and output was produced each time.

**Comment by rvazarkar** [comment]
The internal workings of SharpHound uses a pipeline. The pipeline is built using the options specified in collectionmethods, so -c Session will run the same code as -c LocalGroup, Session when it runs session enumeration.

If account lockouts are being caused there's some sort of misconfiguration or security in place around that account, because I've yet to experience an account lockout from BloodHound after hundreds of runs

**Comment by yellow-starburst** [comment]
@johnmccash could you please close this issue?

**Comment by johnmccash** [comment]
Sorry. I've been incredibly busy. I'm retrying now using the new 4.0.2. With any luck, maybe I won't be able to replicate the behavior.
John

**Comment by johnmccash** [comment]
Sorry. I've been incredibly busy. I'm retrying now using the new 4.0.2. With any luck, maybe I won't be able to replicate the behavior.
John

**Comment by johnmccash** [comment]
I've retried, and still have the same problems. Not sure what's going on, but happy to help if someone wants me to troubleshoot. That said, I really can't post sharphound output publicly. I'm willing to email less sensitive bits directly, with the understanding that the data will be promptly destroyed after the troubleshooting is completed.

**Comment by aress31** [comment]
Same issue for me! See:

```
PS C:\Users\foo\Documents\Tools\AD\BloodHound-win32-x64\resources\app\Collectors> .\SharpHound.exe --domain 'foo.corp' --ldapusername 'foo' --ldappassword 'bar' --prettyjson -c "All,GPOLocalGroup" -v
----------------------------------------------
Initializing SharpHound at 17:31 on 23/08/2021
----------------------------------------------

Resolved Collection Methods: Group, Sessions, LoggedOn, Trusts, ACL, ObjectProps, LocalGroups, SPNTargets, Container, GPOLocalGroup
```

**Comment by rvazarkar** [comment]
Hopefully vNext will fix this issue.
