### ISSUE TITLE
Feature Request: Don't zoom edges and nodes, only space between

### ISSUE THREAD

**Issue by johnmccash** [BloodHoundAD/BloodHound#426]
When viewing a densely crowded graph, zooming is of limited utility, because the edges get wider and nodes get bigger. The primary function of zooming is (for me anyway) to get the objects farther apart for enhanced differentiation. This is made more difficult by their increasing size. I'd prefer if the nodes and edges didn't actually get wider when zooming.

**Comment by rvazarkar** [comment]
This isn't something we can control and unfortunately is a problem with the graph library we're using. We'll take a look at fixing this in the future if we can, but I'm going to close this for now
