### ISSUE TITLE
Issues when right clicking on Azure edges

### ISSUE THREAD

**Issue by johnmccash** [BloodHoundAD/BloodHound#427]
When right clicking on an AZContributor edge, and selecting 'Help', the 'info' text shown does not list the to/from nodes, which is inconsistent with display of older edges. Inclusion of the node information in the edge description helps immensely when examining an extremely busy graph, as you may not be able to pick out what node the edge connects to when there are many close together.

When right-clicking on an AZOwns edge, same as above.

Same for AZUserAccessAdministrator.

**When I right-click on an edge of type AZVMContributor, the entire Bloodhound GUI goes white, and I have to restart it. (I do not get the "? Help" pop-up at all.**

Note that I initially got to a point where such edges were shown by running a custom query: "Find all Privileged Service Principals"

**Comment by johnmccash** [comment]
I just verified that even in the rolling Bloodhound release, from 2/5/2021, when you right click on an AZVMContributor edge, and click the "?Help" link, the GUI goes all-white. But at least, now, you have to actually click the "?Help" link. Before, it did it immediately on the right click.

**Comment by rvazarkar** [comment]
Should be fixed in https://github.com/BloodHoundAD/BloodHound/commit/729a2943254d6cfab2945bf43a6257e98a4a9023

**Comment by johnmccash** [comment]
Does that include the missing data in the edge "Help" pop-up?
