### ISSUE TITLE
Feature Request: Allow Selection & Move of Subgraphs

### ISSUE THREAD

**Issue by johnmccash** [BloodHoundAD/BloodHound#429]
Another useful feature would be the ability to select/move all nodes and edges on one side of a specific edge (perhaps by adding 'select right subgraph', and 'select left subgraph' items to the right-click menu for edges?). This should provide the capability to quickly and easily break smaller related chunks of a large & complex graph out for more detailed reformatting & examination. A possible refinement of this might be to also provide a max depth parameter, so that only nodes within that distance in the indicated direction would be selected.

**Comment by rvazarkar** [comment]
I believe the library we're using supports this, but the maintainer blew away all the documentation making it extremely difficult to actually figure anything out. If we can figure out how to do this in the future, we'll implement it, but I'm going to close this for now.
