### ISSUE TITLE
Containers are missing - and so are attack paths

### ISSUE THREAD

**Issue by JonasBK** [BloodHoundAD/BloodHound#433]
It seems like there could be paths to DA through permissions directly on default containers (e.g. Users container) hidden from BloodHound. Lame example:
- User1 is a standard user but with full control (this object only) on Users container.
- User2 is a standard user but with full control on Domain Admins.
- User1 can add an ACE to the Users container that allow User1 to change the password of users in the Users container (i.e. User2) = path to DA.

If I'm right about this, I can create a pull request if you like. But I imagine you want to decide thing like whether to create a new label in neo4j or replace OU with a Container label and other stuff like that :)

**Comment by rvazarkar** [comment]
Will be fixed in vnext
