### ISSUE TITLE
Feature Request: Display AD Domain Controller replication paths

### ISSUE THREAD

**Issue by scstanton** [BloodHoundAD/BloodHound#434]
It would be a nice feature for BloodHound to be able to display the AD replication topology and intervals between sites/domain controllers.  I know this isn't directly related to attack path mapping but anything which helps enumerate and visualize the AD structure can be useful.

**Comment by rvazarkar** [comment]
After some discussion, this is outside the scope of what the project is attempting to accomplish. So I'm going to close this for now. Thank you for the suggestion!
