### ISSUE TITLE
Query returned no results

### ISSUE THREAD

**Issue by CrutzPan** [BloodHoundAD/BloodHound#438]
Dear BloodHound Team,

Currently i am facing the following issue:

After collecting data with Azure-Hound, if i import my data to my neo4j database i have the following problems:

1. The GUI is just a set of Nodes, but there are no Edges computed connecting those nodes.
2. If i do any query, the response is "the query returned no results".

How do i interpret this result? Does this simply mean that AzureHound was not able to gather enough data compute any Attack Vectors?

Best Regards

**Comment by yellow-starburst** [comment]
This is not a technical bloodhound issue. Please close this issue.

**Comment by rvazarkar** [comment]
Closing this issue for now. Reopen if needed

**Comment by behindblackwalls** [comment]
Can anyone explain this issue? "This is not a technical issue" isn't very helpful. I'm having a similar issue where the data is imported, I can make cypher queries in neo4j, but in bloodhound every query I make just returns no data.
