### ISSUE TITLE
sharphound.ps1:553 Error 

### ISSUE THREAD

**Issue by nicedevil007** [BloodHoundAD/BloodHound#441]
Heya getting this error:

![image](https://user-images.githubusercontent.com/17103076/113267213-5fa15f80-92d6-11eb-8dd2-0a58379c7df6.png)

Tryed to run it without AV software running. Still the same.

Downloaded the script a few minutes before.

**Comment by rvazarkar** [comment]
This is an internal error in sharphound being eaten by the powershell script. Going to hope its fixed in vnext and we can re-open later if needed
