### ISSUE TITLE
Releases page does not include link to Rolling Release

### ISSUE THREAD

**Issue by johnmccash** [BloodHoundAD/BloodHound#444]
Didn't the Releases page originally contain a link to the Rolling Release? I finally found this at [https://github.com/BloodHoundAD/BloodHound/releases/tag/BloodHound-Rolling](https://github.com/BloodHoundAD/BloodHound/releases/tag/BloodHound-Rolling), but the link was actually kind of hard to find.

**Comment by rvazarkar** [comment]
Its just on the second page. I'll have to find a way to rearrange the releases again
