### ISSUE TITLE
A JavaScript error occured in the main process when executing the BloodHound.exe

### ISSUE THREAD

**Issue by DennisOR** [BloodHoundAD/BloodHound#445]
![BloodHound 4 0 2 Error](https://user-images.githubusercontent.com/75069518/115376835-5584c980-a1cf-11eb-8c64-1935e3cbc846.JPG)

**Comment by Bakira-cyber** [comment]
I had the same issue, you have to disable your antivirus software which delete some important files.

**Comment by DennisOR** [comment]
I downloaded the BloodHound-win32-x64.zip on the actual server itself with NO AV running and then worked like a charm so thank you very much Bakira-cyber for pointing me in the right direction, it is much appreciated  :-)

**Comment by DennisOR** [comment]
Thanks to the comment from Bakira-cyber, my issue is solved :-)
