### ISSUE TITLE
Unable to connect with bolt+s:// or neo4j+s://

### ISSUE THREAD

**Issue by OffsecChuck** [BloodHoundAD/BloodHound#447]
Need the bloodhound interface to allow bolt+s:// or neo4j+s:// options. Currently it appends bolt:// to anything typed in the url bar stating the database exist (if valid). Upon clicking connect it gives an error of unknown database and has changed the url to some similar to bolt://bolt+s://localhost:7687

**From slack chat**
Is it possible to connect bloodhound to a bolt+s database on a remote server? Or a neo4j+s? I can't get it to connect because bloodhound keeps auto-appending bolt:// to the beginning of the connection string

cptjesus  10:46 AM
That's probably a remnant of when bolt was the only real way to connect

10:46
File a bug report and I'll take care of it in the next round of fixes

**Comment by rvazarkar** [comment]
Fixed in vnext

https://github.com/BloodHoundAD/BloodHound/commit/78e65c68e548a09145702293c503a98946aea57d
