### ISSUE TITLE
Feature Request: Change Node Label Display Property

### ISSUE THREAD

**Issue by y-peter** [BloodHoundAD/BloodHound#450]
Hello there. Is there a way to change the displayed Node Label? 
I am trying to pave my way through several hundred Azure Groups. For orientation purposes i want to change the displayed Label (Object ID) to the azname (DisplayName in .json). I can identify Group Names better than long IDs. Is this Possbile?

The Picture shows that Groups (and any other Objects) are displayed with ObjectID as label. 
![Screen Shot 2021-05-03 at 18 11 37](https://user-images.githubusercontent.com/46352014/116902631-a965c880-ac3b-11eb-8e00-ed3c31301820.png)

But i need it to look like this:
![Screen Shot 2021-05-03 at 18 11 37](https://user-images.githubusercontent.com/46352014/116903486-c2bb4480-ac3c-11eb-9f01-f805442b7eda.png)

**Comment by dirkjanm** [comment]
think this should be fixed by #459, can you check using the rolling release?

**Comment by y-peter** [comment]
It is fixed. Sorry for the delay. Thanks 👍
