### ISSUE TITLE
Feature Request: CLI Data Stats Tool

### ISSUE THREAD

**Issue by ptf569** [BloodHoundAD/BloodHound#455]
On a recent assessment I ran SharpHound.exe and dragged the zip into BH, that same was done by a colleague and it turned out that for some reason not all objects had entered into by DB.

Could a CLI tool be created to run against SH output data that could be used to verify the figures that should be expected in the DB Stats? Could help verify missing data when uploading to BH

Ta

**Comment by rvazarkar** [comment]
This would require a complete reimplementation of the ingest logic. I'd be happy to accept a community tool for this, but we're going to close this issue for now. 

That being said, we've made some updates to the ingest process in vnext to make it more robust
