### ISSUE TITLE
BloodHound 4.0.2 import bugs

### ISSUE THREAD

**Issue by pwnj0hn** [BloodHoundAD/BloodHound#458]
BloodHound failes to translate SID to name and find attack paths after importing to 4.0.2. Sometimes it works, but most often it does not. If I import using a 3.x version of BloodHound, all works. If opening 4.0.2 after closing 3.x, everything works fine here too.
I have tested on multiple computers, reinstalled BH, tested against multiple AD's. Same result.

I believe this has to be an import bug in 4.0.2.

**Comment by rvazarkar** [comment]
We've done a bunch of updates to import logic in vnext
