### ISSUE TITLE
*_domains.json not taken into account when feeding zip file

### ISSUE THREAD

**Issue by Hackndo** [BloodHoundAD/BloodHound#462]
Hey there,

I have some weird behavior with BloodHound **on Windows**: When I upload a ZIP file containing Sharphound output, it only unzips 5 out of 6 files inside the zip. The `domains.json` file is always missing. I tried and collect again, same with the new ZIP file. (It comes from `.\SharpHound.exe -c All` as domain admin on DC).

I added some debug info to check why the `domains.json` file is "dropped" someway, and it appears it is right after unzipping:

![image](https://user-images.githubusercontent.com/11051803/120293526-a525dd00-c2c5-11eb-9c33-b749b467a5e6.png)

![image](https://user-images.githubusercontent.com/11051803/120293550-a8b96400-c2c5-11eb-8672-34c009ccf49e.png)

When I unzip `domains.json` manually and feed it into BloodHound, it accepts it and now I have my domains objects in BloodHound.

![image](https://user-images.githubusercontent.com/11051803/120293566-abb45480-c2c5-11eb-8922-53d950aa92ea.png)

![image](https://user-images.githubusercontent.com/11051803/120293578-af47db80-c2c5-11eb-8cfe-b65570716179.png)

I tried and dug in the code to check what could happen, but couldn't find the bug. I even wrote a small `node.js` project to reproduce, but the `domains.json` file is found by `unzipper`.

```js
const unzipper = require('unzipper');
const fs = require('fs');
console.log('App started');

fs.createReadStream('C:\\Users\\RomainBENTZ\\Desktop\\20210601001846_BloodHound.zip')
  .pipe(unzipper.Parse())
  .on('entry', function (entry) {
  	console.log(entry.path);
  	entry.autodrain();
  });
console.log('App closed');
```
![image](https://user-images.githubusercontent.com/11051803/120293590-b242cc00-c2c5-11eb-9b46-80d0fb277301.png)

So I must say I'm quite stuck, as I have no idea why this happens. 

Additional information:
* Tried with last release
* Tried with compiled release with last patches
* On Windows 10 last version

If I'm on Linux, it works like a charm
![image](https://user-images.githubusercontent.com/11051803/120294841-e5398f80-c2c6-11eb-8490-eb21e9aabf80.png)

**Comment by ciyi** [comment]
I'm facing the exact same problem. I've tried it against different domains/environments and it always miss the domain information. I have to import domains.json manually.

I'm using:
Neo4j Community 4.2.2
BloodHound 4.0.2

Thanks!

**Comment by rvazarkar** [comment]
Fixed in vnext, was a bug in the zip library we're using
