### ISSUE TITLE
The futex facility returned an unexpected error code

### ISSUE THREAD

**Issue by bmilliron67** [BloodHoundAD/BloodHound#463]
Debian 10 x64
I have tried building from source as well as downloading the prepackaged binary. Both give the same error. No errors on compile only on run. I've also tried using older versions of the release binary. Those segfault.

**Comment by Liberator69** [comment]
Anyone have a clue on this? It's got me stumped and I'm trying to study for the OSCP.

**Comment by Liberator69** [comment]
Try installing as a non-root user. Got it to work by installing and running as the user account (Kali in this case).

**Comment by rvazarkar** [comment]
Closing this issue. Reopen if needed
