### ISSUE TITLE
No attack path from owned users to computers with ReadLAPSPassword edge in GUI

### ISSUE THREAD

**Issue by snovvcrash** [BloodHoundAD/BloodHound#467]
Hey there!

I have encountered an issue when an attack path from a user in this `LAPS Viewers` group to computers with `ReadLAPSPassword` ACL does not show up in the BloodHound GUI:

![1](https://user-images.githubusercontent.com/23141800/122606096-12d15780-d081-11eb-8ca4-950422e484a1.png)

While the same Cypher query works just fine from the neo4j console:

![2](https://user-images.githubusercontent.com/23141800/122600006-db11e200-d077-11eb-9dbd-33978c509180.png)

The query I'm using:

```
MATCH (n:User) MATCH (m:Computer) MATCH p=shortestPath((n)-[r:MemberOf|ReadLAPSPassword*1..]->(m)) WHERE n.owned RETURN p
```

I would like to know if it is that's an expected behavior. Thanks!

**Comment by rvazarkar** [comment]
If you look at the node, you'll see there's a 10 glyph on it. Right click
on the node and click expand.

**Comment by snovvcrash** [comment]
Yes, I know that. I was just looking for a way to show all the paths on a single screen.
Thanks, anyways, the issue may be closed.
