### ISSUE TITLE
 "Self-SID" is represented as individual node

### ISSUE THREAD

**Issue by fulc2um** [BloodHoundAD/BloodHound#468]
Active directory object with SID S-1-5-10 is represented as individual node, which probably should not be the case.
![Screenshot 2021-06-25 at 20 33 10](https://user-images.githubusercontent.com/75536280/123464281-4cf8a700-d5f5-11eb-9d12-62c9f565606b.png)

Bloodhound version installed: 4.0.2-kali1 
Info collected with bloodhound-python -c All

**Comment by rvazarkar** [comment]
SID is now properly filtered in vnext of SharpHound

https://github.com/BloodHoundAD/SharpHoundCommon/blob/d409649a03f7a69c120216f863b2f97a6e77db5c/src/CommonLib/Processors/ACLProcessor.cs#L473
