### ISSUE TITLE
Add the option of selecting a non-default database when starting Bloodhound

### ISSUE THREAD

**Issue by ss23** [BloodHoundAD/BloodHound#474]
Neo4j supports multiple databases at once. By default, Bloodhound seems to just use the default database name.

I may be just not seeing it, but I can't seem to see a way to change it to something other than the default. Having the option to change this would mean you could have multiple imported datasets working at once, with almost no extra code on the Bloodhound end.

**Comment by rvazarkar** [comment]
We only officially support neo4j community server currently which does not support multiple databases. If this changes in the future I'll take a look at adding support. Alternatively, I would be happy to accept a PR supporting this functionality
