### ISSUE TITLE
[RFF] Show nodes/relationship count

### ISSUE THREAD

**Issue by aress31** [BloodHoundAD/BloodHound#479]
The number of nodes/relationships returned by queries is already displayed in the neo4j console, but I think that it could be a good idea to display this information directly somewhere within the UI. This would include: 
- \# of computers
- \# of users
- etc.

**Comment by rvazarkar** [comment]
Its already shown in the Database Info panel.

![image](https://user-images.githubusercontent.com/5720446/149017817-3b106c54-0a3b-47e5-801f-7e461f66751d.png)
