### ISSUE TITLE
Invalid Username or Password in BloodHound GUI

### ISSUE THREAD

**Issue by TRSecurity** [BloodHoundAD/BloodHound#482]
When prompted to enter the password to connect to the default Neo4j DB with credentials reset to neo4j:neo4j I am receiving an error of invalid username or password. I have reset the password for the admin account multiple times with the set-initial-password but still am not able to authenticate through the BloodHound GUI.

**Comment by rvazarkar** [comment]
Closing this for now due to age. Reopen or open a new issue if the problem persists
