### ISSUE TITLE
BloodHound Hangs When Attempting to Authenticate to Newer Versions of Neo4j

### ISSUE THREAD

**Issue by subat0mik** [BloodHoundAD/BloodHound#485]
When using BloodHound to connect to a Neo4j instance (v4.3.6 in my testing), the client hangs. This produces an error on the Neo4j side:

```
ERROR [graph.db/891b1a5e] Error upgrading database. Database left intact and will likely not be able to start: org.neo4j.storageengine.migration.UpgradeNotAllowedException: Neo4j cannot be started because the database files require upgrading and upgrades are disabled in the configuration. Please set 'dbms.allow_upgrade' to 'true' in your configuration file and try again. Detailed description: Upgrade is required to migrate store to new major version.
```

A workaround to this issue is to uncomment the following line in `/etc/neo4j.conf`: `dbms.allow_upgrade=true`.

However, it appears that BloodHound does not handle version mismatch errors, causing the authentication prompt to spin indefinitely.

**Comment by rvazarkar** [comment]
I'm guessing this is a neo4j issue so I'm going to close this. If its still an issue reopen this one.
