### ISSUE TITLE
Issues with ghaph view

### ISSUE THREAD

**Issue by UrfinJuice11** [BloodHoundAD/BloodHound#486]
Neo4j 4.2.1
BloodHound 4.0.3,2,1; 3.0.5
Linux kali 5.10.0-kali7-amd64 #1 SMP Debian 5.10.28-1kali1 (2021-04-12) x86_64 GNU/Linux (VBox image, 4GB RAM)

1. Upload new data to BH.
2. A couple of initial nodes is displayed. We can drag-n-drop them, zoom in/out. 
3. When make any query to show another couple of nodes, the view gets broken. Zooming, dragging not working. 
4. If make several queries in a raw BH freezes

**Comment by yellow-starburst** [comment]
This is probably lack of ram on system resources. 
Try either loading bh in memory or buy more ram/better cpu.

**Comment by yellow-starburst** [comment]
@UrfinJuice11 lets close this ticket

**Comment by UrfinJuice11** [comment]
Actually I have 16GB RAM on host system and 8GB RAM on the virtual system on which I run BH. Suppose it should be more than enough...

**Comment by UrfinJuice11** [comment]
Maybe I can provide some additional logs/screenshots/other info?

**Comment by rvazarkar** [comment]
My initial guess is that your VM isn't doing hardware acceleration properly, which is causing the weird issues you're seeing. 

One thing you can check is opening the console with Ctrl + Shift + I and see if theres errors there that might help diagnose the problem
