### ISSUE TITLE
BloodHound 4.0.3 Release - Skips the computers.json file when importing from zip file.

### ISSUE THREAD

**Issue by superhac** [BloodHoundAD/BloodHound#487]
I noticed when importing the zip on the lastest release that for whatever reason its skipping importing the computers.json file contained in the zip.  I used the PS script to generate the zip.  

As a work around I just imported all the json files manually and all were accepted.  No issues importing each of the json files manually. 

Thanks!

**Comment by ricardojoserf** [comment]
Hello @superhac , I was having the same problem but had not realized that adding the computers json by hand would fix it, thank you! In my case I was using the latest Bloodhound release with different versions of Neo4j desktop in Windows 10, trying both the exe and Powershell Sharphound versions, could not see the computer objects until adding the json manually

**Comment by rvazarkar** [comment]
Fixed in vnext, was a bug in the unzipper library
