### ISSUE TITLE
Relations between nodes do not show up by default, only when using queries?

### ISSUE THREAD

**Issue by nicolaipre** [BloodHoundAD/BloodHound#488]
I am not sure whether I have missed a setting or not but I have looked thoroughly and haven't found anything that has solved the problem yet. 

I have added the following nodes and added edges/relations between them, but these do not show up even though `Edge Label Display` is set to `Always Display` in the Bloodhound settings. Neo4j is also running without problems. 

![image](https://user-images.githubusercontent.com/16032412/139019868-cc036e1a-c3ba-4680-aad9-e1b933d7926a.png)

If I specify a target node the relations show up, however according to the [docs here](https://bloodhound.readthedocs.io/en/latest/data-analysis/bloodhound-gui.html), it seems like the relations show up without any query?

**Image from Bloodhound Docs, showing relations without a query:**
![image](https://bloodhound.readthedocs.io/en/latest/_images/bloodhound-initial-query.png)

**With target node specified:**
![image](https://user-images.githubusercontent.com/16032412/139020193-75f6b697-d1a8-41d7-94ba-2b2ca636a98c.png)

For reference I am running Bloodhound v. 4.0.3 in a Kali Virtual Machine. 

My goal is to have relations show up by default without any query to easily see the relations between all of the hosts I have added.

**Comment by rvazarkar** [comment]
The image from the docs is the default query that runs when the application spins up, which is members of the domain admins group. Theres no automagical showing of edges, so you're not missing anything here
