### ISSUE TITLE
Sharphound  problem, no session

### ISSUE THREAD

**Issue by orgserj** [BloodHoundAD/BloodHound#493]
I am using the latest Sharphound, it dumped 350k objects, but not a single session =(

**Comment by rvazarkar** [comment]
Is this environment on win10? If so, do you have admin rights on computers? We're making improvements in vnext that might alleviate some of this, but win10 improvements have made enumeration a lot harder

**Comment by yellow-starburst** [comment]
Even if it's win10, bloodhound does indirect enumeration.
So as long as the servers aren't newer than 2016 u should get sessions.
I've had this happen to me a couple times.
Try using an older sharphoudn collector.

**Comment by Bassem-ossama** [comment]
Same problem.

**Comment by yellow-starburst** [comment]
Try again with new update sharphound

**Comment by rvazarkar** [comment]
Closing this for now. Reopen if the problem is still there with the new sharphound

**Comment by JonasBK** [comment]
Hey @ntsurisr,
Sessions are stored in the computer json:
![image](https://user-images.githubusercontent.com/12843299/235143421-f8a410e3-0544-4b7b-b446-26cc56c1e9f7.png)

**Comment by ntsurisr** [comment]
Thank you @JonasBK for the quick response, haven't loaded the data into Bloodhound GUI yet, was expecting a sessions.json file. Appreciate your help.
