### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by f00d4w0rm5** [BloodHoundAD/BloodHound#494]
I'm trying to log on to bloodhound for the first time.  I tried neo4j:neo4j and neo4j:BloodHound but no luck.  

At first I was having issues with the database.  Running 'neo4j console' gave me this error: 
'Error: Could not find or load main class org.neo4j.server.CommunityEntryPoint
Caused by: java.lang.ClassNotFoundException: org.neo4j.server.CommunityEntryPoint'

So instead I downloaded the neo4j-desktop appimage.  This worked fine, and now the database has a green check mark by it in the Bloodhound console.  But now instead of saying 'database not found' it says 'incorrect username or password'.  

I'm running this on Garuda, which is based on Arch.  Any suggestions?

**Comment by rvazarkar** [comment]
We don't currently support the desktop version of neo4j, only server. You need to initially log in to the neo4j web console at localhost:7474 with neo4j:neo4j and change the password. After that you can log in to the BH interface

**Comment by f00d4w0rm5** [comment]
Thanks for your response!  This appears to be a neo4j issue but I'd really appreciate some guidance.  I downloaded bloodhound with pacman and it automatically installed neo4j-community-3.5.14-1.  When I attempt to run neo4j I get below.  Neo4j start appears to work but when I go to localhost:7474 it says the site can't be reached.  Systemctl shows neo4j.service is running at first but then after a minute it says it failed. 

```
λ neo4j console
WARNING! You are using an unsupported Java runtime. 
* Please use Oracle(R) Java(TM) 8, OpenJDK(TM) or IBM J9 to run Neo4j.
* Please see https://neo4j.com/docs/ for Neo4j installation instructions.
Active database: graph.db
Directories in use:
home:         /usr
config:       /usr/conf
logs:         /usr/logs
plugins:      /usr/plugins
import:       NOT SET
data:         /usr/data
certificates: /usr/certificates
run:          /usr/run
Starting Neo4j.
Error: Could not find or load main class org.neo4j.server.CommunityEntryPoint
Caused by: java.lang.ClassNotFoundException: org.neo4j.server.CommunityEntryPoint

λ java --version
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12)
OpenJDK 64-Bit Server VM (build 17.0.1+12, mixed mode)
```

**Comment by f00d4w0rm5** [comment]
I got it working!  Had to change versions of java...as it obviously said -_-
Also, the package installed by pacman did not work but the tarball did!

```
f00d4w0rm5@garuda in ~/tools/apps/neo4j-community-4.4.3/bin as 🧙 took 5s
[🔴] × java --version
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12)
OpenJDK 64-Bit Server VM (build 17.0.1+12, mixed mode)

λ sudo pacman -S jdk11-openjdk

f00d4w0rm5@garuda in ~/tools/apps/neo4j-community-4.4.3/bin as 🧙 
λ archlinux-java status
Available Java environments:
java-11-openjdk
java-17-openjdk (default)
java-8-openjdk/jre

f00d4w0rm5@garuda in ~/tools/apps/neo4j-community-4.4.3/bin as 🧙 took 25ms
λ sudo archlinux-java set java-11-openjdk

f00d4w0rm5@garuda in ~/tools/apps/neo4j-community-4.4.3/bin as 🧙 took 59ms
λ archlinux-java status
Available Java environments:
java-11-openjdk (default)
java-17-openjdk
java-8-openjdk/jre

f00d4w0rm5@garuda in ~/tools/apps/neo4j-community-4.4.3/bin as 🧙 took 23ms
λ java --version
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8)
OpenJDK 64-Bit Server VM (build 11.0.13+8, mixed mode)

f00d4w0rm5@garuda in ~/tools/apps/neo4j-community-4.4.3/bin as 🧙 took 205ms
λ ./neo4j console
```

**Comment by rvazarkar** [comment]
Good to hear! Closing this issue, and happy graphing!
