### ISSUE TITLE
BloodHound won't log into Neo4j database

### ISSUE THREAD

**Issue by scaldwell22** [BloodHoundAD/BloodHound#496]
I have BloodHound set up and running on Ubuntu 20.04.  Everything seems to be working fine, I can log into neo4j through the browser, I can start the neo4j using systemctl or console commands, BloodHound sees the database, but for whatever reason it won't log into the neo4j database through BloodHound.  On my first login to the neo4j web console I did update the password but that is the only change I have made.  When putting in the wrong password BloodHound immediately tells me the password is wrong, but when I put in the right password the login button just spins and nothing happens.  Any help would be appreciated.

![image](https://user-images.githubusercontent.com/98042661/150171392-535f8ffd-51cf-4855-9194-556933604d35.png)

**Comment by rvazarkar** [comment]
Can you open the console using Ctrl + Shift + I and see if theres any errors there

**Comment by scaldwell22** [comment]
> Can you open the console using Ctrl + Shift + I and see if theres any errors there

Absolutely.  Looks like it's saying the graph.db file isn't availible.

![image](https://user-images.githubusercontent.com/98042661/150187952-6ca10f9a-60d2-4a54-b9ed-11edad5cb457.png)

**Comment by rvazarkar** [comment]
Looks like your neo4j instance isn't running properly then. The graphdb not being available means something went wrong in its initialization steps. You should check the neo4j logs

**Comment by scaldwell22** [comment]
Will do, thanks!

**Comment by scaldwell22** [comment]
Got in, ended up just purging neo4j and reinstalling.  Seems to have worked.  I appreciate the quick response and help.
