### ISSUE TITLE
bloodhound 4.1.0 Darwin arm64 release not working

### ISSUE THREAD

**Issue by epichoxha** [BloodHoundAD/BloodHound#504]
App does not run. Error message:`BloodHound.app” is damaged and can’t be opened.`

Mac M1
```
Darwin ****.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64
```

**Comment by yellow-starburst** [comment]
Everything breaks with M1 - what do you expect? Lol

**Comment by vysecurity** [comment]
+1, but you can compile yourself and it'll work.

**Comment by ddlees** [comment]
@epichoxha We overhauled our build infrastructure and are now publishing the artifacts from the most recent commit on the master branch to a rolling release. Can you let us know if the arm64 binary that is published there works for you? Thanks!

https://github.com/BloodHoundAD/BloodHound/releases/tag/rolling

**Comment by epichoxha** [comment]
@ddlees , nah, still getting the same issue. 

```
“BloodHound.app” is damaged and can’t be opened. You should move it to the Bin.
```

**Comment by vysecurity** [comment]
If you build it, it'll work.

**Comment by epichoxha** [comment]
I'll try to build @vysecurity thanks

**Comment by andyrobbins** [comment]
@epichoxha 

I just built the M1 binary on my M1 and verified it works. I went ahead and added it to the release as well: https://github.com/BloodHoundAD/BloodHound/releases/tag/4.1.0

If you'd like to build this yourself, you can clone the repo then run these commands:

`npm ci`
`npm run build`

This will create the M1 compatible binary for you

Andy

**Comment by epichoxha** [comment]
Hey @andyrobbins thanks. Couldn't find your recent built. I build it myself, it works well. 

Thanks

**Comment by vysecurity** [comment]
@andyrobbins did you get customqueries.json to work on the ARM build?

**Comment by vashirov** [comment]
App is not signed, I had to remove `com.apple.quarantine` to be able to start it:
```xattr -d com.apple.quarantine /Applications/BloodHound.app```

**Comment by Esonhugh** [comment]
Is the brew one a right M1 Version?

**Comment by vashirov** [comment]
Brew only had Intel version. I've submitted a PR to add support for arm64 builds in https://github.com/Homebrew/homebrew-cask/pull/127827

**Comment by vashirov** [comment]
What's interesting though is that arm64 version has signing issues while x64 version is just not signed: <img width="804" alt="image" src="https://user-images.githubusercontent.com/1745018/178933605-2f684656-b98a-49fc-91fa-da0f8a632436.png">
<img width="804" alt="image" src="https://user-images.githubusercontent.com/1745018/178933655-64bbb321-8c65-4d92-aef3-ff5f60aff231.png">

**Comment by vysecurity** [comment]
issue still exists.

**Comment by chadministratorwastaken** [comment]
Having this same problem with the latest 4.2.0 release.

**Comment by pwnmeow** [comment]
Its still a issue

**Comment by rpetersson** [comment]
When an application gets downloaded from any source other than those that Apple seems suited, the application gets an extended attribute "com.apple.Quarantine". This triggers the message: "<application> is damaged and can't be opened. You should move it to the Bin."
Remove the attribute and you can launch the application.

To do this, open a console and type:

$ xattr -c <path/to/application.app>

Lauch, smile and enjoy.

**Comment by benburkhart** [comment]
thanks @rpetersson , worked like a charm
