### ISSUE TITLE
SharpHound v4.1 highvalue property not set on all nodes

### ISSUE THREAD

**Issue by idnahacks** [BloodHoundAD/BloodHound#505]
The highvalue property is only being set on nodes that are classed as highvalue in the latest version. Previous versions set the property almost everywhere, with a true or false value.

**Comment by lucasni2** [comment]
Also noticing some built-in groups that were classified as High Value Targets in previous versions are no longer labeled High Value, ie Account Operators, Remote Desktop Users and Print Operators. 

Workaround for previous users comment involves some custom cypher:

MATCH (n) WHERE NOT EXISTS(n.highvalue) SET n.highvalue = false RETURN n.name, n.highvalue
