### ISSUE TITLE
SharpHound uses the same name for all JSON files collected.

### ISSUE THREAD

**Issue by AlexSta2019** [BloodHoundAD/BloodHound#508]
In the latest version of SharpHound, the collector will use the same name for all JSON files created (for users, computers, groups, etc).
![image](https://user-images.githubusercontent.com/81108264/153818304-c0b9298b-8362-4858-aeed-bf1000460694.png)

When archiving the zip files the name conflict will result in a random name for the ZIP file with files collected in a loop. However, the content of the zip files (all JSON files produced) will have the same name - which corresponds to the timestamp when the first ZIP was created.

**Comment by AlexSta2019** [comment]
A possible workaround is to create a loop in PWSH:
```
$start_time = Get-Date
$time_range = New-TimeSpan -Hours 3
for ($t = $start_time; $t -lt $start_time + $time_range; $t = Get-Date) {.\SharpHound.exe -c All -d contoso.com}
```

**Comment by AlexSta2019** [comment]
Yep, when doing this:
`.\SharpHound.exe -c All -d contoso.com --loop --loopduration 03:00:00`

**Comment by rvazarkar** [comment]
Got it, taking a look

**Comment by rvazarkar** [comment]
Fixed in https://github.com/BloodHoundAD/SharpHound/commit/e76cdd8da0348ec2f13a508e8878ca9c77db271b
