### ISSUE TITLE
ERROR | CommonLib ACLProc | BuildGuIDCache - unable to resolve forest

### ISSUE THREAD

**Issue by AlexSta2019** [BloodHoundAD/BloodHound#509]
Latest version of SharpHound shows an error, like the one in the screenshot, soon after initiating a new loop. 
![image](https://user-images.githubusercontent.com/81108264/153819936-b39f3796-7365-4dc3-8d4a-16afeb08da65.png)

The collection seems successful (JSON files created with details about users/computers etc), and the underlying LDAP query does not show any (obvious) error messages.
For LDAP tracing I used the steps from this article: https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/turn-on-debug-logging-ldap-client

Would be great if anyone could confirm this is an error that can be ignored.

**Comment by rvazarkar** [comment]
Assuming this is running under netonly, I dont believe theres anything we can do to fix this. The worst that can happen is you miss LAPS edges with these errors.

**Comment by InTheFog-DT** [comment]
Received the same error numerous times, eventually the collection started normally

**Comment by rvazarkar** [comment]
Closing this for now. Reopen if the issue comes back
