### ISSUE TITLE
I think prettprint is broken ?

### ISSUE THREAD

**Issue by freeload101** [BloodHoundAD/BloodHound#522]
I think --prettyprint is broken ? and maybe zip ? ( my output is normally around 100 megs )

I am running Sharphound with the following ( may not need powershell etc ) and it looks like it's going fine then writes to bin file and dies or just writes to empty .json with a bunch of blank entries ',,,,,,,,,,,,,,,,,,,,,,,,,,,,'

`
runas /netonly /user:"NR.AD.COMPANY.COM\robert.mccurdy@COMPANY.com" cmd

powershell

$ctxtype = [System.DirectoryServices.ActiveDirectory.DirectoryContextType]::Domain
$ctx = New-Object System.DirectoryServices.ActiveDirectory.DirectoryContext($ctxtype,"NR.AD.COMPANY.COM")
$domain = [System.DirectoryServices.ActiveDirectory.Domain]::GetDomain($ctx)
$domain.Name

./SharpHound.exe -v 1 --nozip true --prettyprint true

`

Once I removed prettyprint it seems to be working fine ... I won't know because it takes about 1hr to run lol ...

**Comment by McBartok** [comment]
Can confirm that I have the same issue. Had not got to the point of figuring out why it was failing until I saw this, so thanks :)

So Sharphound works as expected, provided you dont use prettyprint, but fails if I add it.

Strange part is it used to work fine. Maybe its a character in some AD object that is breaking the `JsonSerializer.Serialize` in /SharpHound/blob/dev/src/Writers/JsonDataWriter.cs?

**Comment by freeload101** [comment]
> 

If I had to guess yah parsing issue .. because it does all the 'work' then at the end errors out so like the array or whatever (not a programmer) has got something that breaks the output. 

note: If I do debug (vv or v2 whatever) it runs fine .. one would think the debug output would 'crash' it in the same way.

**Comment by rvazarkar** [comment]
Yeah, theres definitely an issue with PrettyPrint. Will add it to todo

**Comment by freeload101** [comment]
Did I get lucky or did you fix it ? I ran it fine from binary the 29th following I may have not had the `-s` as a switch not sure now. I can try again next week if you like. I just know I didn't have to parse the JSON this time

```
runas /user:"nr.ad.COMPANY.com\USERNAME" /netonly cmd
SharpHound.exe -s --CollectionMethods All --prettyprint true
```
https://github.com/freeload101/Bloodhound-Portable

-Thanks!
