### ISSUE TITLE
Suggested New Edge: msDS-GroupMSAMembership

### ISSUE THREAD

**Issue by johnmccash** [BloodHoundAD/BloodHound#524]
For GMSA accounts (which are often highly privileged), the msDS-GroupMSAMembership attribute specifies accounts that can retrieve the password. This should be an edge traced by Bloodhound.

**Comment by rvazarkar** [comment]
We track this already

https://github.com/BloodHoundAD/SharpHoundCommon/blob/master/src/CommonLib/Processors/ACLProcessor.cs#L415

**Comment by johnmccash** [comment]
Rohan,
I’m not disputing your answer, but I’m still a little confused. I can’t find the associated edge documented at https://bloodhound.readthedocs.io/en/latest/data-analysis/edges.html, and I’m unclear from reading the source (sorry, I’m definitely NOT a developer) exactly what this would look like displayed in the GUI.
.
.
.
Ahah! Found it. If I’m reading this correctly, the associated Edge name would be ReadGMSAPassword, right? So, shouldn’t that be documented in the associated Edges page above? It doesn’t appear to be… That being the case, please change this to a documentation issue.

                Thanks
                                John

**Comment by johnmccash** [comment]
Rohan,
I’m not disputing your answer, but I’m still a little confused. I can’t find the associated edge documented at https://bloodhound.readthedocs.io/en/latest/data-analysis/edges.html, and I’m unclear from reading the source (sorry, I’m definitely NOT a developer) exactly what this would look like displayed in the GUI.
.
.
.
Ahah! Found it. If I’m reading this correctly, the associated Edge name would be ReadGMSAPassword, right? So, shouldn’t that be documented in the associated Edges page above? It doesn’t appear to be… That being the case, please change this to a documentation issue.

                Thanks
                                John

From: Rohan Vazarkar ***@***.***>
Sent: Thursday, March 10, 2022 10:12 AM
To: BloodHoundAD/BloodHound ***@***.***>
Cc: John Mccash ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [BloodHoundAD/BloodHound] Suggested New Edge: msDS-GroupMSAMembership (Issue #524)

This email originated from outside the organization. Do not click links or open attachments unless you have verified this email is legitimate.


We track this already

https://github.com/BloodHoundAD/SharpHoundCommon/blob/master/src/CommonLib/Processors/ACLProcessor.cs#L415<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBloodHoundAD%2FSharpHoundCommon%2Fblob%2Fmaster%2Fsrc%2FCommonLib%2FProcessors%2FACLProcessor.cs%23L415&data=04%7C01%7Cjm460%40ntrs.com%7C441b1b51aa5d4b91cc0c08da02b0acbc%7C2434528d4270497781dda6308c1761a3%7C0%7C0%7C637825255073017713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PH1iAzCeSESXVPCsKnuxn9Seygs3KYzMc9v6LUe6qlQ%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBloodHoundAD%2FBloodHound%2Fissues%2F524%23issuecomment-1064230111&data=04%7C01%7Cjm460%40ntrs.com%7C441b1b51aa5d4b91cc0c08da02b0acbc%7C2434528d4270497781dda6308c1761a3%7C0%7C0%7C637825255073017713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZCSAurswK7Q9OYqo0oXyOuBC8xg7kH8BgisrAKtXjBE%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAVW6VD6TG435KT72ZGCBUDU7INL5ANCNFSM5PXJJUVQ&data=04%7C01%7Cjm460%40ntrs.com%7C441b1b51aa5d4b91cc0c08da02b0acbc%7C2434528d4270497781dda6308c1761a3%7C0%7C0%7C637825255073017713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EUFkIC5mSCu2%2BNtcFOyp2IAWbXKIEO5o65Lan3KNW9E%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjm460%40ntrs.com%7C441b1b51aa5d4b91cc0c08da02b0acbc%7C2434528d4270497781dda6308c1761a3%7C0%7C0%7C637825255073017713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0rctlqaHl8ksFvL327swhntLvsayMwniLk0Uh5LSwgA%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjm460%40ntrs.com%7C441b1b51aa5d4b91cc0c08da02b0acbc%7C2434528d4270497781dda6308c1761a3%7C0%7C0%7C637825255073017713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QeT%2FNVBmQVjHhucYSwUvMRMVm8s6VHaMh9n%2FKlJOo9U%3D&reserved=0>.
