### ISSUE TITLE
Searches only available by 'id' rather than friendly name

### ISSUE THREAD

**Issue by Only1BigK** [BloodHoundAD/BloodHound#527]
I have imported results from AzureHound and when searching for a user or device in BloodHound, objects are only resolved when searching by their "Device ID" rather than a friendly name such as "Device Display Name" or for users, I can only find people using "Object ID" rather than "Display Name".

BloodHound version: 4.0.2.0
AzureHound version: latest (last commit 8th July 2021)

This is not affecting SharpHound.

**Comment by rvazarkar** [comment]
In our next release, we're changing how AzureHound sets names for AD users (as in it won't at all)
