### ISSUE TITLE
Feature Request: User Input In QueryNodeSelect

### ISSUE THREAD

**Issue by cutaway** [BloodHoundAD/BloodHound#53]
The "QueryNodeSelect" function in BloodHound/src/components/Float/QueryNodeSelect.jsx is used to gather information from user queryable data. For really large environments it might be easier, in some cases, to allow users to input data for a query. 

For instance, selecting all computers with sessions belonging to a specific user or service account. Another example is finding usernames in multiple domains. 

With the current model the "nodeSelectQuery" would need to populate ALL users in a dropbox list for selection. It would be easier to just query the BloodHound user for data associated with the username. 

I took a quick look at BloodHound/src/components/Float/QueryNodeSelect.jsx did not see a quick and easy way for myself to accomplish this. I figure there should be an easy way to determine if the query field of nodeSelectQuery is empty and then just ask for input.

Example:

```
 {
             "name" : "Cutaway Test: Search Account Name in All Domains",
             "requireNodeSelect": true,
             "nodeSelectQuery": {
                 "query": "",
                 "onFinish": "MATCH (n:User) WHERE n.name =~ ('(?i){}' + '(?i)@*.') RETURN n",
                 "start": "{}",
                 "end": "",
                 "allowCollapse": false,
                 "boxTitle": "Input Account Name..."
             }
 },
```

Thank you,
cutaway

**Comment by cutaway** [comment]
Okay, just realized my examples weren't very good as they can be done by just typing the data into the default search text box. Still, it might be useful for future queries to have user input rather than just pre-build queries.

cutaway

**Comment by rvazarkar** [comment]
We're probably not going to implement this, just because the amount of work it would take to actually do it is way too much with the way the UI is currently structured. 

It might be easier to accomplish what you want with the new pre-built queries anyways.
