### ISSUE TITLE
Big data file ZIP

### ISSUE THREAD

**Issue by benybb** [BloodHoundAD/BloodHound#534]
Hello,

I used Bloodhound in a very big Environment .
The zip file is huge - 3 MB .
When i drag it into Bloohound - it doesn't success to import the objects.

no errors shown  in the upload task!

Does Bloodhound have a limit size of database ?

Thanks in advance !!

**Comment by ddlees** [comment]
@benybb No there is no size limit and 3MB isn't anywhere near large enough to cause an issue. That said, it's more likely that ingest is not handling something in the data that is being uploaded properly.

In the BloodHound UI you should be able to `ctrl + shift + i` to capture any errors being logged to the console. If you are able to post those logs here that would help us be able to figure out what might be going on. Thank you!

**Comment by benybb** [comment]
Thanks for the response - nothing special in the error logs..
![image](https://user-images.githubusercontent.com/22418612/162286954-a94143e9-f9d0-44aa-9c5b-3cc940928a6b.png)

Also Captured the Sharphound process collector - I tried again but no difference at all:
![Capture](https://user-images.githubusercontent.com/22418612/162287238-8fe87d08-db04-4ef9-8c69-f2a0272aae78.JPG)

That's the files's size:
![image](https://user-images.githubusercontent.com/22418612/162287429-66fea238-cdaa-468e-834d-f6da3657ed06.png)

Should be there thousands of objects but Bloodhound show only a few - hundred:
![image](https://user-images.githubusercontent.com/22418612/162287686-8251fd6d-30a4-480d-bafc-a4a38989ad41.png)


Also the search filed find nothing....
