### ISSUE TITLE
Query Progress Bar/Status

### ISSUE THREAD

**Issue by platinumvoid** [BloodHoundAD/BloodHound#535]
Is there a way to view the status of an executed query (preferrably in a percentage/progress bar), instead of a looped animation that sais processing data? I have a large infrastructure 20k plus nodes (Azure) and it is taking too long ( I am not sure if an error was encountered or it just needs more time)

**Comment by rvazarkar** [comment]
Neo4j doesn't provide this data to use unfortunately
