### ISSUE TITLE
SharpHound.ps1 missing from Collectors

### ISSUE THREAD

**Issue by Japillow** [BloodHoundAD/BloodHound#544]
The [BloodHound documentation](https://bloodhound.readthedocs.io/en/latest/data-collection/sharphound.html) mentions the PS1 version of Sharphound. Since commit https://github.com/BloodHoundAD/BloodHound/commit/38811dcd8e8b0478d2e8694b742b9cd8a4a02265, the .ps1 version of SharpHound was "temporarily removed" from [Collectors](https://github.com/BloodHoundAD/BloodHound/tree/master/Collectors). Why was the PowerShell version removed and will it return eventually ? Is there a rationale, or do we just need to update the binary to the new version and create a PR ?

N.B. The former ps1 version of SharpHound can still be found at https://github.com/BloodHoundAD/BloodHound/blob/4.0.3/Collectors/SharpHound.ps1. Note however, this does not ensure compatibility with future BloodHound versions.

**Comment by rvazarkar** [comment]
I'll be reintroducing this shortly, I updated the template and automation in the repo here: https://github.com/BloodHoundAD/SharpHound/commit/a6770fb5f1608155011dacfb067d347cbb8f3d2b
