### ISSUE TITLE
BloodHound won't start

### ISSUE THREAD

**Issue by bubaidongfang** [BloodHoundAD/BloodHound#546]
Environment: neo4j starts normally, java 11 works normally, win10 system,Neo4j Server version: 4.4.7,BloodHoundAD：4.1.0([BloodHound-win32-x64.zip]
Unable to start, the error message is shown in the figure:
![image](https://user-images.githubusercontent.com/18612063/170180539-2d33f30f-cc1c-44eb-a48f-b3a93d629cbf.png)

**Comment by rvazarkar** [comment]
I dont believe we've seen this issue and we cant replicate it. Can you give us more information on how to replicate?

**Comment by bubaidongfang** [comment]
The latest version no longer has this error, thank you



***@***.***
 
From: Rohan Vazarkar
Date: 2022-07-19 02:41
To: BloodHoundAD/BloodHound
CC: bubaidongfang; Author
Subject: Re: [BloodHoundAD/BloodHound] BloodHound won't start (Issue #546)
I dont believe we've seen this issue and we cant replicate it. Can you give us more information on how to replicate?
