### ISSUE TITLE
Machine Account PwdLastSet attribute used as enumeration condition flag

### ISSUE THREAD

**Issue by TinusGreen** [BloodHoundAD/BloodHound#549]
Hi there,

I came across the issue using SharpHound (v3) in my test network. After a couple of months, I started to see that SharpHound was refusing to perform the local enumeration of the discovered hosts.

Using the `--trackcomputercalls` flag when running Sharphound, I discovered that it decided not to enumerate the local configuration due to the reason: "PwdLastSetOutOfRange". I was able to confirm that the machine accounts of my lab hosts had not rotated in the last four months. After rotating the machine accounts and confirming that it updated the PwdLastSet attribute in the associated AD computer object, Sharphound performed the required local enumeration on these hosts.

While I can understand that the machine accounts were old, I would like to understand why this is being used as a condition flag to attempt to enumerate the host? Often on assessments we would target the hosts of an organisation that have not rotated their machine accounts in the last 30 days, since that usually indicates that the machine account was potentially manually tampered with. However, with this being used as an enumeration condition, it would not perform the local checks such as sessions or local admins, meaning your Bloodhound data would be incomplete.

Could this perhaps either be removed as an enumeration condition or a parameter exposed that could override this configuration?

**Comment by rvazarkar** [comment]
The default setting for computer password rotation is 30 days, so we key off that to remove hosts which likely aren't alive. This ends up saving a lot of time on enumeration as we're not waiting for API calls to timeout. 

I can look at making this a flag

**Comment by TinusGreen** [comment]
Thank you for the feedback.

Yes, I'm aware that machine accounts should rotate every 30 days. We have just in the past discovered some active hosts that had older machine accounts, usually indicating that someone tampered with them which is then often associated with additional vulnerabilities. Having a flag that we could set to ensure that there would still be enumerated would really help.

Thank you for the assistance.

**Comment by rvazarkar** [comment]
I added a flag to skip this check in https://github.com/BloodHoundAD/SharpHound/commit/a6770fb5f1608155011dacfb067d347cbb8f3d2b

It'll be in the next build of SharpHound, or you can grab the rolling release to get it.

**Comment by TinusGreen** [comment]
Thank you!
