### ISSUE TITLE
Proposed New Edge: SyncLAPSPassword

### ISSUE THREAD

**Issue by simondotsh** [BloodHoundAD/BloodHound#555]
## Context
The combination of `DS-Replication-Get-Changes` and `DS-Replication-Get-Changes-In-Filtered-Set` at the root of a domain renders it possible for a principal to perform a directory synchronization (DirSync), and retrieve confidential and RODC filtered attributes, such as LAPS' `ms-Mcs-AdmPwd`. See technical details [here](https://simondotsh.com/infosec/2022/07/11/dirsync.html).

## Proposed New Edge
**Name:** SyncLAPSPassword.
**Conditions:** A principal has both `DS-Replication-Get-Changes` and `DS-Replication-Get-Changes-In-Filtered-Set` at the root of a domain.
**Linked To:** All LAPS-enabled computers.

While this does not follow the current way edges for `DCSync` are drawn, it avoids returning a path when a principal only has one of the two privileges; however, it could lead to missing this edge when a principal can, for instance, add themselves to a group that has the second needed privileges. Despite this, I still believe this is the more desirable way to implement it.

## Contributing
If this edge is wanted, and the proposed way to implement it suits you, I can contribute the required changes, but will be waiting for the green light before doing so.

**Comment by rvazarkar** [comment]
Hey Simon, we've decided to accept this feature. Let me know if you want to contribute the code, otherwise we'll try and roll this into our 4.2 changeset and credit you with the request

**Comment by simondotsh** [comment]
Hi @rvazarkar,

I'll give it a go and report back when I created the pull requests.

**Comment by simondotsh** [comment]
Hello @rvazarkar,

See the pull requests above for the contribution of this edge.

**Comment by rvazarkar** [comment]
This is a phenomenal PR. Thanks for the work. We're most likely going to accept it as is and make a few changes on our end to better fit some stuff we're doing for the 4.2 release.

**Comment by rvazarkar** [comment]
All the necessary changes have been merged into the respective 4.2 branches of the project. I'll close this when we've fully merged
