### ISSUE TITLE
Please add hotkey for toggling of expansion/collapse mode of Searchbar

### ISSUE THREAD

**Issue by jaredbarez** [BloodHoundAD/BloodHound#562]
**Is your feature request related to a problem? Please describe.**
Expanded searchbar's popup window (e.g. when showing an object properties) obscures considerable portion of attack path viewing area. Due to that, user is frequently forced to click on Searchbar's menu blade icon in order to collapse it and free the viewing area, which slows down the analysis performed by user by frequent clicking and moving the mouse to and from Searchbar's menu blade icon, or by zooming/moving attack paths just for the sake of avoiding expanded searchbar's popup window.

**Describe the solution you'd like**
Please add keyboard hotkey which should provide toggling of expansion/collapse mode of Searchbar. E.g. "TAB" key would be a good candidate for default hotkey because the user's right hand is (in majority of users) used for handling mouse.

An option (in source code or in GUI) for user to change hotkey assignement for this same action would be appreciated.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by rvazarkar** [comment]
Added in https://github.com/BloodHoundAD/BloodHound/commit/f2819fa33109fdc15b6d8b77cc4cab89632baafe

Is bound to `s` when on the graph
