### ISSUE TITLE
Please add hotkey for "Back" action of Searchbar

### ISSUE THREAD

**Issue by jaredbarez** [BloodHoundAD/BloodHound#563]
**Is your feature request related to a problem? Please describe.**
The analysis process performed by user in BH GUI could be made smoother/faster by adding hotkey for "Back" action (found in Searchbar).

**Describe the solution you'd like**
Adding of hotkey for "Back" action. Possible candidate(s) for this hotkey could be Backspace key (in some cases already used as "going back" in some browsers, so a portion of users could be already familiar with this behavior), or Cursor Left Key. 
An option (in source code or in GUI) for user to change hotkey assignement for this same action would be appreciated.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by rvazarkar** [comment]
Added in https://github.com/BloodHoundAD/BloodHound/commit/f2819fa33109fdc15b6d8b77cc4cab89632baafe

Is bound to backspace when on the graph
