### ISSUE TITLE
Typo in javascript: toUpperCase

### ISSUE THREAD

**Issue by jbelamor** [BloodHoundAD/BloodHound#571]
There is a typo in the javascript that holds the ingestion: newingestion.js

In the line 1143 it is calling to the function "t**p**UpperCase" instead of "toUpperCase"

https://github.com/BloodHoundAD/BloodHound/blob/45c04e7292a44362af1031cc0d7bd3748433ac4d/src/js/newingestion.js#L1143

**Comment by rvazarkar** [comment]
Thanks for the issue, not sure how we missed that during our testing
