### ISSUE TITLE
Domain "UNKNOWN"

### ISSUE THREAD

**Issue by ruuand** [BloodHoundAD/BloodHound#58]
Hi,

I have an issue with the Powershell Ingestor. All groups / users in local_admins.csv appears as being part of the "UNKNOWN" domain (e.g `"group","MIDEEL.SHINRA-INC.local","Domain Admins@UNKNOWN"`). All users / groups are properly named in the two other files (e.g "`Domain Admins@SHINRA-INC.local`")

Some quick infos:
- I ran `Get-BloodHoundData | Export-BloodHoundCSV`  
- I'm running the script from a non-domain-joined machine with `runas /netonly [...]`.
- There is only one domain in my small environment.

I can still do a find / replace to change it but i'm still wondering where this might come from.

And thanks for this tool, I've just played a bit with it but I will definitely try it on my next engagement.

Cheers !

**Comment by rvazarkar** [comment]
This supposedly happens when the IPv4 address in the SessionFrom data doesn't resolve to a name in AD.

**Comment by g1ldedm1n1on** [comment]
any update?

**Comment by rvazarkar** [comment]
The new version of the ingestor shouldn't allow this to happen, we've implemented fallbacks that should be more precise. I'll close this once we release it.

**Comment by rvazarkar** [comment]
The new ingestor has better fallbacks implemented, so this shouldn't happen anymore. You can find it here:

https://github.com/BloodHoundAD/SharpHound/releases
