### ISSUE TITLE
White Background no authentication

### ISSUE THREAD

**Issue by Adecosta1** [BloodHoundAD/BloodHound#584]
Installed latest version to windows 10 VM and run the exe but not authentication window ...just the blank white app background.
![bloodhound](https://user-images.githubusercontent.com/67304550/187418278-b8823576-0439-40e9-92f1-e98e81a608a2.jpg)

**Comment by pqod** [comment]
same issue but in windows 11

**Comment by pqod** [comment]
I solved the problem. Check if the zip has actually extracted all the files(dist folder, collection folder etc..). My antivirus was deleting malicious files and bloodhound would not start

**Comment by rvazarkar** [comment]
Closing this as an AV problem
