### ISSUE TITLE
Upload data problem

### ISSUE THREAD

**Issue by leebaird** [BloodHoundAD/BloodHound#586]
**Describe the bug**
Unable to upload SharpHound data that is 6 months old.

OS: Kali Linux rolling, fully patched.
Install method: apt install -y bloodhound

**To Reproduce**
Dragging a zip file onto the GUI returns an error.
The same thing happens when dragging on individual files.
The Upload Data button gives the same results.
"File created from incompatible collector     NaN%"

**Expected behavior**
JSON files are successfully uploaded.

**Additional context**
<img width="656" alt="apt" src="https://user-images.githubusercontent.com/4013039/189235771-8f9da8e9-ffe3-4bb2-afc4-a67fac92b538.png">

**Comment by JonasBK** [comment]
I believe 4.2 BH is only compatible with the v1.1 version (latest) of SharpHound released in August this year: https://github.com/BloodHoundAD/SharpHound/releases/tag/v1.1.0

You could try to install the 4.1 version of BH:
https://github.com/BloodHoundAD/BloodHound/releases/tag/4.1.1
