### ISSUE TITLE
Rightclick a "GenericWrite" edge targeting a GPO and click the "Help" button, the whole UI goes blank

### ISSUE THREAD

**Issue by l0ss** [BloodHoundAD/BloodHound#589]
When i rightclick a "GenericWrite" edge targeting a GPO and click the "Help" button, the whole UI goes blank. The JavaScript console shows some uninformative React errors.

**To Reproduce**
Rightclick a "GenericWrite" edge targeting a GPO and click the "Help" button

**Expected behavior**
Help is displayed.

**Screenshots**
![Monosnap BloodHound 2022-09-15 14-08-34](https://user-images.githubusercontent.com/24580473/190935781-8ddccec3-2d3f-4999-b300-9233a9797794.png)

**Comment by JonasBK** [comment]
Closing - Fixed in 4.3.1 🥳
