### ISSUE TITLE
Bloodhound incorrectly mentions Computer Node as User Node

### ISSUE THREAD

**Issue by surajpkhetani** [BloodHoundAD/BloodHound#593]
**Describe the bug**
In the bloodhound graph, an invalid relationship seems to be shown. i.e. CanRDP permission from one user to other user. However, the target is actually a Computer Node.

**Expected behavior**
The node should be a user node instead of a computer node.

**Screenshots**
![image](https://user-images.githubusercontent.com/25839564/193579359-5797a436-feba-4760-ade5-4245bbea37f0.png)

**Comment by rvazarkar** [comment]
Did you do GPOLocalGroup collection?

**Comment by surajpkhetani** [comment]
I do not think I included GPOLocalGroup in the collection.

**Comment by JonasBK** [comment]
Hi @surajpkhetani,

Thanks for reporting this!
I'm 99% sure that this is caused by the same problem as this issue: https://github.com/BloodHoundAD/BloodHound/issues/589
I will mark this one as a duplicate. We will get it fixed as soon as possible.
