### ISSUE TITLE
Domain Trust Attributes Addition

### ISSUE THREAD

**Issue by Xyan1d3** [BloodHoundAD/BloodHound#594]
**Problem**
Everytime I am in a multi domain / forest network I have to run powerview's Get-DomainTrust cmdlet or the Get-ADTrust cmdlet to enumerate the trusts across the domains / forests. While bloodhound only displays only the direction of the trust, It would be much better if it also had the trust attributes

**Solution **
Add like some more arrows which would have the attributes like FILTER_SIDS, QUARANTINED_DOMAIN, PARENT_CHILD between the domains that would make enumeration and trust visualisation much more better.

**Comment by jsdhasfedssad** [comment]
This would be great to have! The information I lack the most is whether or not SID history, in MS' terminology that is called "treat_as_external", and whether or not SID filtering is enabled ("quarantine"). I would also like the group attribute RID to be implemented but I had already put that in a [request ](https://github.com/BloodHoundAD/BloodHound/issues/648) before seeing this.
