### ISSUE TITLE
Screen goes white when trying to view info on a specific edge.

### ISSUE THREAD

**Issue by mk-parrot** [BloodHoundAD/BloodHound#598]
The screen goes completely white when trying to view info by pressing the ? Help button in the right click menu of an `WriteAccountRestrictions` edge requiring a restart of the application.

1. Query something that returns a WriteAccountRestrictions edge
2. Right click on the edge
3. Left click ? help in the right click menu
4. Application window goes white

**Expected behavior**
Show the help information menu on said edge.

**Additional context**
 `TypeError e.toLowerCase is not a function` error message viewable in the console.

**Comment by ville87** [comment]
Having same issue when clicking on the "? Help" of a GenericWrite relation from "Domain Computers" to a GPO
