### ISSUE TITLE
Find Kerberoastable Users with Most Privileges does not return nodes

### ISSUE THREAD

**Issue by DoubtfulJerboa** [BloodHoundAD/BloodHound#603]
**Describe the bug**
The prebuilt query for finding kerberoastable users with the most privileges is unable to return data within bloodhound, as the cypher query does not return a node object. However, the cypher query does return data within neo4j as a table of values.

**Screenshots**
![image](https://user-images.githubusercontent.com/114900731/199193512-4202c20f-3b5f-4ac6-b31b-a915f4b409b9.png)

**Additional context**
The query: (BloodHound\src\components\SearchContainer\Tabs\PrebuiltQueries.json -line 225)
``` MATCH (u:User {hasspn:true}) OPTIONAL MATCH (u)-[:AdminTo]->(c1:Computer) OPTIONAL MATCH (u)-[:MemberOf*1..]->(:Group)-[:AdminTo]->(c2:Computer) WITH u,COLLECT(c1) + COLLECT(c2) AS tempVar UNWIND tempVar AS comps RETURN u.name,COUNT(DISTINCT(comps)) ORDER BY COUNT(DISTINCT(comps)) DESC ```
Can be changed to: 
``` MATCH (u:User {hasspn:true}) OPTIONAL MATCH (u)-[:AdminTo]->(c1:Computer) OPTIONAL MATCH (u)-[:MemberOf*1..]->(:Group)-[:AdminTo]->(c2:Computer) WITH u,COLLECT(c1) + COLLECT(c2) AS tempVar UNWIND tempVar AS comps RETURN u,COUNT(DISTINCT(comps)) ORDER BY COUNT(DISTINCT(comps)) DESC ```

By changing RETURN u.name to RETURN u, the Cypher query will return node objects that can be displayed within BloodHound
![image](https://user-images.githubusercontent.com/114900731/199196122-fd4e1f00-930b-4604-a8ad-fc2334012e1c.png)

**Comment by JonasBK** [comment]
Closing - Fixed in 4.3.1 🥳
