### ISSUE TITLE
Using deprecated key addition command which no longer works to install neo4j

### ISSUE THREAD

**Issue by jasong-cyqual** [BloodHoundAD/BloodHound#608]
**Describe the bug**
Step 1 in the instructions to install Neo4j is no longer valid which prevents successful installation.

**To Reproduce**
1. Follow Step 1 of Neo4j install

**Expected behavior**
Installation of Neo4j

**Additional context**
Consider replacing with:
wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo gpg --dearmor | sudo tee /usr/share/keyrings/neotechnology.gpg.key > /dev/null

**Comment by JonasBK** [comment]
Hey @jasong-cyqual,

Thanks for your suggestion. Total linux noob here, but it looks like it is not working on my end?
![image](https://user-images.githubusercontent.com/12843299/235763646-ba5e1a23-a10b-4106-ac00-54798cae16e5.png)

**Comment by JonasBK** [comment]
Closing - Installation instructions for Linux have been updated and verified
