### ISSUE TITLE
Collect all the required information offline via ntds.dit

### ISSUE THREAD

**Issue by nwf9** [BloodHoundAD/BloodHound#61]
Hi Guys,

It was important to retrieve all the information if you are off network and you have the ntds.dit. You can check this project https://github.com/ANSSI-FR/AD-control-paths/blob/master/README.md

**Comment by Meatballs1** [comment]
Don't think ADCP pulls directly from NTDS.dit

**Comment by nwf9** [comment]
You can use adcp directly from NTDS.dit

**Comment by Meatballs1** [comment]
Provides instructions to mount it etc - `dsamain.exe -allowNonAdminAccess -dbpath <ntds.dit path> -ldapPort 1234` etc, but not direct from file? Or is that what you meant? :)

**Comment by nwf9** [comment]
You are playing with those words :-). The dsamain use the ntds.dit file to mount the ldap part.

**Comment by wifiuk** [comment]
i would be interested in a way to run bloodhound against an offline copy of AD.
Is that currently possible?

**Comment by rvazarkar** [comment]
How much information is actually available in NTDS? At best you could collect Group Membership and ACL information unless I'm missing something, because both local admins and sessions are per-server.

**Comment by maaaaz** [comment]
@rvazarkar I confirm that can dump Groups and ACLs from a remounted ntds (cf. https://github.com/BloodHoundAD/SharpHound/issues/12)

**Comment by rvazarkar** [comment]
This should be doable as of https://github.com/BloodHoundAD/SharpHound/issues/12
