### ISSUE TITLE
Domain trust information not working

### ISSUE THREAD

**Issue by matt-moses** [BloodHoundAD/BloodHound#614]
**Describe the bug**
Domain trust information is getting lost somewhere either in ingestion or failing to map on the UI. I have verified that SharpHound is collecting the domain trust information by reviewing the SharpHound JSON (see screenshots). After importing the SharpHound JSON files domain trust is not viewable.

**To Reproduce**
1. In a domain that holds trust in another domain, run SharpHound (1.1.0).
2. Import the SharpHound zip.
3. Using the BloodHound (4.2.0) menu option to "show domain trusts"

**Expected behavior**
Domain trusts are mapped onto the screen.

**Screenshots**
This screenshot is to verify that the trust information exists in the JSON.
![2022-11-12-075423_002](https://user-images.githubusercontent.com/8397647/202318416-6c234954-6186-42e0-909f-1d940acc2072.jpeg)

![2022-11-12-075825_002](https://user-images.githubusercontent.com/8397647/202319733-2cb7457c-cd94-4fd4-a1f0-7014f3a42ae3.png)

![2022-11-12-075513_002](https://user-images.githubusercontent.com/8397647/202319735-d0a35852-c59b-46eb-816e-0d9ed47c5bc8.png)

**Comment by matt-moses** [comment]
See also: https://bloodhoundhq.slack.com/archives/C20NG2L87/p1668635999102419

**Comment by matt-moses** [comment]
Reviewing the code and I'm definitely new here but wanted to throw out this lead...could it be related to the changes regarding moving from `oldingestion.js` to `newingestion.js`? Looks like the JSON produced from the latest SharpHound uses integers but the `newingestion.js` has moved to strings for denoting things like `TrustDirection` and `TrustType` which would cause these conditions to be unmet: https://github.com/BloodHoundAD/BloodHound/blob/master/src/js/newingestion.js#L795

See also https://github.com/BloodHoundAD/BloodHound/blob/master/src/js/newingestion.js#L3

**Comment by matt-moses** [comment]
Suggested work around:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/8397647/202615996-5e238793-500f-49db-8c0c-7476da16794f.png">

**Comment by dadevel** [comment]
I stumbled upon the issue today and automated the workaround in a small Python script: https://gist.github.com/dadevel/a8e7f5af88f659e99141e21011b1f37d
Maybe its helpful to someone.

**Comment by Pastea** [comment]
> I stumbled upon the issue today and automated the workaround in a small Python script: https://gist.github.com/dadevel/a8e7f5af88f659e99141e21011b1f37d Maybe its helpful to someone.
> 
> FYI: There's also an related issue open in [BloodHoundAD/SharpHound#33](https://github.com/BloodHoundAD/SharpHound/issues/33)

There is a typo on line 71, array should be TRUST_TYPES, not TRUST_DIRECTIONS

**Comment by dadevel** [comment]
@Pastea Thanks, I fixed it.

**Comment by JonasBK** [comment]
Hi @matt-moses,

Thanks for reporting the issue.

I think someone changed SharpHoundCommon without updating BloodHound 🙃 
It will be fixed with this commit: https://github.com/BloodHoundAD/BloodHound/commit/7d3c0fb02cee29f62f18ceb3f9460ce51c8b4a0e

I will close this issue when 4.3.1 is released.

**Comment by rvazarkar** [comment]
Should be fixed in 4.3.1

**Comment by matt-moses** [comment]
Thanks all!

**Comment by JonasBK** [comment]
Closing - Fixed in 4.3.1 🥳
