### ISSUE TITLE
Documentation update request: Neo4j install - AuthorizationManager check failed

### ISSUE THREAD

**Issue by clr2of8** [BloodHoundAD/BloodHound#615]
I'm requesting that you add a note to the neo4j install instructions for Windows that folks might need to "unblock" the install files. I got this error and needed to unblock all of the files before the install would work.

![image](https://user-images.githubusercontent.com/22311332/202582628-8103e986-b95c-4ead-bc3b-42c3a29d495f.png)

**Comment by hailnolly** [comment]
Hi @clr2of8, please can you advise how you unblocked the install files as I have the same issue.

**Comment by clr2of8** [comment]
The easiest way is to use the PowerShell cmdlet `Unblock-File` on the zip file before you unzip it as follows:

```powershell
Unblock-File Downloads\neo4j-community-4.4.14-windows.zip
```

**Comment by JonasBK** [comment]
Hi @clr2of8,

Whether you are allowed to run binaries from the Internet in PowerShell depends on the PowerShell Execution Policy. If the policy is too strict, you cannot run the bat file. Unblock-File works only if the policy is configured to RemoteSigned, but it won’t work for AllSigned. You could potentially change the PowerShell Execution Policy temporarily, but you will not be able to do that if it is configured on the machine level. The most reliable way to run the script from PowerShell is probably using one of the bypasses for PowerShell Execution Policy: https://www.netspi.com/blog/technical/network-penetration-testing/15-ways-to-bypass-the-powershell-execution-policy/.

Running a binary from PowerShell can be more complicated than running it from command prompt. The install instructions suggest command prompt, so if the user does that, they should not have to deal with PowerShell Execution Policy.

But thanks a lot for reporting this anyway. It is good to know that we should consider rewriting the install instructions to make it more straightforward in the future :)
