### ISSUE TITLE
How to Host Bloodhound Server on EC2 Public IP

### ISSUE THREAD

**Issue by arishwani** [BloodHoundAD/BloodHound#616]
Hi, 
Is there any documentation on how to host Bloodhound Server on EC2 Public so many users could login to it using the login page instead of just having it hosted on a localhost. 

Thank you 
Ari

**Comment by yellow-starburst** [comment]
Yeah you just change the neo4j conifg

**Comment by arishwani** [comment]
@yellow-starburst I did change the config file to be pointed to the Ec2 IP but not luck 

![image](https://user-images.githubusercontent.com/33989965/205929965-ef4ac3ee-763b-4fc5-8f23-c75f6474391c.png)
