### ISSUE TITLE
Performance in big corp environments

### ISSUE THREAD

**Issue by wintermute-** [BloodHoundAD/BloodHound#62]
Hello

After running the recently optimised ingestor for a day without stealth mode from a laptop on a corporate network with a complicated multinational AD structure, the resulting csvs had the following volumes: 
* group_memberships ~ 200 Mb
* local_admins ~ 6 Mb
* trusts ~ 5 Kb
* user_sessions ~ 60 Kb

The process to load group memberships into BloodHound has now been running continuously for about 72h and is showing at around 60% completion. Here are the database stats at this stage:
* Users ~ 40k loaded
* Computers ~ 24k loaded
* Groups ~ 76k loaded 
* Sessions ~ 600 loaded
* Relationships ~ 1.8 million loaded

Questions:
A) Is the long time required to load in the data expected behaviour due to volume?
B) Is the likely cause for the number of mapped sessions being so low due to the network segregation in place on the network? Note that the mapping of user sessions did not finish within a day.
C) Would anyone have further suggestions from practice on how to improve coverage / effectiveness in a large messy environment?

**Comment by rvazarkar** [comment]
That's definitely a huge database. I haven't really encountered anything of that size yet, so its difficult to write code to anticipate that. However, one of the unfortunate things about enforcing uniqueness constraints is that as the database size grows, the number of checks for uniqueness also grows. It's normal for the ingestion process to take longer as the db grows, but that sounds incredibly long. 

I would love to chat with you about it on the bloodhound slack channel if you have time.

As to questions B and C, I think those are better questions for @HarmJ0y

**Comment by rvazarkar** [comment]
I'll have a new version of the interface out in a couple weeks. I successfully tested ingesting a 360mb csv file through the UI. I'll update this post when I drop the new release officially

**Comment by th3grif7er** [comment]
I am in a similar boat to @wintermute- in terms of a large messy environment as well as the CSV sizes, but my user_sessions is substantially larger. 

group_memberships ~ 250 Mb
local_admins ~ 16 Mb
trusts ~ 3 Kb
user_sessions ~ 4.6 Mb

Everything loaded through the UI until I get to user_sessions. Then it hangs anywhere between 30%-45% and will just stay there for days. 

Is there a log written somewhere that I can look at to see what is hanging it? Is it actually hanging? or if I left it would it eventually process in?

**Comment by rvazarkar** [comment]
As soon as neo4j releases their new driver I'll have a fix out. Until then,
you can try and rig something up with load csv from the neo4j interface.

I'm not kidding when I say the code is already done, just needs the new
driver

**Comment by rvazarkar** [comment]
Hopefully this is fixed. Let me know otherwise
