### ISSUE TITLE
Proposed New Edge: DumpSMSAPassword

### ISSUE THREAD

**Issue by simondotsh** [BloodHoundAD/BloodHound#624]
## Context
A principal with administrative privileges on a computer with a Standalone Manged Service Account (sMSA) installed on it can retrieve the sMSA's password by dumping LSA secrets. This is not a new technique, but I documented [here](https://simondotsh.com/infosec/2022/12/12/assessing-smsa.html) how BloodHound could map this in the same fashion as `ReadGMSAPassword`.

## Proposed New Edge
**Name:** DumpSMSAPassword.
**Relationship Creation**: Enumerate sMSA with `objectClass=msDS-ManagedServiceAccount`. Create a relationship starting from the computer object matching the distinguished name stated in the sMSA attribute `msDS-HostServiceAccountBL` and link it to the sMSA.

## Contributing
If this edge is wanted, and the proposed way to implement it suits you, I can contribute the required changes, but will be waiting for the green light before doing so.

**Comment by JonasBK** [comment]
Excellent work, @simondotsh. Thanks a lot for sharing your research!
We definitely want that edge in BH, and it would be much appreciated if you would make pull requests for the feature.

**Comment by simondotsh** [comment]
Hey @JonasBK,

I've modified the required projects to introduce the edge.

**Comment by JonasBK** [comment]
Awesome! We will review it and keep you updated. 
Thank you so much for this great contribution!

**Comment by simondotsh** [comment]
Hi @JonasBK,

MS has documented the privileges required to delegate full access over sMSAs [here](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd548356(v=ws.10)?redirectedfrom=MSDN#delegating-managed-service-account-management). To install a fresh sMSA from an elevated prompt on a host, I only needed the `Reset password` and `Write account restrictions` privileges on the sMSA object in my lab.

After basic tests, I couldn't overwrite an already-installed sMSA, so it looks like you'd need to uninstall it from the host first using the same object privileges and local admin.

**Comment by JonasBK** [comment]
Gotcha. Thanks for the explanation and testing!

**Comment by JonasBK** [comment]
Hey @simondotsh, 

There are two minor things we want to change.
We would want the SMSA array to be renamed DumpSMSAPassword, so it is named the same as the edge. And then, we want to change it from a string array to a TypedPrincipal array.
![image](https://user-images.githubusercontent.com/12843299/228625526-ca23acb6-946b-45c9-a596-407b182838a1.png)

Would you be interested in making these changes? 

Completely understandable if you are not interested in rewriting your well-working PRs. We will make the changes in that case but will still credit you when releasing the next BloodHound version.

**Comment by simondotsh** [comment]
Hi @JonasBK,

I've pushed the required changes to the three pull requests; let me know if this does the job.

**Comment by JonasBK** [comment]
Awesome, @simondotsh!

It looks good :)

There are two minor things for BloodHound as well. 

1. I just noticed your comment here: https://github.com/BloodHoundAD/BloodHound/pull/626#issuecomment-1363408958
It is a good point. It would be great to have a check like that.

2. This line here is missing. It enables intellisense.
![image](https://user-images.githubusercontent.com/12843299/228870486-3f711a71-a11b-40cf-b12f-62aa4c54a0ab.png)

**Comment by simondotsh** [comment]
Hey @JonasBK,

Done!

**Comment by JonasBK** [comment]
Closing - Implemented in 4.3.1 🥳
