### ISSUE TITLE
Unable to upload AzureHound 1.2.2 collection

### ISSUE THREAD

**Issue by ag-michael** [BloodHoundAD/BloodHound#636]
Hi, 

I performed a collection using AzureHound 1.2.2. I cannot upload this using BloodHound 4.2.0, I'm getting the error below:

![image](https://user-images.githubusercontent.com/39683291/211853295-af7b7b20-3cb9-445b-9d4b-a09c5d05c880.png)

I could not find a later release of BloodHound or AzureHound. Can you please help me resolve this issue?

**Comment by TheConciergeDev** [comment]
I was facing the same issue - using BloodHound 4.1.1 it was possible to import my scan results (https://github.com/BloodHoundAD/BloodHound/releases/tag/4.1.1).

With 4.2 the team was re-writing the AzureHound collector - so I guess the import of the results has changed as well. I assume your collector (as was mine) is older.

Hope this helps! 

Cheerz!

**Comment by ag-michael** [comment]
@TheConciergeDev  It worked fine for me with the previous version of AzureHound, it started failing when I upgraded to 1.2.2. I just double checked to make sure.

**Comment by JonasBK** [comment]
Hi @ag-michael,

I will close this issue since we now have a new version of both AzureHound and Bloodhound. Let me know if you have any issues with the latest versions!
