### ISSUE TITLE
bloodhound 4.2.0 Darwin arm64 release not working

### ISSUE THREAD

**Issue by chadministratorwastaken** [BloodHoundAD/BloodHound#639]
**Describe the bug**
App does not run. Error message: "BloodHound.app” is damaged and can’t be opened.

**To Reproduce**
1. Download and unzip latest release
2. Click on BloodHound.app
3. See error

**Expected behavior**
Expect BloodHound application to launch to login screen

**Screenshots**
![image](https://user-images.githubusercontent.com/50153561/212166239-aec56f03-967b-44e6-bc95-a28ae326811c.png)

**Additional context**
Darwin HOSTNAME.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64

A similar issue (#504) was closed for v4.1.0.

**Comment by Tw1sm** [comment]
Same issue, app works fine once compiled manually with the commands in the v4.1.0 issue

**Comment by NotMedic** [comment]
Check whether the file is quarantined by GateKeeper. This can be done with 

`ls -l@ ./BloodHound.app`

if you see the Extended Attribute of 'com.apple.quarantine', you can remove it with:

`xattr -d com.apple.quarantine ./BloodHound.app`

Try that and report back?

**Comment by chadministratorwastaken** [comment]
Great success!  Thank you for the solution.

**Comment by JonasBK** [comment]
Is this still an issue with the 4.3 release?

**Comment by chadministratorwastaken** [comment]
@JonasBK Yes

**Comment by njmulsqb** [comment]
<img width="615" alt="image" src="https://github.com/BloodHoundAD/BloodHound/assets/47940898/57b20680-38b9-41a4-9e76-6bdaa16154fd">
Not working on M2
