### ISSUE TITLE
White Screen on loading

### ISSUE THREAD

**Issue by FlappyCheese** [BloodHoundAD/BloodHound#649]
If this is a SharpHound bug, please file the bug in the SharpHound repo [here](https://github.com/BloodHoundAD/SharpHound)

**Describe the bug**
In Kali linux, launching ./BloodHound will launch however it will just launch a white page, in the terminal the following text. 

/BloodHound
(node:24084) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information

**To Reproduce**
1. Go to terminal
2. start your neo4j, sudo neo4j console
3. in another terminal window, launch your bloodhound gui ./BloodHound
4. See the blank white page.

**Expected behavior**
A login prompt to BloodHound GUI

**Screenshots**

**Additional context**
Add any other context about the problem here. If this bug is in the UI, open the console using Ctrl + Shift + I and see if there's any errors to attach here.
![Screenshot from 2023-03-06 14-00-21](https://user-images.githubusercontent.com/55724496/223009609-88653885-2df3-4515-8bec-b1ab9e53265e.png)

**Comment by FlappyCheese** [comment]
HI as a work around i used sudo apt install bloodhound and that seems to work. but dont know how often the kali app is updated.

**Comment by JonasBK** [comment]
Hi FlappyCheese,

Thanks for posting your fix!

I do not know how often BloodHound, Neo4j, etc., are updated in Kali, but there seem to be some issues with incompatible versions at least in some releases of Kali.
