### ISSUE TITLE
neo4j database format migration for sample db

### ISSUE THREAD

**Issue by gitcomrade** [BloodHoundAD/BloodHound#65]
When using the latest version of neo4j community edition (3.1.0) there's a database format issue preventing loading the BloodHoundExampleDB.graphdb file.  This issue prevents users from loading the example db and this is the error message:  
![image](https://cloud.githubusercontent.com/assets/24595021/21241734/b5a3d63a-c2d6-11e6-80e7-565492b5b62c.png)

This can be fixed by going into your [neo4jroot]/conf/neo4j.conf file and uncommenting out the line: 
dbms.allow_format_migration=true

Then you should be able to log into BloodHound over http://localhost:7687 instead of the suggested bolt:// connection.

Also, can you guys pretty please update your getting started documentation on the wiki?  Here are some people who've done a decent job in that regard.
http://blog.cobaltstrike.com/2016/12/14/my-first-go-with-bloodhound/
https://popped.io/setting-up-bloodhound-on-debian-jessie/
https://www.shellandco.net/understand-privilege-relationships-active-directory-environment/

**Comment by rvazarkar** [comment]
Authentication is fixed
