### ISSUE TITLE
Unable to upload big size collection file

### ISSUE THREAD

**Issue by dhazh007** [BloodHoundAD/BloodHound#651]
If this is a SharpHound bug, please file the bug in the SharpHound repo [here](https://github.com/BloodHoundAD/SharpHound)

**Describe the bug**

I'm having trouble uploading my SharpHound output to the BloodHound database.
Except for large Sharphound output, small sizes may be uploaded without trouble.
I attempted to upload a 21MB file, but I couldn't because it took too long to complete each component or was obstructed while uploading.

Appreciate if you could resolve or fix this issue asap.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If this bug is in the UI, open the console using Ctrl + Shift + I and see if there's any errors to attach here.

**Comment by dhazh007** [comment]
Please note that I have no problem with previous versions of bloodhound.

**Comment by yellow-starburst** [comment]
https://gist.github.com/deltronzero/7c23bacf97b4b61c7a2f2950ef6f35d8
