### ISSUE TITLE
Is the Neo4j 4.4.13 requirement actually accurate or should this read as 4.4.19?

### ISSUE THREAD

**Issue by kaydaskalakis** [BloodHoundAD/BloodHound#657]
Available current options for download only include 

Neo4j Community Edition 5.6.0 and
Neo4j Community Edition 4.4.19 [LTS]

https://neo4j.com/download-center/#community

**Comment by JonasBK** [comment]
Hi Kay,
The latest 4.4.x version usually works. Did you test with 4.4.19?

**Comment by kaydaskalakis** [comment]
Hi there Jonas, thank you! Yes it works with 4.4.19, I am referring to the article in the guide which still refers to 4.4.13 in the warning under [Neo4j 4.4.13](https://bloodhound.readthedocs.io/en/latest/installation/windows.html#install-neo4j). Perhaps this should be edited to reflect the 4.4.19 version or changed to 4.4.x for accuracy?

**Comment by JonasBK** [comment]
Thanks a lot, Kay! :)
