### ISSUE TITLE
Chrome blocks the download and G Data reports virus

### ISSUE THREAD

**Issue by LHBL2003** [BloodHoundAD/BloodHound#673]
The provided x64 releases cannot be downloaded without problems. Either Chrome blocks the download or the anti-virus programs sound an alarm.

**Comment by JonasBK** [comment]
Hi @LHBL2003,

That is correct, many browsers and AVs will flag BloodHound as malicious as it can be abused for malicious intent. We can not change that. To use BloodHound, you will have to use an OS where you are safe to allow-list BloodHound or disable the security features that flag it.
