### ISSUE TITLE
Exception calling InvokeMember...Format of the specified domain name is invalid

### ISSUE THREAD

**Issue by pendraggon87** [BloodHoundAD/BloodHound#68]
I am receiving the following errors:

VERBOSE: Error with translate init in Convert-ADName: Exception calling "InvokeMember" with "5" argument(s): "The
format of the specified domain name is invalid. (Exception from HRESULT: 0x800704BC)"
VERBOSE: Error with translate Set/Get in Convert-ADName: Exception calling "InvokeMember" with "5" argument(s): "Nam
translation: Could not find the name or insufficient right to see name. (Exception from HRESULT: 0x80072116)"

I am letting the tool continue to run, but unsure if this will result in incomplete data.

**Comment by rvazarkar** [comment]
We don't use Convert-ADName in the new ingestor, and it shouldn't cause many problems anyways. I'm closing this issue, since this is just a standard error we get during enumeration
