### ISSUE TITLE
Display current version information

### ISSUE THREAD

**Issue by sin9yt** [BloodHoundAD/BloodHound#696]
**Is your feature request related to a problem? Please describe.**
It would be a nice addition to display the current version of the bloodhound server within the UI. Currently, the only known way is to use the api/version endpoint to find the version. Displaying this info would make it easier when one needs to upgrade to a newer version.

**Describe the solution you'd like**
I personally favor adding a new section within the 'Administration' Menu, similar to 'About' menu that chrome uses to display the version information. 

**Describe alternatives you've considered**
Another way would be  display within the dropdown in a smaller font when a user clicks on the settings button in the top right.

**Comment by executionByFork** [comment]
Are you talking about this? There is a button on the right labeled with an `i` that pulls this up in the GUI. If you are talking about displaying the Neo4j version, you can see that with the `neo4j version` command.

![image](https://github.com/user-attachments/assets/ac742573-1a6f-4250-b833-df8bc23e80ad)

**Comment by sin9yt** [comment]
I'll close this issue, I had mistakenly raised the issue in this repo instead of the new bloodhound repo.

 I created the same issue in the new repo and they recently built that feature and merged it, so all good now.
