### ISSUE TITLE
Zip File not loading

### ISSUE THREAD

**Issue by dwalter0** [BloodHoundAD/BloodHound#700]
If this is a SharpHound bug, please file the bug in the SharpHound repo [here](https://github.com/BloodHoundAD/SharpHound)

**Describe the bug**
When I attempt to load a .zip file produced by SharpHound, The Upload Progress pane is shown but nothing is uploaded, all items remain at 0%.

**To Reproduce**
1. In an Active Directory domain run SharpHound v2.0.1 with the "-c all" flag. This produces a zip file.
2. Transfer the zip file via SMB onto the linux host running BloodHound
3. Run BloodHound --no-sandbox and log into neo4j
4. Drag and drop the zip file onto the bloodhound window.
5. The Upload Progress pane is shown but no progress is made.

**Expected behavior**
The json files in the zip file are uploaded and the graphs of the AD domain are shown.

**Screenshots**
![image](https://github.com/BloodHoundAD/BloodHound/assets/1719888/cf49b75e-f129-4306-859c-97b3260632c7)

**Additional context**
I've had some idea that this was a version issue so have tried the kali apt version of bloodhound as well as the last 3 releases from github and a couple of olde random ones. I have also tried different combinations of older versions of SharpHound all with the same result. I have attached one of the SharpHound v2.0.1 zip files that isn't working for me in BloodHound.
[20231127035041_BloodHound.zip](https://github.com/BloodHoundAD/BloodHound/files/13467470/20231127035041_BloodHound.zip)

**Comment by JonasBK** [comment]
Hi,

SharpHound v2.x is only compatible with BloodHound CE (v5.x) which you can find here: https://github.com/SpecterOps/BloodHound

The application does not have a nice way of telling you that it does not understand the data format, unfortunately..

**Comment by jibinge0rge** [comment]
<img width="536" alt="image" src="https://github.com/user-attachments/assets/b2796076-82cc-40b2-9b5b-5ba568c1ea90">

While trying to upload zip to BloodHound i'm facing this issue. I'm using the latest version of SharpHound and BloodHound

**Comment by r4nd0m4rest** [comment]
Hi @JonasBK, 
Thank you for posting that information!

So what you're saying is that SharpHound collections using the most up-to-date version of SharpHound (v2.5.8) will not work with the most up-to-date version of BloodHound (v6.2.2)?

If so, that is pretty frustrating.
- Does SpectorOps have a list of showing compatible versions of Sharphound and Bloodhound?
- **GOAL:** What version of SharpHound do I need to use with my Bloodhound v4.3.1 from Kali Linux?

As of today (2024-11-29),
- most up-to-date SharpHound = v2.5.8
- most up-to-date BloodHound CE (by Spector Ops) = v6.2.2
- most up-to-date BlooudHound (for Kali) = v4.3.1
![20241129_bloodhound-upload-issue](https://github.com/user-attachments/assets/46d5195f-ce0d-4dd7-878d-23742b94ca5e)

**Comment by JonasBK** [comment]
We recommend using the latest version of SharpHound with the latest version of BloodHound CE. If you are on legacy BH (v4.3.1 or earlier), then you need to use the SH collector of v1.1.0 (or earlier).
