### ISSUE TITLE
can't upload files

### ISSUE THREAD

**Issue by k-0-i** [BloodHoundAD/BloodHound#704]
If this is a SharpHound bug, please file the bug in the SharpHound repo [here](https://github.com/BloodHoundAD/SharpHound)
[20240218092224_blood.zip](https://github.com/BloodHoundAD/BloodHound/files/14321565/20240218092224_blood.zip)

**Screenshots**
![image](https://github.com/BloodHoundAD/BloodHound/assets/95953449/e97ad634-0cbf-4619-b61c-0806f0cb8173)

**Comment by ab2pentest** [comment]
Facing the same issue, but after attempting to upload files one by one, I discovered that the problem lies within the file `{datetime}_computers.json`.

I believe this is a SharpHound bug.

**Comment by JonasBK** [comment]
Hi!

This repo is the legacy version BloodHound which is no longer maintained. It is only compatible with SharpHound v1.x.
The new BloodHound Community Edition, which is compatible with SharpHound of version v2.x, can be found here: https://github.com/SpecterOps/BloodHound
