### ISSUE TITLE
When I click on WriteDacl help bloodhound  a white screen will appear

### ISSUE THREAD

**Issue by helloyw** [BloodHoundAD/BloodHound#705]
When I click on WriteDacl help bloodhound, a white screen will appear
<img width="774" alt="image" src="https://github.com/BloodHoundAD/BloodHound/assets/32027872/5b8381b5-8fcf-4c8b-be82-b36f5f4c3346">
<img width="1791" alt="image" src="https://github.com/BloodHoundAD/BloodHound/assets/32027872/d64e8b37-cf38-4332-81e1-6a5581a2008f">
I am using Kali's built-in Bloodhound
This is an error in the ctrl+shift+i console
`bundle.js:53 Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=zT for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at bundle.js:53
    at Ni (bundle.js:53)
    at ys (bundle.js:53)
    at lc (bundle.js:53)
    at sc (bundle.js:53)
    at Xs (bundle.js:53)
    at bundle.js:53
    at t.unstable_runWithPriority (bundle.js:61)
es @ bundle.js:53
n.callback @ bundle.js:53
da @ bundle.js:53
as @ bundle.js:53
fc @ bundle.js:53
t.unstable_runWithPriority @ bundle.js:61
Vo @ bundle.js:53
dc @ bundle.js:53
Xs @ bundle.js:53
(anonymous) @ bundle.js:53
t.unstable_runWithPriority @ bundle.js:61
Vo @ bundle.js:53
zo @ bundle.js:53
$o @ bundle.js:53
D @ bundle.js:53
Kt @ bundle.js:53
bundle.js:32 Uncaught Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=zT for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at bundle.js:53
    at Ni (bundle.js:53)
    at ys (bundle.js:53)
    at lc (bundle.js:53)
    at sc (bundle.js:53)
    at Xs (bundle.js:53)
    at bundle.js:53
    at t.unstable_runWithPriority (bundle.js:61)
(anonymous) @ bundle.js:32
Error @ bundle.js:37
(anonymous) @ bundle.js:53
Ni @ bundle.js:53
ys @ bundle.js:53
lc @ bundle.js:53
sc @ bundle.js:53
Xs @ bundle.js:53
(anonymous) @ bundle.js:53
t.unstable_runWithPriority @ bundle.js:61
Vo @ bundle.js:53
zo @ bundle.js:53
$o @ bundle.js:53
D @ bundle.js:53
Kt @ bundle.js:53`

**Comment by JonasBK** [comment]
Hi,
I believe this was fixed in v4.3.1. However, we no longer maintain the codebase of the legacy version of BloodHound. Check out the maintained BloodHound Community Edition here: https://github.com/SpecterOps/BloodHound
