### ISSUE TITLE
Add New control path

### ISSUE THREAD

**Issue by nwf9** [BloodHoundAD/BloodHound#71]
Hi guys, 

Is it possible to modify the ingestor to check if they have LAPS installed and if the DC is writable or readable only ( RODC )

**Comment by andyrobbins** [comment]
Hi nwf9,

Thanks for the control path addition suggestion. We are very slowly expanding the schema to include additional control paths; however, LAPS presence and read privileges on the ms-Mcs-AdmPwd attribute is not currently one of those we have on deck. I expect we'll add this in at some point in the coming months.

Can you expand a little more on your suggestion regarding writable vs read-only domain controllers?

**Comment by nwf9** [comment]
Hi Andy,

It's correct about the LAPS attribute because lot of company use those attributes. You can have the same point of view for the read only domain control attribute like : 

- msDS-NeverRevealGroup
- msDS-RevealOnDemandGroup
- managedby


https://msdn.microsoft.com/en-us/library/cc223662.aspx





https://msdn.microsoft.com/en-us/library/cc223662.aspx

**Comment by rvazarkar** [comment]
We've added functionality in 2.0 to reveal principals that can read the LAPS password
