### ISSUE TITLE
Add proxy support for Export-BloodHoundData and 32bits powershell

### ISSUE THREAD

**Issue by fBdoFM** [BloodHoundAD/BloodHound#77]
Hi,

Please add proxy support for Export-BloodHoundData. I wrote it this way:
--
$proxy = [System.Net.WebRequest]::GetSystemWebProxy()
$proxy.Credentials = [System.Net.CredentialCache]::DefaultCredentials
	
$WebClient = New-Object System.Net.WebClient
$WebClient.proxy = $proxy
        if($PSBoundParameters['Credential']) {
            $BloodHoundUserName = $Credential.UserName
            $BloodHoundPassword = $Credential.GetNetworkCredential().Password
            $Base64UserPass = [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($BloodHoundUserName + ':' + $BloodHoundPassword))
---
Sorry for quick copy/paste.

Also if running in a 32bits powershell BloodHound will crash so you should check first the environement. [System.Environment]::Is64BitProcess

Thanks

**Comment by rvazarkar** [comment]
This should no longer be necessary. The new ingestor is compiled using AnyCPU so should run on either environment. You can find it here:

https://github.com/BloodHoundAD/SharpHound/releases

Additionally it should respect proxy rules. If not, open an issue on that repo. Thanks!
