### ISSUE TITLE
You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by dandan112** [BloodHoundAD/BloodHound#79]
Getting this message on both the master and ingestor_tune up scripts.  The groupmemberships.csv file only gets to 684kb.  

You cannot call a method on a null-valued expression.
At C:\BloodHound-master\PowerShell\new\BloodHound.ps1:5191 char:55
+                                 $GroupWriter.WriteLine <<<< ("`"$GroupName@$GroupDomain`",`"$AccountName`",`"$ObjectT
ype`"")
    + CategoryInfo          : InvalidOperation: (WriteLine:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by rvazarkar** [comment]
Hopefully you shouldn't have the same issue with the new ingestor:

https://github.com/BloodHoundAD/SharpHound
