### ISSUE TITLE
Feature Request - Don't include Disabled users by default in pathfinding

### ISSUE THREAD

**Issue by jeffmcjunkin** [BloodHoundAD/BloodHound#80]
In recent testing, a number of paths to Domain Admin included disabled users, which make for a non-working path to domain admin.

I've been using release 1.2 (https://github.com/adaptivethreat/BloodHound/releases/tag/1.2).

**Comment by rvazarkar** [comment]
This is actually an ingestor issue, we don't currently filter out disabled users. @HarmJ0y might want to take a look at this

**Comment by jeffmcjunkin** [comment]
Update: https://github.com/rvazarkar/Sharphound2 filters out disabled users, so a workaround is to use that project for ingestion.

**Comment by rvazarkar** [comment]
As an update to this, SharpHound does not filter out disabled users any more, but using Object Properties, it is possible to filter them out of attack paths. It's not set that way by default, but maybe we'll look into some kind of setting to filter them out

**Comment by jeffmcjunkin** [comment]
My $0.02: it'd be ideal if searching disabled objects was an available option, but the default was to exclude disabled users and computers in attack paths.

I'm excited about the 1.4 release and Sharphound2 going out of beta -- great work!

**Comment by rvazarkar** [comment]
A disabled user in an attack path can be re-enabled, making the attack path valid. We're going to leave the functionality as is.
