### ISSUE TITLE
Error while launching BloodHound.ps1 from BloodHound/PowerShell

### ISSUE THREAD

**Issue by str4n63r** [BloodHoundAD/BloodHound#83]
Dear @HarmJ0y ,

Below is the error encountered while running **Bloodhound.ps1**
**Operating System:** Windows 2012 R2 Standard (build:9600)
**Architecture:** 64-Bit OS with local administrative privileges
**Error Reference Link:** [http://pastebin.com/tic7xKn1](http://pastebin.com/tic7xKn1)

**PS:** I enabled Powershell execution bypass policy on the machine

Help really appreciated.

Thanks & regards,
str4n63r

**Comment by rvazarkar** [comment]
You downloaded the html version. You need to download the raw version.

**Comment by str4n63r** [comment]
@rvazarkar Thanks for the intimation. Will try again.

**Comment by str4n63r** [comment]
@rvazarkar This time the import was successful. But when I tried collecting data using **Get-BloodHoundData** module I didn't see an option **Export-BloodHoundCSV** after **|** symbol. So I tried directly running **Get-BloodHoundData** which resulted in below error.

**Error Link:** [http://pastebin.com/vDceYxLv](http://pastebin.com/vDceYxLv)

**Comment by rvazarkar** [comment]
The command for the ingestor has changed as of the newest version. You can see the new documentation on the wiki.

https://github.com/BloodHoundAD/BloodHound/wiki/PowerShell-Ingestor

**Comment by andyrobbins** [comment]
@str4n63r:

In the error output you pasted, the following line gives the best clue as to what's going on:

`Current security context is not associated with an Active
Directory domain or forest.`

This leads me to believe that you're running the ingestor (the BloodHound.ps1 you downloaded and imported into PowerShell) from a local user context, not from a domain user context. Re-try once you have a domain user context.

**Comment by str4n63r** [comment]
@rvazarkar  Will follow the new documentation and try.

@andyrobbins  There was one more user which belongs to domain XXX named 'Administrator' and I choose the wrong 'Administrator' user which is a local admin user. That is why it is saying 
**Current security context is not associated with an Active Directory domain or forest.**
Thanks a lot for the insight. You saved my time.

**Comment by rvazarkar** [comment]
Closing this for now
