### ISSUE TITLE
Feature Request - Add Local Admin Query

### ISSUE THREAD

**Issue by DavOz** [BloodHoundAD/BloodHound#84]
There's currently a query for the top 10 accounts with local admin rights but not all users and all machines with local admin rights. Could you create a query that will scan every machine and display which users have local admin rights?

Thank you!

**Comment by andyrobbins** [comment]
@DavOz:

Thanks for the feature suggestion. Can you explain a little more what the end-result you're looking for is? Do you want to know every single computer, group and user that has local admin rights anywhere in the domain?

**Comment by DavOz** [comment]
Sure - I want the graph  to show every computer or server in the domain and then show which group or users have direct local admin to that machine. Basically just a query against each machine to show who's in the local admin group. Thanks!

**Comment by andyrobbins** [comment]
@DavOz: sorry for the extended delay on this issue. I have a way to generate a chart that I think will provide what you're looking for here. Look for a blog post on the SpecterOps blog in the coming months for that.
