### ISSUE TITLE
Feature request: compare groups

### ISSUE THREAD

**Issue by jackassplus** [BloodHoundAD/BloodHound#85]
In a recent test, I had found two groups in the domain that are _nearly_ identical to the domain admins group. A way to easily compare these groups would be swell. Specifically the intersection and the inverse:
(A union B) - (A intersection B)

**Comment by rvazarkar** [comment]
I dont think theres any easy way to implement this in the UI. I'm closing it for now, but if I come up with a solution to the problem, I'll re-open it 👍
