### ISSUE TITLE
Empty user_sessions.csv and trusts.csv

### ISSUE THREAD

**Issue by CaledoniaProject** [BloodHoundAD/BloodHound#86]
I'm testing BloodHound with multiple VMs, I have 3 boxes and two users.

1. user `admin` belongs to `domain admin` and logged on host1
2. user `aaron` belongs to `domain user` and logged on host2, 
    and `aaron` can logon to host1, and is a local administrator.

Now on host2, I can verify userhunter works:

```
PS c:\test\powersploit> Invoke-UserHunter
UserDomain      : CORP
UserName        : admin
ComputerName    : WIN2008-APP.corp.aaron.com
IPAddress       : 172.16.177.150
SessionFrom     :
SessionFromName :
LocalAdmin      :

UserDomain      : CORP
UserName        : admin
ComputerName    : WIN2008-APP.corp.aaron.com
IPAddress       : 172.16.177.150
SessionFrom     :
SessionFromName :
LocalAdmin      :
```

But when I use BloodHound,

```
PS c:\test\BloodHound-master\PowerShell> Get-BloodHoundData
Writing output to CSVs in: c:\test\BloodHound-master\PowerShell\
Done writing output to CSVs in: c:\test\BloodHound-master\PowerShell\
```

The `user_sessions.csv` and `trusts.csv` is both empty, only one line containing the CSV header.

Any ideas?  Perhaps I'm wrong about how bloodhound works.

**Comment by c0d3xpl0it** [comment]
Try using below commands.
Import-Module .\BloodHound.ps1
Get-BloodHoundData | Export-BloodhoundCSV

**Comment by CaledoniaProject** [comment]
@c0d3xpl0it There's no such function in master branch.

https://github.com/BloodHoundAD/BloodHound/blob/master/PowerShell/BloodHound.ps1

Did I miss something?

**Comment by CaledoniaProject** [comment]
Perhaps I should use `Invoke-BloodHound`?

**Comment by rvazarkar** [comment]
So sessions from an unprivileged session is grabbed using NetUserSessionEnum, which will only return sessions established over the network. Examples are remote logins or file share access. BloodHound also filters out your current user to avoid false positives. 

If you have admin, you can enumerate whose logged in locally using the following:

>Invoke-BloodHound -CollectionMethod LoggedOn

**Comment by jackassplus** [comment]
I'm having a similar problem. If I run Get-NetSession, I get data back, but it isn't in either the CSV or sent to the RestAPI if I just run it via Get-BloodhoundData

**Comment by rvazarkar** [comment]
Are those sessions you're getting back local users? Because BloodHound filters those out and only looks at domain users

**Comment by jackassplus** [comment]
Not all of them. For instance, against the PDC, I get a mix of computer accounts and domain/service accounts. I see no local accounts. (Unless there are identically named local accounts, but this seems unlikely)

**Comment by rvazarkar** [comment]
Very strange. Are you in the BloodHound Slack channel?

**Comment by jackassplus** [comment]
I'm not. There is an extremely unlikely possibility that there really ARE no sessions other than the service accounts AND there is an identically named local account....

**Comment by Jimfa** [comment]
I'm having a remarkably similar problem in a virtual domain, where no domain sessions or users are returned (except for one user who is a member of the domain_admins group, while several others are simply logged in on domain accounts). Was there any resolution to this? I notice last update was 19 days ago - curious for any feedback.

**Comment by rvazarkar** [comment]
If there aren't any network sessions, it won't find them. Network sessions are for file shares and whatnot. If you have local admin on the systems, try the LoggedOn collection method.

**Comment by rvazarkar** [comment]
I'm going to go ahead and close this issue for now
