### ISSUE TITLE
Feature Request: Expose Pre-Built Analytics Queries in Raw Query Bar

### ISSUE THREAD

**Issue by ryanohoro** [BloodHoundAD/BloodHound#87]
To give users better insight into the Cypher query language, I would suggest copying the contents of the pre-built queries to the raw query bar so that they can be examined and modified if desired.

The Cypher language is opaque within the BloodHound interface and this should expose end users to the possibility of running customized queries.

```
Find all Domain Admins
Find Shortest Paths to Domain Admins
Find Top 10 Users with Most Sessions
Find Top 10 Computers with Most Sessions
Find Top 10 Users with Most Local Admin Rights
Find Top 10 Computers with Most Admins
Users with Foreign Domain Group Membership
Groups with Foreign Domain Group Membership
Map Domain Trusts
```

**Comment by rvazarkar** [comment]
I'll likely implement this across the board in the form of an option in the settings, something like "Expose Raw Queries"

**Comment by rvazarkar** [comment]
Fixed in https://github.com/BloodHoundAD/BloodHound/commit/aac115721bb3ae9133dec3b2f0804e0b48f6687c
