### ISSUE TITLE
sudo should not be used in step 4 of Linux and MacOS build instructions

### ISSUE THREAD

**Issue by seanthegeek** [BloodHoundAD/BloodHound#88]
While `sudo` is needed to install `electron-packager` globally ( the `-g` switch), sudo should not me used with the normal `npm install command` as currently shown in the wiki.

https://github.com/BloodHoundAD/BloodHound/wiki/Building-BloodHound-from-source

**Comment by andyrobbins** [comment]
Thank you, fixed
