### ISSUE TITLE
Feature: Import AD Explorer snapshots

### ISSUE THREAD

**Issue by aress31** [BloodHoundAD/BloodHound#89]
Hi,

Just got a look into BloodHound and it looks very promising. I can clearly see a need for it for internal engagements. However, usually when I get valid credentials through Responder; open shares or whatever, I then take a snapshot of the AD state using AD Explorer from the Sysinternal suite. 

I think that (if possible) adding a feature to populate the DB or import this AD Explorer snapshot for use with BloodHound would be a nice addition.

Regards,
Alex

**Comment by Meatballs1** [comment]
Have you got any documentation on AD Explorer snapshot format? I've looked into it but its never been very clear!

**Comment by rvazarkar** [comment]
I've never used AD explorer before, so I would definitely need more information as @Meatballs1 said.

**Comment by HarmJ0y** [comment]
I second @Meatballs1 - I've looked but never found documentation on the AD Explorer snapshot binary format. It would likely be non-trivial to reverse the format.

**Comment by rvazarkar** [comment]
The format appears to be proprietary, so I'm going to close this issue

**Comment by c3c** [comment]
I made an implementation that's available at https://github.com/c3c/ADExplorerSnapshot.py

Might need some beta-testing :)
