### ISSUE TITLE
The dot dot dot animation ... eg: SQL2.EXTERNAL.LOCAL

### ISSUE THREAD

**Issue by KaptainKool** [BloodHoundAD/BloodHound#90]
In the demo data, when clicked on the node: SQL2.EXTERNAL.LOCAL, the Group Delegated Local Admin & Derivate Local Admin do not fill out with a numeric value, rather they have the dot-dot-dot animation play out. 

From a UI perspective I am not sure if I should read that as a "0"  or continue waiting for it to do its crunching ... just that it never ends.

**Comment by rvazarkar** [comment]
![image](https://cloud.githubusercontent.com/assets/5720446/23912497/2cf8aa92-08b6-11e7-8237-91176f746290.png)

I can't seem to recreate this. Do you have any more information?

**Comment by KaptainKool** [comment]
<img width="487" alt="screenshot" src="https://cloud.githubusercontent.com/assets/13147402/23916622/d0b16050-0912-11e7-8383-6e3fdc345783.png">

**Comment by KaptainKool** [comment]
Example above. Stock install on a Kali VM with 2GB RAM.

**Comment by KaptainKool** [comment]
Additionally running "neo4j console", I see the below print on the terminal screen, when I click to select on the node SQL2.EXTERNAL.LOCAL in BloodHound.



2017-03-14 18:40:54.679+0000 ERROR Client triggered an unexpected error [ExecutionFailed]: The shortest path algorithm does not work when the start and end nodes are the same. This can happen if you
perform a shortestPath search after a cartesian product that might have the same start and end nodes for some
of the rows passed to shortestPath. If you would rather not experience this exception, and can accept the
possibility of missing results for those rows, disable this in the Neo4j configuration by setting
`cypher.forbid_shortestpath_common_node` to false. If you cannot accept missing results, and really want the
shortestPath between two common nodes, then re-write the query using a standard Cypher variable length pattern
expression followed by ordering by path length and limiting to one result.. See debug.log for more details, reference 0fdddfb2-f5b1-476d-940c-17619f4f76e0.
2017-03-14 18:40:54.823+0000 ERROR Client triggered an unexpected error [ExecutionFailed]: The shortest path algorithm does not work when the start and end nodes are the same. This can happen if you
perform a shortestPath search after a cartesian product that might have the same start and end nodes for some
of the rows passed to shortestPath. If you would rather not experience this exception, and can accept the
possibility of missing results for those rows, disable this in the Neo4j configuration by setting
`cypher.forbid_shortestpath_common_node` to false. If you cannot accept missing results, and really want the
shortestPath between two common nodes, then re-write the query using a standard Cypher variable length pattern
expression followed by ordering by path length and limiting to one result.. See debug.log for more details, reference 5f62f9a5-357d-43ba-a3d1-8df761800ca6.

**Comment by rvazarkar** [comment]
Interesting. Will take a look at this.

**Comment by rvazarkar** [comment]
Looks like this behavior was introduced in 3.1.2 of neo4j which is why we haven't seen it before. Will try and find a fix/workaround

**Comment by KaptainKool** [comment]
Thank you ! 

To avoid running into it, what's the recommended/safe version of neo4j to use with the current version of BloodHound ?

Team ATD rocks  & thanks for the great tool.

**Comment by rvazarkar** [comment]
3.1.1 should work fine until we get a fix for this out. Or you can add the configuration suggested in the error.

**Comment by johnmccash** [comment]
The neo4j error message has a mistake in it! It's not "cypher.forbid_shortestpath_common_node=false", but rather "cypher.forbid_shortestpath_common_nodes=false"

**Comment by rvazarkar** [comment]
As of the 1.4 release, this should be fixed
