### ISSUE TITLE
neo4j Query encoding issues on special chars,

### ISSUE THREAD

**Issue by Genome8** [BloodHoundAD/BloodHound#91]
After beating my head against a wall for a day or so trying to find my missing nodes I discovered a issue with the NEO4J Rest API that would error when special char's like "l-N" were close to other character. This resulted in me finding different format errors returned by the API.

To overcome this limitation, I created a PowerShell .net implementation of the NEO4J BOLT Driver which can be found here ( https://www.github.com/genome8/NEO4J-PowerShell-Driver ).

I love what you guys are doing, and hope to contribute more soon to this Awesome Project and the Empire Project!
* With the BOLT protocol you can now have "\\" as long as you encode "\" as "\\" or "\\" as "\\\\".
-L

**Comment by rvazarkar** [comment]
This is incredible. Are you in the BloodHound slack by any chance?

**Comment by rvazarkar** [comment]
https://bloodhoundgang.herokuapp.com/

**Comment by rvazarkar** [comment]
Going to go ahead and close this, the issue hopefully shouldn't be present in the new ingestor/UI
