### ISSUE TITLE
Local Administrator shown as Domain Administrator

### ISSUE THREAD

**Issue by Cashfl0w** [BloodHoundAD/BloodHound#93]
I'm seeing issues where sessions running on workstations under the local administrator account are being appended with the domain name suffix thereby giving the impression that someone is using my Domain Administrator account when that's not the case.  _(this scared the £$%£$ out of my a few weeks ago!)_

Is there a way to differentiate between a local account and a domain account?  Maybe colour them differently or drop the domain suffix?

**Comment by rvazarkar** [comment]
Unfortunately, when we retrieve session data, we don't know what domain they're from or even if they are from a domain.

All we get is a username. We do some deconfliction by searching the domain and global catalog to see if that user exists. However, there's no way for us to determine if a session is actually coming from a domain user. It's one of the limitations of the windows API. 

BloodHound doesn't collect local accounts as of now, so we assume everything is a domain account for sessions.

**Comment by Cashfl0w** [comment]
Understood.  Thanks for the super quick response.
