### ISSUE TITLE
Error While trying to Import BloodHound.ps1 file

### ISSUE THREAD

**Issue by adimenia** [BloodHoundAD/BloodHound#94]
Hello,

im trying to run the following command on windows 7 Pro build 7600.

Import-Module .\BloodHound.ps1 (from the directory were the file is located) and im getting the following Error.
![image](https://cloud.githubusercontent.com/assets/5006200/24321266/24903f7c-1159-11e7-9dbb-4abc70ea1eb3.png)
any ideas?

**Comment by rvazarkar** [comment]
You downloaded the html of the page. Download the raw version
