### ISSUE TITLE
How to use the Neo4j Rest API?

### ISSUE THREAD

**Issue by new-gen23** [BloodHoundAD/BloodHound#95]
I have set up Neo4j to listen on:

> Bolt enabled on 0.0.0.0:7687.
> Remote interface available at http://localhost:7474/

Bloodhound is connecting with success to port 7687. Now, I tried to let the Powershell Script stream to the port by using:

> Invoke-BloodHound  -UserPass neo4j:mypass -URI "bolt://192.168.1.1:7687"

This fails with the error:

> "Error connecting to Neo4j rest REST server at '$($URI.AbsoluteUri)'"
> OperationStopped: (Error connectin...1.1:7687/rest':String) [], RuntimeException

Is the URI Parameter correct?
Do I have to create a database in Neo4j first? -> How?

**Comment by rvazarkar** [comment]
The rest API is on port 7474 and uses http not bolt. The powershell
ingestor does not support bolt.

**Comment by new-gen23** [comment]
Confirmed !
Correct command would be:  

> Invoke-BloodHound  -UserPass user:pass -URI "http://192.168.1.1:7474"

While monitoring the traffic, I often see:
Unable to deserialize request: Invalid UTF-8 middle byte 0x66
 at [Source: HttpInputOverHTTP@7ec49a70; line: 1, column: 1715]

**Comment by rvazarkar** [comment]
Its possible if you have non-standard characters in your output. Something we'll have fixed with the revised ingestor.

**Comment by bkr32** [comment]
@new-gen23  what exactly did you change in the config file? i've tried the above command but it fails with the error ```
Error connecting to Neo4j rest REST server at 'http://192.168.0.17:7474/'
At line:4991 char:17
+ ...             throw "Error connecting to Neo4j rest REST server at '$($ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error connectin...168.0.17:7474/':String) [], RuntimeException
    + FullyQualifiedErrorId : Error connecting to Neo4j rest REST server at 'http://192.168.0.17:7474/'
```
checking the file it's authorization thats wrong username is neo4j and i've tried all given passwords from neo4j BloodHound to my own pass

**Comment by RamblingCookieMonster** [comment]
I've tried messing with encoding on the vm, no luck with either of these (file.encoding is hard coded to UTF-8 in their odd management powershell module that builds the jvm args)

```
dbms.jvm.additional=-Dfile.encoding=UTF-8
dbms.jvm.additional=-Dsun.jnu.encoding=UTF-8
```

Anyone run into this and have a workaround, outside of sanitizing `[^\x00-\x7F]` characters?

**Comment by rvazarkar** [comment]
I *think* the new rest api code in SharpHound should handle non-ascii characters gracefully. Try it and let me know
